INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000005, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000298, '0', NULL, 132, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000011, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000436, '1', NULL, 132, 'Y', 'MAN', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000012, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000300, '0', NULL, 132, 'Y', 'RES', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000013, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000301, '0', NULL, 132, 'Y', 'END', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000015, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000301, '0', NULL, 132, 'Y', 'MAN', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000024, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000357, '0', NULL, 1000002, 'B', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000025, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000489, '1', NULL, 1000002, 'B', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000026, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000263, '0', NULL, 1000003, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000027, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000264, '0', NULL, 1000003, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000028, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000398, '1', NULL, 1000003, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000029, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000399, '1', NULL, 1000003, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000030, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000302, '0', NULL, 1000003, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000031, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000303, '1', NULL, 1000003, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000032, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000437, '1', NULL, 1000003, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000033, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000438, '1', NULL, 1000003, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000035, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000292, '0', 1000003, 132, 'N', NULL, 'B', 1000005, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000034, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000292, '0', 1000003, 132, 'N', NULL, 'B', 1000000, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000036, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000293, '0', 1000003, 132, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000037, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000294, '0', 1000003, 132, 'B', NULL, 'B', 1000002, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000038, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000295, '0', 1000003, 132, 'B', NULL, 'B', 1000001, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000041, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000426, '1', 1000003, 132, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000042, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000427, '1', 1000003, 132, 'B', NULL, 'B', 1000005, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000043, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000427, '1', 1000003, 132, 'B', NULL, 'B', 1000000, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000044, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000428, '1', 1000003, 132, 'B', 'END', 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000045, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000428, '1', 1000003, 132, 'B', 'RES', 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000046, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000429, '1', 1000003, 132, 'B', NULL, 'B', 1000002, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000039, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000296, '0', 1000003, 132, 'B', NULL, 'B', 1000007, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000047, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000430, '1', 1000003, 132, 'B', NULL, 'B', 1000001, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000048, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000431, '1', 1000003, 132, 'B', NULL, 'B', 1000007, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000050, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000314, '0', NULL, 1000004, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000051, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000448, '1', NULL, 1000004, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000053, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000477, '1', NULL, 1000005, 'B', NULL, 'B', NULL, '1000765', NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000052, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000345, '0', NULL, 1000005, 'B', NULL, 'B', NULL, '1000767', NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000054, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000347, '0', NULL, 1000006, 'B', NULL, 'B', NULL, '1000768', NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000055, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000479, '1', NULL, 1000006, 'B', NULL, 'B', NULL, '1000769', NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000056, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000350, '0', NULL, 1000000, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000057, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000482, '1', NULL, 1000000, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000058, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000487, '1', NULL, 1000007, 'B', NULL, 'B', NULL, '1000773', NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000059, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000355, '0', NULL, 1000007, 'B', NULL, 'B', NULL, '1000774', NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000064, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000017, '0', NULL, 1000008, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000065, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000018, '0', NULL, 131, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000088, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000195, '1', NULL, 1000011, 'B', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000089, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000103, '0', NULL, 1000013, 'B', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000090, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000207, '1', NULL, 1000013, 'B', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000091, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000362, '0', NULL, 1000014, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000092, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000494, '1', NULL, 1000014, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000094, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000320, '0', NULL, 1000015, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000095, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000454, '1', NULL, 1000015, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000096, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000018, '0', NULL, 1000016, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000097, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000017, '0', NULL, 1000016, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000105, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000212, '1', NULL, 1000017, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000108, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000168, '1', NULL, 1000018, 'N', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000109, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000157, '1', NULL, 1000018, 'Y', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000111, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000173, '1', NULL, 1000019, 'N', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000113, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000158, '1', NULL, 1000019, 'Y', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000116, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000050, '0', NULL, 1000020, 'Y', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000121, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000201, '1', NULL, 1000022, 'B', NULL, 'B', NULL, '1000782', NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000122, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000067, '0', NULL, 1000023, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000123, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000528, '1', NULL, 1000023, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000129, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000109, '0', NULL, 1000027, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000130, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000212, '1', NULL, 1000027, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000131, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000373, '0', NULL, 1000028, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000132, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000502, '1', NULL, 1000028, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000133, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000107, '0', NULL, 1000029, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000128, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000145, '1', 1000002, 126, 'B', NULL, 'B', 1000002, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000124, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000321, '0', NULL, 1000024, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000125, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000529, '1', NULL, 1000024, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000126, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000366, '0', NULL, 1000025, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000118, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000028, '0', 1000001, 126, 'B', NULL, 'B', 1000001, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000119, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000138, '1', 1000001, 126, 'B', NULL, 'B', 1000001, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000085, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000041, '0', 1000003, 126, 'B', NULL, 'B', 1000003, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000086, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000151, '1', 1000003, 126, 'B', NULL, 'B', 1000003, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000127, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000035, '0', 1000002, 126, 'B', NULL, 'B', 1000002, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000076, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000000, '0', 1000000, 126, 'N', 'MAN', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000078, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000001, '0', 1000000, 126, 'N', 'RES', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000114, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000014, '0', 1000000, 1000020, 'N', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000060, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000017, '0', 1000000, 131, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000061, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000018, '0', 1000000, 1000008, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000079, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000045, '0', 1000000, 126, 'Y', 'MAN', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000080, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000046, '0', 1000000, 126, 'Y', 'RES', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000107, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000047, '0', 1000000, 1000018, 'Y', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000112, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000048, '0', 1000000, 1000019, 'Y', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000062, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000051, '0', 1000000, 131, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000066, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000051, '0', 1000000, 131, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000099, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000051, '0', 1000000, 1000016, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000063, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000052, '0', 1000000, 131, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000067, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000052, '0', 1000000, 131, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000098, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000052, '0', 1000000, 1000016, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000106, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000060, '0', 1000000, 1000018, 'N', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000110, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000065, '0', 1000000, 1000019, 'N', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000134, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000086, '0', 1000000, 1000030, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000087, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000091, '0', 1000000, 1000011, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000120, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000097, '0', 1000000, 1000022, 'B', NULL, 'B', NULL, '1000781', NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000104, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000109, '0', 1000000, 1000017, 'B', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000081, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000110, '1', 1000000, 126, 'N', 'MAN', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000082, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000111, '1', 1000000, 126, 'N', 'RES', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000019, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000380, '1', 1000000, 132, 'N', NULL, 'Y', 1000006, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000007, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000433, '1', 1000000, 132, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000009, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000436, '1', 1000000, 132, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000115, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000124, '1', 1000000, 1000020, 'N', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000068, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000127, '1', 1000000, 1000008, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000069, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000127, '1', 1000000, 131, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000103, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000127, '1', 1000000, 1000016, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000070, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000128, '1', 1000000, 1000008, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000071, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000128, '1', 1000000, 131, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000102, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000128, '1', 1000000, 1000016, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000083, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000155, '1', 1000000, 126, 'Y', 'MAN', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000084, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000156, '1', 1000000, 126, 'Y', 'RES', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000117, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000160, '1', 1000000, 1000020, 'Y', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000072, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000161, '1', 1000000, 1000008, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000074, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000162, '1', 1000000, 1000008, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000075, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000162, '1', 1000000, 131, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000101, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000162, '1', 1000000, 1000016, 'Y', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000073, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000161, '1', 1000000, 131, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000100, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000161, '1', 1000000, 1000016, 'Y', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000008, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000435, '1', 1000000, 132, 'Y', 'END', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000017, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000375, '1', NULL, 132, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000016, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000242, '0', 1000000, 132, 'N', NULL, 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000004, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000241, '0', 1000000, 132, 'N', NULL, 'Y', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000006, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000374, '1', 1000000, 132, 'N', NULL, 'B', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000018, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000381, '1', 1000000, 132, 'N', NULL, 'N', 1000006, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000049, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000432, '1', 1000003, 132, 'N', 'END', 'N', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.LBR_CFOPLINE(lbr_cfopline_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_cfop_id, lbr_destionationtype, lbr_productcategory_id, c_doctype_id, lbr_issubtributaria, lbr_transactiontype, lbr_ismanufactured, lbr_bpartnercategory_id, lbr_tax_id, lbr_taxstatus, lbr_legalmessage_id)
  VALUES(1000040, 11, 11, 'Y', sysdate, 100, sysdate, 100, 1000297, '0', 1000003, 132, 'N', 'END', 'N', NULL, NULL, NULL, NULL);
exit
