-- BUGFIX SEQUENCE CHECK
UPDATE AD_SEQUENCE SET AD_SEQUENCE_ID = 1000076 WHERE NAME like 'LBR_ProcessLink';
UPDATE AD_SEQUENCE SET AD_SEQUENCE_ID = 1000077 WHERE NAME like 'LBR_OtherNFLink';
UPDATE AD_SEQUENCE SET CURRENTNEXT = (SELECT MAX(AD_SEQUENCE_ID) + 1 FROM AD_SEQUENCE) WHERE AD_SEQUENCE_ID = 16;

exit
