/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Inclusão de Abatimento em Boleto Bancário
 */

public class Abatimento {
  private Double valorAbatimento = null;

  public Abatimento valorAbatimento(Double valorAbatimento) {
    this.valorAbatimento = valorAbatimento;
    return this;
  }

   /**
   * Valor do abatimento (reduz valor do boleto) expresso em moeda corrente.
   * @return valorAbatimento
  **/
  public Double getValorAbatimento() {
    return valorAbatimento;
  }

  public void setValorAbatimento(Double valorAbatimento) {
    this.valorAbatimento = valorAbatimento;
  }



}
