/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Alteração das datas limites para concessão de desconto no Boleto Bancário
 */

public class AlteracaoDataDesconto {
  private String novaDataLimitePrimeiroDesconto = null;

  private String novaDataLimiteSegundoDesconto = null;

  private String novaDataLimiteTerceiroDesconto = null;

  public AlteracaoDataDesconto novaDataLimitePrimeiroDesconto(String novaDataLimitePrimeiroDesconto) {
    this.novaDataLimitePrimeiroDesconto = novaDataLimitePrimeiroDesconto;
    return this;
  }

   /**
   * Nova data limite do Primeiro Desconto
   * @return novaDataLimitePrimeiroDesconto
  **/
  public String getNovaDataLimitePrimeiroDesconto() {
    return novaDataLimitePrimeiroDesconto;
  }

  public void setNovaDataLimitePrimeiroDesconto(String novaDataLimitePrimeiroDesconto) {
    this.novaDataLimitePrimeiroDesconto = novaDataLimitePrimeiroDesconto;
  }

  public AlteracaoDataDesconto novaDataLimiteSegundoDesconto(String novaDataLimiteSegundoDesconto) {
    this.novaDataLimiteSegundoDesconto = novaDataLimiteSegundoDesconto;
    return this;
  }

   /**
   * Nova data limite do Segundo Desconto 
   * @return novaDataLimiteSegundoDesconto
  **/
  public String getNovaDataLimiteSegundoDesconto() {
    return novaDataLimiteSegundoDesconto;
  }

  public void setNovaDataLimiteSegundoDesconto(String novaDataLimiteSegundoDesconto) {
    this.novaDataLimiteSegundoDesconto = novaDataLimiteSegundoDesconto;
  }

  public AlteracaoDataDesconto novaDataLimiteTerceiroDesconto(String novaDataLimiteTerceiroDesconto) {
    this.novaDataLimiteTerceiroDesconto = novaDataLimiteTerceiroDesconto;
    return this;
  }

   /**
   * Nova data limite do Terceiro Desconto
   * @return novaDataLimiteTerceiroDesconto
  **/
  public String getNovaDataLimiteTerceiroDesconto() {
    return novaDataLimiteTerceiroDesconto;
  }

  public void setNovaDataLimiteTerceiroDesconto(String novaDataLimiteTerceiroDesconto) {
    this.novaDataLimiteTerceiroDesconto = novaDataLimiteTerceiroDesconto;
  }

}
