/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Alteração de prazo limite de aceite após vencimento de Boleto Bancário
 */

public class AlteracaoPrazo {
	private Integer quantidadeDiasAceite = null;

	public AlteracaoPrazo quantidadeDiasAceite(Integer quantidadeDiasAceite) {
		this.quantidadeDiasAceite = quantidadeDiasAceite;
		return this;
	}

	/**
	 * Quantidade máxima de dias corridos para recebimento do boleto após a data de
	 * vencimento
	 * 
	 * @return quantidadeDiasAceite
	 **/
	public Integer getQuantidadeDiasAceite() {
		return quantidadeDiasAceite;
	}

	public void setQuantidadeDiasAceite(Integer quantidadeDiasAceite) {
		this.quantidadeDiasAceite = quantidadeDiasAceite;
	}

}
