/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Alteração de Seu Número em Boleto Bancário
 */

public class AlteracaoSeuNumero {
  private String codigoSeuNumero = null;

  public AlteracaoSeuNumero codigoSeuNumero(String codigoSeuNumero) {
    this.codigoSeuNumero = codigoSeuNumero;
    return this;
  }

   /**
   * Número adotado e controlado pelo Cliente, para identificar o título de cobrança.
   * @return codigoSeuNumero
  **/
  public String getCodigoSeuNumero() {
    return codigoSeuNumero;
  }

  public void setCodigoSeuNumero(String codigoSeuNumero) {
    this.codigoSeuNumero = codigoSeuNumero;
  }


}
