/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Alteração de desconto em Boletos Bancários
 */

public class AlteracaoDesconto {
  private Integer tipoPrimeiroDesconto = null;

  private Double novoValorPrimeiroDesconto = null;

  private Double novoPercentualPrimeiroDesconto = null;

  private String novaDataLimitePrimeiroDesconto = null;

  private Integer tipoSegundoDesconto = null;

  private Double novoValorSegundoDesconto = null;

  private Double novoPercentualSegundoDesconto = null;

  private String novaDataLimiteSegundoDesconto = null;

  private Integer tipoTerceiroDesconto = null;

  private Double novoValorTerceiroDesconto = null;

  private Double novoPercentualTerceiroDesconto = null;

  private String novaDataLimiteTerceiroDesconto = null;

  public AlteracaoDesconto tipoPrimeiroDesconto(Integer tipoPrimeiroDesconto) {
    this.tipoPrimeiroDesconto = tipoPrimeiroDesconto;
    return this;
  }

   /**
   * Código para identificação do tipo de desconto que deverá ser concedido como Primeiro Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data        2 - Percentual até a data informada 3 - Desconto por dia de antecipação
   * @return tipoPrimeiroDesconto
  **/
  public Integer getTipoPrimeiroDesconto() {
    return tipoPrimeiroDesconto;
  }

  public void setTipoPrimeiroDesconto(Integer tipoPrimeiroDesconto) {
    this.tipoPrimeiroDesconto = tipoPrimeiroDesconto;
  }

  public AlteracaoDesconto novoValorPrimeiroDesconto(Double novoValorPrimeiroDesconto) {
    this.novoValorPrimeiroDesconto = novoValorPrimeiroDesconto;
    return this;
  }

   /**
   * Novo valor do Primeiro Desconto
   * @return novoValorPrimeiroDesconto
  **/
  public Double getNovoValorPrimeiroDesconto() {
    return novoValorPrimeiroDesconto;
  }

  public void setNovoValorPrimeiroDesconto(Double novoValorPrimeiroDesconto) {
    this.novoValorPrimeiroDesconto = novoValorPrimeiroDesconto;
  }

  public AlteracaoDesconto novoPercentualPrimeiroDesconto(Double novoPercentualPrimeiroDesconto) {
    this.novoPercentualPrimeiroDesconto = novoPercentualPrimeiroDesconto;
    return this;
  }

   /**
   * Novo percentual de desconto sobre o valor do boleto no Primeiro Desconto
   * @return novoPercentualPrimeiroDesconto
  **/
  public Double getNovoPercentualPrimeiroDesconto() {
    return novoPercentualPrimeiroDesconto;
  }

  public void setNovoPercentualPrimeiroDesconto(Double novoPercentualPrimeiroDesconto) {
    this.novoPercentualPrimeiroDesconto = novoPercentualPrimeiroDesconto;
  }

  public AlteracaoDesconto novaDataLimitePrimeiroDesconto(String novaDataLimitePrimeiroDesconto) {
    this.novaDataLimitePrimeiroDesconto = novaDataLimitePrimeiroDesconto;
    return this;
  }

   /**
   * Nova data limite do Primeiro Desconto
   * @return novaDataLimitePrimeiroDesconto
  **/
  public String getNovaDataLimitePrimeiroDesconto() {
    return novaDataLimitePrimeiroDesconto;
  }

  public void setNovaDataLimitePrimeiroDesconto(String novaDataLimitePrimeiroDesconto) {
    this.novaDataLimitePrimeiroDesconto = novaDataLimitePrimeiroDesconto;
  }

  public AlteracaoDesconto tipoSegundoDesconto(Integer tipoSegundoDesconto) {
    this.tipoSegundoDesconto = tipoSegundoDesconto;
    return this;
  }

   /**
   * Código para identificação do tipo de desconto que deverá ser concedido como Segundo Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data        2 - Percentual até a data informada 3 - Desconto por dia de antecipação
   * @return tipoSegundoDesconto
  **/
  public Integer getTipoSegundoDesconto() {
    return tipoSegundoDesconto;
  }

  public void setTipoSegundoDesconto(Integer tipoSegundoDesconto) {
    this.tipoSegundoDesconto = tipoSegundoDesconto;
  }

  public AlteracaoDesconto novoValorSegundoDesconto(Double novoValorSegundoDesconto) {
    this.novoValorSegundoDesconto = novoValorSegundoDesconto;
    return this;
  }

   /**
   * Novo valor do Segundo Desconto 
   * @return novoValorSegundoDesconto
  **/
  public Double getNovoValorSegundoDesconto() {
    return novoValorSegundoDesconto;
  }

  public void setNovoValorSegundoDesconto(Double novoValorSegundoDesconto) {
    this.novoValorSegundoDesconto = novoValorSegundoDesconto;
  }

  public AlteracaoDesconto novoPercentualSegundoDesconto(Double novoPercentualSegundoDesconto) {
    this.novoPercentualSegundoDesconto = novoPercentualSegundoDesconto;
    return this;
  }

   /**
   * Novo percentual de desconto sobre o valor do boleto no Segundo Desconto
   * @return novoPercentualSegundoDesconto
  **/
  public Double getNovoPercentualSegundoDesconto() {
    return novoPercentualSegundoDesconto;
  }

  public void setNovoPercentualSegundoDesconto(Double novoPercentualSegundoDesconto) {
    this.novoPercentualSegundoDesconto = novoPercentualSegundoDesconto;
  }

  public AlteracaoDesconto novaDataLimiteSegundoDesconto(String novaDataLimiteSegundoDesconto) {
    this.novaDataLimiteSegundoDesconto = novaDataLimiteSegundoDesconto;
    return this;
  }

   /**
   * Nova data limite do Segundo Desconto
   * @return novaDataLimiteSegundoDesconto
  **/
  public String getNovaDataLimiteSegundoDesconto() {
    return novaDataLimiteSegundoDesconto;
  }

  public void setNovaDataLimiteSegundoDesconto(String novaDataLimiteSegundoDesconto) {
    this.novaDataLimiteSegundoDesconto = novaDataLimiteSegundoDesconto;
  }

  public AlteracaoDesconto tipoTerceiroDesconto(Integer tipoTerceiroDesconto) {
    this.tipoTerceiroDesconto = tipoTerceiroDesconto;
    return this;
  }

   /**
   * Código para identificação do tipo de desconto que deverá ser concedido como Terceiro Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data        2 - Percentual até a data informada 3 - Desconto por dia de antecipação
   * @return tipoTerceiroDesconto
  **/
  public Integer getTipoTerceiroDesconto() {
    return tipoTerceiroDesconto;
  }

  public void setTipoTerceiroDesconto(Integer tipoTerceiroDesconto) {
    this.tipoTerceiroDesconto = tipoTerceiroDesconto;
  }

  public AlteracaoDesconto novoValorTerceiroDesconto(Double novoValorTerceiroDesconto) {
    this.novoValorTerceiroDesconto = novoValorTerceiroDesconto;
    return this;
  }

   /**
   * Novo valor do Terceiro Desconto
   * @return novoValorTerceiroDesconto
  **/
  public Double getNovoValorTerceiroDesconto() {
    return novoValorTerceiroDesconto;
  }

  public void setNovoValorTerceiroDesconto(Double novoValorTerceiroDesconto) {
    this.novoValorTerceiroDesconto = novoValorTerceiroDesconto;
  }

  public AlteracaoDesconto novoPercentualTerceiroDesconto(Double novoPercentualTerceiroDesconto) {
    this.novoPercentualTerceiroDesconto = novoPercentualTerceiroDesconto;
    return this;
  }

   /**
   * Novo percentual de desconto sobre o valor do boleto no Terceiro Desconto
   * @return novoPercentualTerceiroDesconto
  **/
  public Double getNovoPercentualTerceiroDesconto() {
    return novoPercentualTerceiroDesconto;
  }

  public void setNovoPercentualTerceiroDesconto(Double novoPercentualTerceiroDesconto) {
    this.novoPercentualTerceiroDesconto = novoPercentualTerceiroDesconto;
  }

  public AlteracaoDesconto novaDataLimiteTerceiroDesconto(String novaDataLimiteTerceiroDesconto) {
    this.novaDataLimiteTerceiroDesconto = novaDataLimiteTerceiroDesconto;
    return this;
  }

   /**
   * Nova data limite do Terceiro Desconto
   * @return novaDataLimiteTerceiroDesconto
  **/
  public String getNovaDataLimiteTerceiroDesconto() {
    return novaDataLimiteTerceiroDesconto;
  }

  public void setNovaDataLimiteTerceiroDesconto(String novaDataLimiteTerceiroDesconto) {
    this.novaDataLimiteTerceiroDesconto = novaDataLimiteTerceiroDesconto;
  }

}
