/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Alteração de dados do Endereço do Pagador em Boleto bancário
 */

public class AlteracaoEndereco {
  private String enderecoPagador = null;

  private String bairroPagador = null;

  private String cidadePagador = null;

  private String ufPagador = null;

  private Integer cePPagador = null;

  public AlteracaoEndereco enderecoPagador(String enderecoPagador) {
    this.enderecoPagador = enderecoPagador;
    return this;
  }

   /**
   * Endereço do Pagador
   * @return enderecoPagador
  **/
  public String getEnderecoPagador() {
    return enderecoPagador;
  }

  public void setEnderecoPagador(String enderecoPagador) {
    this.enderecoPagador = enderecoPagador;
  }

  public AlteracaoEndereco bairroPagador(String bairroPagador) {
    this.bairroPagador = bairroPagador;
    return this;
  }

   /**
   * Bairro do Pagador
   * @return bairroPagador
  **/
  public String getBairroPagador() {
    return bairroPagador;
  }

  public void setBairroPagador(String bairroPagador) {
    this.bairroPagador = bairroPagador;
  }

  public AlteracaoEndereco cidadePagador(String cidadePagador) {
    this.cidadePagador = cidadePagador;
    return this;
  }

   /**
   * Cidade do Pagador
   * @return cidadePagador
  **/
  public String getCidadePagador() {
    return cidadePagador;
  }

  public void setCidadePagador(String cidadePagador) {
    this.cidadePagador = cidadePagador;
  }

  public AlteracaoEndereco ufPagador(String ufPagador) {
    this.ufPagador = ufPagador;
    return this;
  }

   /**
   * UF do Pagador
   * @return ufPagador
  **/
  public String getUfPagador() {
    return ufPagador;
  }

  public void setUfPagador(String ufPagador) {
    this.ufPagador = ufPagador;
  }

  public AlteracaoEndereco cePPagador(Integer cePPagador) {
    this.cePPagador = cePPagador;
    return this;
  }

   /**
   * CEP do Pagador
   * @return cePPagador
  **/
  public Integer getCePPagador() {
    return cePPagador;
  }

  public void setCePPagador(Integer cePPagador) {
    this.cePPagador = cePPagador;
  }

}
