/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.Objects;

/**
 * Alteração de data de vencimento do boleto.
 */

public class AlteracaoData {
	private String novaDataVencimento = null;

	public AlteracaoData novaDataVencimento(String novaDataVencimento) {
		this.novaDataVencimento = novaDataVencimento;
		return this;
	}

	/**
	 * Nova data de vencimento do boleto.
	 * 
	 * @return novaDataVencimento
	 **/
	public String getNovaDataVencimento() {
		return novaDataVencimento;
	}

	public void setNovaDataVencimento(String novaDataVencimento) {
		this.novaDataVencimento = novaDataVencimento;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AlteracaoData alteracaoData = (AlteracaoData) o;
		return Objects.equals(this.novaDataVencimento, alteracaoData.novaDataVencimento);
	}

	@Override
	public int hashCode() {
		return Objects.hash(novaDataVencimento);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AlteracaoData {\n");

		sb.append("    novaDataVencimento: ").append(toIndentedString(novaDataVencimento)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
