/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Alterar valor do abatimento concedido em um Boleto Bancário
 */
public class AlteracaoAbatimento {
  private Double novoValorAbatimento = null;

  public AlteracaoAbatimento novoValorAbatimento(Double novoValorAbatimento) {
    this.novoValorAbatimento = novoValorAbatimento;
    return this;
  }

   /**
   * Novo valor do abatimento (reduz valor do boleto) expresso em moeda corrente.
   * @return novoValorAbatimento
  **/
  public Double getNovoValorAbatimento() {
    return novoValorAbatimento;
  }

  public void setNovoValorAbatimento(Double novoValorAbatimento) {
    this.novoValorAbatimento = novoValorAbatimento;
  }



}
