/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Inclusão de desconto em Boleto Bancário
 */
public class Desconto {
  private Integer tipoPrimeiroDesconto = null;

  private Double valorPrimeiroDesconto = null;

  private Double percentualPrimeiroDesconto = null;

  private String dataPrimeiroDesconto = null;

  private Integer tipoSegundoDesconto = null;

  private Double valorSegundoDesconto = null;

  private Double percentualSegundoDesconto = null;

  private String dataSegundoDesconto = null;

  private Integer tipoTerceiroDesconto = null;

  private Double valorTerceiroDesconto = null;

  private Double percentualTerceiroDesconto = null;

  private String dataTerceiroDesconto = null;

  public Desconto tipoPrimeiroDesconto(Integer tipoPrimeiroDesconto) {
    this.tipoPrimeiroDesconto = tipoPrimeiroDesconto;
    return this;
  }

   /**
   * Código para identificação do tipo de desconto que deverá ser concedido como Primeiro Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data        2 - Percentual até a data informada 3 - Desconto por dia de antecipação
   * @return tipoPrimeiroDesconto
  **/
  public Integer getTipoPrimeiroDesconto() {
    return tipoPrimeiroDesconto;
  }

  public void setTipoPrimeiroDesconto(Integer tipoPrimeiroDesconto) {
    this.tipoPrimeiroDesconto = tipoPrimeiroDesconto;
  }

  public Desconto valorPrimeiroDesconto(Double valorPrimeiroDesconto) {
    this.valorPrimeiroDesconto = valorPrimeiroDesconto;
    return this;
  }

   /**
   * Valor do Primeiro Desconto 
   * @return valorPrimeiroDesconto
  **/
  public Double getValorPrimeiroDesconto() {
    return valorPrimeiroDesconto;
  }

  public void setValorPrimeiroDesconto(Double valorPrimeiroDesconto) {
    this.valorPrimeiroDesconto = valorPrimeiroDesconto;
  }

  public Desconto percentualPrimeiroDesconto(Double percentualPrimeiroDesconto) {
    this.percentualPrimeiroDesconto = percentualPrimeiroDesconto;
    return this;
  }

   /**
   * Percentual de desconto sobre o valor do boleto no Primeiro Desconto 
   * @return percentualPrimeiroDesconto
  **/
  public Double getPercentualPrimeiroDesconto() {
    return percentualPrimeiroDesconto;
  }

  public void setPercentualPrimeiroDesconto(Double percentualPrimeiroDesconto) {
    this.percentualPrimeiroDesconto = percentualPrimeiroDesconto;
  }

  public Desconto dataPrimeiroDesconto(String dataPrimeiroDesconto) {
    this.dataPrimeiroDesconto = dataPrimeiroDesconto;
    return this;
  }

   /**
   * Data limite do Primeiro Desconto 
   * @return dataPrimeiroDesconto
  **/
  public String getDataPrimeiroDesconto() {
    return dataPrimeiroDesconto;
  }

  public void setDataPrimeiroDesconto(String dataPrimeiroDesconto) {
    this.dataPrimeiroDesconto = dataPrimeiroDesconto;
  }

  public Desconto tipoSegundoDesconto(Integer tipoSegundoDesconto) {
    this.tipoSegundoDesconto = tipoSegundoDesconto;
    return this;
  }

   /**
   * Código para identificação do tipo de desconto que deverá ser concedido como Segundo Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data        2 - Percentual até a data informada 3 - Desconto por dia de antecipação
   * @return tipoSegundoDesconto
  **/
  public Integer getTipoSegundoDesconto() {
    return tipoSegundoDesconto;
  }

  public void setTipoSegundoDesconto(Integer tipoSegundoDesconto) {
    this.tipoSegundoDesconto = tipoSegundoDesconto;
  }

  public Desconto valorSegundoDesconto(Double valorSegundoDesconto) {
    this.valorSegundoDesconto = valorSegundoDesconto;
    return this;
  }

   /**
   * Valor do Segundo Desconto 
   * @return valorSegundoDesconto
  **/
  public Double getValorSegundoDesconto() {
    return valorSegundoDesconto;
  }

  public void setValorSegundoDesconto(Double valorSegundoDesconto) {
    this.valorSegundoDesconto = valorSegundoDesconto;
  }

  public Desconto percentualSegundoDesconto(Double percentualSegundoDesconto) {
    this.percentualSegundoDesconto = percentualSegundoDesconto;
    return this;
  }

   /**
   * Percentual de desconto sobre o valor do boleto no Segundo Desconto 
   * @return percentualSegundoDesconto
  **/
  public Double getPercentualSegundoDesconto() {
    return percentualSegundoDesconto;
  }

  public void setPercentualSegundoDesconto(Double percentualSegundoDesconto) {
    this.percentualSegundoDesconto = percentualSegundoDesconto;
  }

  public Desconto dataSegundoDesconto(String dataSegundoDesconto) {
    this.dataSegundoDesconto = dataSegundoDesconto;
    return this;
  }

   /**
   * Data limite do Segundo Desconto 
   * @return dataSegundoDesconto
  **/
  public String getDataSegundoDesconto() {
    return dataSegundoDesconto;
  }

  public void setDataSegundoDesconto(String dataSegundoDesconto) {
    this.dataSegundoDesconto = dataSegundoDesconto;
  }

  public Desconto tipoTerceiroDesconto(Integer tipoTerceiroDesconto) {
    this.tipoTerceiroDesconto = tipoTerceiroDesconto;
    return this;
  }

   /**
   * Código para identificação do tipo de desconto que deverá ser concedido como Terceiro Desconto. Valores a informar: 0 - Sem desconto 1 - Valor fixo até a data        2 - Percentual até a data informada 3 - Desconto por dia de antecipação
   * @return tipoTerceiroDesconto
  **/
  public Integer getTipoTerceiroDesconto() {
    return tipoTerceiroDesconto;
  }

  public void setTipoTerceiroDesconto(Integer tipoTerceiroDesconto) {
    this.tipoTerceiroDesconto = tipoTerceiroDesconto;
  }

  public Desconto valorTerceiroDesconto(Double valorTerceiroDesconto) {
    this.valorTerceiroDesconto = valorTerceiroDesconto;
    return this;
  }

   /**
   * Valor do Terceiro Desconto 
   * @return valorTerceiroDesconto
  **/
  public Double getValorTerceiroDesconto() {
    return valorTerceiroDesconto;
  }

  public void setValorTerceiroDesconto(Double valorTerceiroDesconto) {
    this.valorTerceiroDesconto = valorTerceiroDesconto;
  }

  public Desconto percentualTerceiroDesconto(Double percentualTerceiroDesconto) {
    this.percentualTerceiroDesconto = percentualTerceiroDesconto;
    return this;
  }

   /**
   * Percentual de desconto sobre o valor do boleto no Terceiro Desconto 
   * @return percentualTerceiroDesconto
  **/
  public Double getPercentualTerceiroDesconto() {
    return percentualTerceiroDesconto;
  }

  public void setPercentualTerceiroDesconto(Double percentualTerceiroDesconto) {
    this.percentualTerceiroDesconto = percentualTerceiroDesconto;
  }

  public Desconto dataTerceiroDesconto(String dataTerceiroDesconto) {
    this.dataTerceiroDesconto = dataTerceiroDesconto;
    return this;
  }

   /**
   * Data limite do Terceiro Desconto 
   * @return dataTerceiroDesconto
  **/
  public String getDataTerceiroDesconto() {
    return dataTerceiroDesconto;
  }

  public void setDataTerceiroDesconto(String dataTerceiroDesconto) {
    this.dataTerceiroDesconto = dataTerceiroDesconto;
  }

}
