/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.Objects;
/**
 * Objeto de erro.
 */

public class Errov4Erros {
  private String codigo = null;

  private String versao = null;

  private String mensagem = null;

  private String ocorrencia = null;

  public Errov4Erros codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

   /**
   * Código da mensagem de erro.
   * @return codigo
  **/
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public Errov4Erros versao(String versao) {
    this.versao = versao;
    return this;
  }

   /**
   * Versão da mensagem de erro.
   * @return versao
  **/
  public String getVersao() {
    return versao;
  }

  public void setVersao(String versao) {
    this.versao = versao;
  }

  public Errov4Erros mensagem(String mensagem) {
    this.mensagem = mensagem;
    return this;
  }

   /**
   * Mensagem de erro.
   * @return mensagem
  **/
  public String getMensagem() {
    return mensagem;
  }

  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }

  public Errov4Erros ocorrencia(String ocorrencia) {
    this.ocorrencia = ocorrencia;
    return this;
  }

   /**
   * Código da ocorrência do erro. Não se trata de código HTTP.
   * @return ocorrencia
  **/
  public String getOcorrencia() {
    return ocorrencia;
  }

  public void setOcorrencia(String ocorrencia) {
    this.ocorrencia = ocorrencia;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Errov4Erros errov4Erros = (Errov4Erros) o;
    return Objects.equals(this.codigo, errov4Erros.codigo) &&
        Objects.equals(this.versao, errov4Erros.versao) &&
        Objects.equals(this.mensagem, errov4Erros.mensagem) &&
        Objects.equals(this.ocorrencia, errov4Erros.ocorrencia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, versao, mensagem, ocorrencia);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Errov4Erros {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    versao: ").append(toIndentedString(versao)).append("\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    ocorrencia: ").append(toIndentedString(ocorrencia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
