/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.ArrayList;
import java.util.List;
/**
 * Representação de um objeto de erro v2.
 */

public class ErroV2 {
  private List<Errov2Erros> erros = null;

  public ErroV2 erros(List<Errov2Erros> erros) {
    this.erros = erros;
    return this;
  }

  public ErroV2 addErrosItem(Errov2Erros errosItem) {
    if (this.erros == null) {
      this.erros = new ArrayList<Errov2Erros>();
    }
    this.erros.add(errosItem);
    return this;
  }

   /**
   * Get erros
   * @return erros
  **/
  public List<Errov2Erros> getErros() {
    return erros;
  }

  public void setErros(List<Errov2Erros> erros) {
    this.erros = erros;
  }

}
