/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Atributos do erro.
 */

public class ErroOAuthNaoAutorizadoAttributes {
  private String error = null;

  public ErroOAuthNaoAutorizadoAttributes error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Mensagem do erro.
   * @return error
  **/
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

}
