/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Errov2Erros
 */

public class Errov2Erros {
	private String codigo = null;

	private String versao = null;

	private String mensagem = null;

	private String ocorrencia = null;

	public Errov2Erros codigo(String codigo) {
		this.codigo = codigo;
		return this;
	}

	/**
	 * Get codigo
	 * 
	 * @return codigo
	 **/
	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Errov2Erros versao(String versao) {
		this.versao = versao;
		return this;
	}

	/**
	 * Get versao
	 * 
	 * @return versao
	 **/
	public String getVersao() {
		return versao;
	}

	public void setVersao(String versao) {
		this.versao = versao;
	}

	public Errov2Erros mensagem(String mensagem) {
		this.mensagem = mensagem;
		return this;
	}

	/**
	 * Get mensagem
	 * 
	 * @return mensagem
	 **/
	public String getMensagem() {
		return mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	public Errov2Erros ocorrencia(String ocorrencia) {
		this.ocorrencia = ocorrencia;
		return this;
	}

	/**
	 * Get ocorrencia
	 * 
	 * @return ocorrencia
	 **/
	public String getOcorrencia() {
		return ocorrencia;
	}

	public void setOcorrencia(String ocorrencia) {
		this.ocorrencia = ocorrencia;
	}

}
