/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * ErroErrors
 */

public class ErroErrors {
  private String code = null;

  private String message = null;

  public ErroErrors code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Código e versão do erro.
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ErroErrors message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Mensagem de erro.
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }



}
