/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.ArrayList;
import java.util.List;
/**
 * Representa os campos de erro de uma requisição a um recurso.
 */

public class ErroV4 {
  private List<Errov4Erros> erros = null;

  public ErroV4 erros(List<Errov4Erros> erros) {
    this.erros = erros;
    return this;
  }

  public ErroV4 addErrosItem(Errov4Erros errosItem) {
    if (this.erros == null) {
      this.erros = new ArrayList<Errov4Erros>();
    }
    this.erros.add(errosItem);
    return this;
  }

   /**
   * Lista que contém os objetos de erro.
   * @return erros
  **/
  public List<Errov4Erros> getErros() {
    return erros;
  }

  public void setErros(List<Errov4Erros> erros) {
    this.erros = erros;
  }



}
