/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.ArrayList;
import java.util.List;
/**
 * Representação de um objeto de erro.
 */

public class Erro {
  private List<ErroErrors> errors = null;

  public Erro errors(List<ErroErrors> errors) {
    this.errors = errors;
    return this;
  }

  public Erro addErrorsItem(ErroErrors errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ErroErrors>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  public List<ErroErrors> getErrors() {
    return errors;
  }

  public void setErrors(List<ErroErrors> errors) {
    this.errors = errors;
  }

}
