/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.math.BigDecimal;
/**
 * Representação de um objeto de erro do OAuth 2.0.
 */

public class ErroOAuthNaoAutorizado {
  private BigDecimal statusCode = null;

  private String error = null;

  private String message = null;

  private ErroOAuthNaoAutorizadoAttributes attributes = null;

  public ErroOAuthNaoAutorizado statusCode(BigDecimal statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Código do estado do erro.
   * @return statusCode
  **/
  public BigDecimal getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(BigDecimal statusCode) {
    this.statusCode = statusCode;
  }

  public ErroOAuthNaoAutorizado error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Tipo do erro.
   * @return error
  **/
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public ErroOAuthNaoAutorizado message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Mensagem do erro.
   * @return message
  **/
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ErroOAuthNaoAutorizado attributes(ErroOAuthNaoAutorizadoAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  public ErroOAuthNaoAutorizadoAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(ErroOAuthNaoAutorizadoAttributes attributes) {
    this.attributes = attributes;
  }

}
