/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.Objects;
/**
 * IdCancelarpixBody
 */


public class IdCancelarpixBody {
  private Integer numeroConvenio = null;

  public IdCancelarpixBody numeroConvenio(Integer numeroConvenio) {
    this.numeroConvenio = numeroConvenio;
    return this;
  }

   /**
   * Número do convênio de Cobrança do Cliente.
   * @return numeroConvenio
  **/
  public Integer getNumeroConvenio() {
    return numeroConvenio;
  }

  public void setNumeroConvenio(Integer numeroConvenio) {
    this.numeroConvenio = numeroConvenio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdCancelarpixBody idCancelarpixBody = (IdCancelarpixBody) o;
    return Objects.equals(this.numeroConvenio, idCancelarpixBody.numeroConvenio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroConvenio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdCancelarpixBody {\n");
    
    sb.append("    numeroConvenio: ").append(toIndentedString(numeroConvenio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
