/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * IdListarretornomovimentoBody
 */


public class IdListarretornomovimentoBody {
  private String dataMovimentoRetornoInicial = null;

  private String dataMovimentoRetornoFinal = null;

  private Long codigoPrefixoAgencia = null;

  private Long numeroContaCorrente = null;

  private Integer numeroCarteiraCobranca = null;

  private Integer numeroVariacaoCarteiraCobranca = null;

  private Long numeroRegistroPretendido = null;

  private Long quantidadeRegistroPretendido = null;

  public IdListarretornomovimentoBody dataMovimentoRetornoInicial(String dataMovimentoRetornoInicial) {
    this.dataMovimentoRetornoInicial = dataMovimentoRetornoInicial;
    return this;
  }

   /**
   * Data inicial do processamento do movimento de retorno de cobrança de Boleto.
   * @return dataMovimentoRetornoInicial
  **/
  public String getDataMovimentoRetornoInicial() {
    return dataMovimentoRetornoInicial;
  }

  public void setDataMovimentoRetornoInicial(String dataMovimentoRetornoInicial) {
    this.dataMovimentoRetornoInicial = dataMovimentoRetornoInicial;
  }

  public IdListarretornomovimentoBody dataMovimentoRetornoFinal(String dataMovimentoRetornoFinal) {
    this.dataMovimentoRetornoFinal = dataMovimentoRetornoFinal;
    return this;
  }

   /**
   * Data final do processamento do movimento de retorno de cobrança de Boleto.
   * @return dataMovimentoRetornoFinal
  **/
  public String getDataMovimentoRetornoFinal() {
    return dataMovimentoRetornoFinal;
  }

  public void setDataMovimentoRetornoFinal(String dataMovimentoRetornoFinal) {
    this.dataMovimentoRetornoFinal = dataMovimentoRetornoFinal;
  }

  public IdListarretornomovimentoBody codigoPrefixoAgencia(Long codigoPrefixoAgencia) {
    this.codigoPrefixoAgencia = codigoPrefixoAgencia;
    return this;
  }

   /**
   * Código do prefixo identificador de uma dependência do Banco.
   * @return codigoPrefixoAgencia
  **/
  public Long getCodigoPrefixoAgencia() {
    return codigoPrefixoAgencia;
  }

  public void setCodigoPrefixoAgencia(Long codigoPrefixoAgencia) {
    this.codigoPrefixoAgencia = codigoPrefixoAgencia;
  }

  public IdListarretornomovimentoBody numeroContaCorrente(Long numeroContaCorrente) {
    this.numeroContaCorrente = numeroContaCorrente;
    return this;
  }

   /**
   * Número identificador de uma Conta Corrente contratada pelo cliente junto ao Banco do Brasil.
   * @return numeroContaCorrente
  **/
  public Long getNumeroContaCorrente() {
    return numeroContaCorrente;
  }

  public void setNumeroContaCorrente(Long numeroContaCorrente) {
    this.numeroContaCorrente = numeroContaCorrente;
  }

  public IdListarretornomovimentoBody numeroCarteiraCobranca(Integer numeroCarteiraCobranca) {
    this.numeroCarteiraCobranca = numeroCarteiraCobranca;
    return this;
  }

   /**
   * Número identificador da carteira de Cobrança. Indica o tipo de serviço de cobrança, para o qual são aplicadas regras específicas.
   * @return numeroCarteiraCobranca
  **/
  public Integer getNumeroCarteiraCobranca() {
    return numeroCarteiraCobranca;
  }

  public void setNumeroCarteiraCobranca(Integer numeroCarteiraCobranca) {
    this.numeroCarteiraCobranca = numeroCarteiraCobranca;
  }

  public IdListarretornomovimentoBody numeroVariacaoCarteiraCobranca(Integer numeroVariacaoCarteiraCobranca) {
    this.numeroVariacaoCarteiraCobranca = numeroVariacaoCarteiraCobranca;
    return this;
  }

   /**
   * Número identificador da variação da Carteira de Cobrança. Identifica cada grupo de condições específicas (variação) para um mesmo tipo de serviço de cobrança contratado pelo cliente (carteira), visando separar os títulos de cobrança de acordo com os interesses do próprio cliente e previamente negociados com o Banco.
   * @return numeroVariacaoCarteiraCobranca
  **/
  public Integer getNumeroVariacaoCarteiraCobranca() {
    return numeroVariacaoCarteiraCobranca;
  }

  public void setNumeroVariacaoCarteiraCobranca(Integer numeroVariacaoCarteiraCobranca) {
    this.numeroVariacaoCarteiraCobranca = numeroVariacaoCarteiraCobranca;
  }

  public IdListarretornomovimentoBody numeroRegistroPretendido(Long numeroRegistroPretendido) {
    this.numeroRegistroPretendido = numeroRegistroPretendido;
    return this;
  }

   /**
   * Número do registro ou da página que deseja buscar na consulta. Quando primeira chamada, informar \&quot;001\&quot;
   * @return numeroRegistroPretendido
  **/
  public Long getNumeroRegistroPretendido() {
    return numeroRegistroPretendido;
  }

  public void setNumeroRegistroPretendido(Long numeroRegistroPretendido) {
    this.numeroRegistroPretendido = numeroRegistroPretendido;
  }

  public IdListarretornomovimentoBody quantidadeRegistroPretendido(Long quantidadeRegistroPretendido) {
    this.quantidadeRegistroPretendido = quantidadeRegistroPretendido;
    return this;
  }

   /**
   * Quantidade de registros ou páginas que desejar buscar na consulta. Quantidade máxima de 10000 boletos por chamada
   * @return quantidadeRegistroPretendido
  **/
  public Long getQuantidadeRegistroPretendido() {
    return quantidadeRegistroPretendido;
  }

  public void setQuantidadeRegistroPretendido(Long quantidadeRegistroPretendido) {
    this.quantidadeRegistroPretendido = quantidadeRegistroPretendido;
  }

}
