/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.Objects;
/**
 * InlineResponse200
 */


public class InlineResponse200 {
  private InlineResponse200Pix pix = null;

  private InlineResponse200QrCode qrCode = null;

  public InlineResponse200 pix(InlineResponse200Pix pix) {
    this.pix = pix;
    return this;
  }

   /**
   * Get pix
   * @return pix
  **/
  public InlineResponse200Pix getPix() {
    return pix;
  }

  public void setPix(InlineResponse200Pix pix) {
    this.pix = pix;
  }

  public InlineResponse200 qrCode(InlineResponse200QrCode qrCode) {
    this.qrCode = qrCode;
    return this;
  }

   /**
   * Get qrCode
   * @return qrCode
  **/
  public InlineResponse200QrCode getQrCode() {
    return qrCode;
  }

  public void setQrCode(InlineResponse200QrCode qrCode) {
    this.qrCode = qrCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.pix, inlineResponse200.pix) &&
        Objects.equals(this.qrCode, inlineResponse200.qrCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pix, qrCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    pix: ").append(toIndentedString(pix)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
