/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2001
 */

public class InlineResponse2001 {
	/**
	 * Indicador de continuidade para informar que a pesquisa possui mais registros
	 * a apresentar S-Sim, N-Não
	 */
	public enum IndicadorContinuidadeEnum {
		S("S"), N("N");

		private String value;

		IndicadorContinuidadeEnum(String value) {
			this.value = value;
		}

		public String getValue() {
			return value;
		}

	}

	private IndicadorContinuidadeEnum indicadorContinuidade = null;

	private Long numeroUltimoRegistro = null;

	private List<InlineResponse2001ListaRegistro> listaRegistro = null;

	public InlineResponse2001 indicadorContinuidade(IndicadorContinuidadeEnum indicadorContinuidade) {
		this.indicadorContinuidade = indicadorContinuidade;
		return this;
	}

	/**
	 * Indicador de continuidade para informar que a pesquisa possui mais registros
	 * a apresentar S-Sim, N-Não
	 * 
	 * @return indicadorContinuidade
	 **/
	public IndicadorContinuidadeEnum getIndicadorContinuidade() {
		return indicadorContinuidade;
	}

	public void setIndicadorContinuidade(IndicadorContinuidadeEnum indicadorContinuidade) {
		this.indicadorContinuidade = indicadorContinuidade;
	}

	public InlineResponse2001 numeroUltimoRegistro(Long numeroUltimoRegistro) {
		this.numeroUltimoRegistro = numeroUltimoRegistro;
		return this;
	}

	/**
	 * Numero do ultimo registro da consulta
	 * 
	 * @return numeroUltimoRegistro
	 **/
	public Long getNumeroUltimoRegistro() {
		return numeroUltimoRegistro;
	}

	public void setNumeroUltimoRegistro(Long numeroUltimoRegistro) {
		this.numeroUltimoRegistro = numeroUltimoRegistro;
	}

	public InlineResponse2001 listaRegistro(List<InlineResponse2001ListaRegistro> listaRegistro) {
		this.listaRegistro = listaRegistro;
		return this;
	}

	public InlineResponse2001 addListaRegistroItem(InlineResponse2001ListaRegistro listaRegistroItem) {
		if (this.listaRegistro == null) {
			this.listaRegistro = new ArrayList<InlineResponse2001ListaRegistro>();
		}
		this.listaRegistro.add(listaRegistroItem);
		return this;
	}

	/**
	 * Get listaRegistro
	 * 
	 * @return listaRegistro
	 **/
	public List<InlineResponse2001ListaRegistro> getListaRegistro() {
		return listaRegistro;
	}

	public void setListaRegistro(List<InlineResponse2001ListaRegistro> listaRegistro) {
		this.listaRegistro = listaRegistro;
	}

}
