/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * InlineResponse200Pix
 */

public class InlineResponse200Pix {
  private String chave = null;

  public InlineResponse200Pix chave(String chave) {
    this.chave = chave;
    return this;
  }

   /**
   * Código chave do pagador do Pix.
   * @return chave
  **/
  public String getChave() {
    return chave;
  }

  public void setChave(String chave) {
    this.chave = chave;
  }



}
