/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * InlineResponse200QrCode
 */

public class InlineResponse200QrCode {
  private String url = null;

  private String txId = null;

  private String emv = null;

  public InlineResponse200QrCode url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL do payload do QR Code Pix.
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public InlineResponse200QrCode txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * Código que identifica a transação Pix - transactionID.
   * @return txId
  **/
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }

  public InlineResponse200QrCode emv(String emv) {
    this.emv = emv;
    return this;
  }

   /**
   * BR Code no padrão EMV. Sequência de caracteres correspondente ao payload do QR Code Pix.
   * @return emv
  **/
  public String getEmv() {
    return emv;
  }

  public void setEmv(String emv) {
    this.emv = emv;
  }
}
