/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Inclusão de Juros de Mora em Boleto Bancário
 */
public class Juros {
  private Integer tipoJuros = null;

  private Double valorJuros = null;

  private Double taxaJuros = null;

  public Juros tipoJuros(Integer tipoJuros) {
    this.tipoJuros = tipoJuros;
    return this;
  }

   /**
   * Valor do Juros de Mora a ser aplicado sobre o valor do Boleto
   * @return tipoJuros
  **/
  public Integer getTipoJuros() {
    return tipoJuros;
  }

  public void setTipoJuros(Integer tipoJuros) {
    this.tipoJuros = tipoJuros;
  }

  public Juros valorJuros(Double valorJuros) {
    this.valorJuros = valorJuros;
    return this;
  }

   /**
   * Taxa do Juros de Mora a ser aplicado sobre o valor do Boleto
   * @return valorJuros
  **/
  public Double getValorJuros() {
    return valorJuros;
  }

  public void setValorJuros(Double valorJuros) {
    this.valorJuros = valorJuros;
  }

  public Juros taxaJuros(Double taxaJuros) {
    this.taxaJuros = taxaJuros;
    return this;
  }

   /**
   * Código para identificação do tipo de Juros de Mora que deverá ser aplicado ao Boleto. Valores a informar: 0 - Dispensar 1 - Valor por dia de atraso        2 - Taxa Mensal 3 - Isento
   * @return taxaJuros
  **/
  public Double getTaxaJuros() {
    return taxaJuros;
  }

  public void setTaxaJuros(Double taxaJuros) {
    this.taxaJuros = taxaJuros;
  }

}
