/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Inclusão de multa em Boleto Bancário
 */

public class Multa {
  private Integer tipoMulta = null;

  private Float valorMulta = null;

  private String dataInicioMulta = null;

  private Float taxaMulta = null;

  public Multa tipoMulta(Integer tipoMulta) {
    this.tipoMulta = tipoMulta;
    return this;
  }

   /**
   * Porcentagem sobre o valor do boleto a ser cobrada de multa
   * @return tipoMulta
  **/
  public Integer getTipoMulta() {
    return tipoMulta;
  }

  public void setTipoMulta(Integer tipoMulta) {
    this.tipoMulta = tipoMulta;
  }

  public Multa valorMulta(Float valorMulta) {
    this.valorMulta = valorMulta;
    return this;
  }

   /**
   * Data para início da cobrança da multa
   * @return valorMulta
  **/
  public Float getValorMulta() {
    return valorMulta;
  }

  public void setValorMulta(Float valorMulta) {
    this.valorMulta = valorMulta;
  }

  public Multa dataInicioMulta(String dataInicioMulta) {
    this.dataInicioMulta = dataInicioMulta;
    return this;
  }

   /**
   * Código para identificação do tipo de multa
   * @return dataInicioMulta
  **/
  public String getDataInicioMulta() {
    return dataInicioMulta;
  }

  public void setDataInicioMulta(String dataInicioMulta) {
    this.dataInicioMulta = dataInicioMulta;
  }

  public Multa taxaMulta(Float taxaMulta) {
    this.taxaMulta = taxaMulta;
    return this;
  }

   /**
   * Valor  sobre o valor do boleto a ser cobrado de multa
   * @return taxaMulta
  **/
  public Float getTaxaMulta() {
    return taxaMulta;
  }

  public void setTaxaMulta(Float taxaMulta) {
    this.taxaMulta = taxaMulta;
  }
}
