/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.Objects;
/**
 * Inclui condições de Negativação de Boleto Bancário
 */

public class Negativacao {
  private Integer quantidadeDiasNegativacao = null;

  private Integer tipoNegativacao = null;

  public Negativacao quantidadeDiasNegativacao(Integer quantidadeDiasNegativacao) {
    this.quantidadeDiasNegativacao = quantidadeDiasNegativacao;
    return this;
  }

   /**
   * Quantidade de dias, após o vencimento do Boleto, que o Boleto será Negativado
   * @return quantidadeDiasNegativacao
  **/
  public Integer getQuantidadeDiasNegativacao() {
    return quantidadeDiasNegativacao;
  }

  public void setQuantidadeDiasNegativacao(Integer quantidadeDiasNegativacao) {
    this.quantidadeDiasNegativacao = quantidadeDiasNegativacao;
  }

  public Negativacao tipoNegativacao(Integer tipoNegativacao) {
    this.tipoNegativacao = tipoNegativacao;
    return this;
  }

   /**
   * Código para identificação do tipo de Negativação que deverá ser aplicado ao Boleto. Valores a informar: 1 - Incluir Negativação 2 - Alterar Negativação        3 - Cancelar Negativação 4 - Excluir Negativação
   * @return tipoNegativacao
  **/
  public Integer getTipoNegativacao() {
    return tipoNegativacao;
  }

  public void setTipoNegativacao(Integer tipoNegativacao) {
    this.tipoNegativacao = tipoNegativacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Negativacao negativacao = (Negativacao) o;
    return Objects.equals(this.quantidadeDiasNegativacao, negativacao.quantidadeDiasNegativacao) &&
        Objects.equals(this.tipoNegativacao, negativacao.tipoNegativacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantidadeDiasNegativacao, tipoNegativacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Negativacao {\n");
    
    sb.append("    quantidadeDiasNegativacao: ").append(toIndentedString(quantidadeDiasNegativacao)).append("\n");
    sb.append("    tipoNegativacao: ").append(toIndentedString(tipoNegativacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
