/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Inclusão de Protesto em Boleto Bancário
 */

public class Protesto {
  private Float quantidadeDiasProtesto = null;

  public Protesto quantidadeDiasProtesto(Float quantidadeDiasProtesto) {
    this.quantidadeDiasProtesto = quantidadeDiasProtesto;
    return this;
  }

   /**
   * Quantos dias após a data de vencimento do boleto para iniciar o processo de cobrança através de protesto. (valor inteiro &gt;&#x3D; 0).
   * @return quantidadeDiasProtesto
  **/
  public Float getQuantidadeDiasProtesto() {
    return quantidadeDiasProtesto;
  }

  public void setQuantidadeDiasProtesto(Float quantidadeDiasProtesto) {
    this.quantidadeDiasProtesto = quantidadeDiasProtesto;
  }

}
