/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * RequisicaoRegistroBoletosSegundoDesconto
 */

public class RequisicaoRegistroBoletosSegundoDesconto {
  private String dataExpiracao = null;

  private Float porcentagem = null;

  private Float valor = null;

  public RequisicaoRegistroBoletosSegundoDesconto dataExpiracao(String dataExpiracao) {
    this.dataExpiracao = dataExpiracao;
    return this;
  }

   /**
   * Se tipo &gt; 0, Definir uma data de expiração do desconto, no formato \&quot;dd.mm.aaaa\&quot; .
   * @return dataExpiracao
  **/
  public String getDataExpiracao() {
    return dataExpiracao;
  }

  public void setDataExpiracao(String dataExpiracao) {
    this.dataExpiracao = dataExpiracao;
  }

  public RequisicaoRegistroBoletosSegundoDesconto porcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
    return this;
  }

   /**
   * Se tipo &#x3D; 2, definir uma porcentagem de desconto &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return porcentagem
  **/
  public Float getPorcentagem() {
    return porcentagem;
  }

  public void setPorcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
  }

  public RequisicaoRegistroBoletosSegundoDesconto valor(Float valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Se tipo &#x3D; 1, definir um valor de desconto &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return valor
  **/
  public Float getValor() {
    return valor;
  }

  public void setValor(Float valor) {
    this.valor = valor;
  }

}
