/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.Objects;
/**
 * RequisicaoRegistroBoletosTerceiroDesconto
 */

public class RequisicaoRegistroBoletosTerceiroDesconto {
  private String dataExpiracao = null;

  private Float porcentagem = null;

  private Float valor = null;

  public RequisicaoRegistroBoletosTerceiroDesconto dataExpiracao(String dataExpiracao) {
    this.dataExpiracao = dataExpiracao;
    return this;
  }

   /**
   * Se tipo &gt; 0, Definir uma data de expiração do desconto, no formato \&quot;dd.mm.aaaa\&quot;.
   * @return dataExpiracao
  **/
  public String getDataExpiracao() {
    return dataExpiracao;
  }

  public void setDataExpiracao(String dataExpiracao) {
    this.dataExpiracao = dataExpiracao;
  }

  public RequisicaoRegistroBoletosTerceiroDesconto porcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
    return this;
  }

   /**
   * Se tipo &#x3D; 2, definir uma porcentagem de desconto &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return porcentagem
  **/
  public Float getPorcentagem() {
    return porcentagem;
  }

  public void setPorcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
  }

  public RequisicaoRegistroBoletosTerceiroDesconto valor(Float valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Se tipo &#x3D; 1, definir um valor de desconto &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return valor
  **/
  public Float getValor() {
    return valor;
  }

  public void setValor(Float valor) {
    this.valor = valor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequisicaoRegistroBoletosTerceiroDesconto requisicaoRegistroBoletosTerceiroDesconto = (RequisicaoRegistroBoletosTerceiroDesconto) o;
    return Objects.equals(this.dataExpiracao, requisicaoRegistroBoletosTerceiroDesconto.dataExpiracao) &&
        Objects.equals(this.porcentagem, requisicaoRegistroBoletosTerceiroDesconto.porcentagem) &&
        Objects.equals(this.valor, requisicaoRegistroBoletosTerceiroDesconto.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataExpiracao, porcentagem, valor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequisicaoRegistroBoletosTerceiroDesconto {\n");
    
    sb.append("    dataExpiracao: ").append(toIndentedString(dataExpiracao)).append("\n");
    sb.append("    porcentagem: ").append(toIndentedString(porcentagem)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
