/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.Objects;
/**
 * RequisicaoRegistroBoletosBeneficiarioFinal
 */


public class RequisicaoRegistroBoletosBeneficiarioFinal {
  private Integer tipoInscricao = null;

  private Long numeroInscricao = null;

  private String nome = null;

  public RequisicaoRegistroBoletosBeneficiarioFinal tipoInscricao(Integer tipoInscricao) {
    this.tipoInscricao = tipoInscricao;
    return this;
  }

   /**
   * Código que identifica o tipo de inscrição do beneficiário final.  Domínios: 1 - CPF; 2 - CNPJ
   * @return tipoInscricao
  **/
  public Integer getTipoInscricao() {
    return tipoInscricao;
  }

  public void setTipoInscricao(Integer tipoInscricao) {
    this.tipoInscricao = tipoInscricao;
  }

  public RequisicaoRegistroBoletosBeneficiarioFinal numeroInscricao(Long numeroInscricao) {
    this.numeroInscricao = numeroInscricao;
    return this;
  }

   /**
   * Número de registro do beneficiário final.  Para o tipo &#x3D; 1, informar numero do CPF.  Para o tipo &#x3D; 2, informar numero do CNPJ.
   * @return numeroInscricao
  **/
  public Long getNumeroInscricao() {
    return numeroInscricao;
  }

  public void setNumeroInscricao(Long numeroInscricao) {
    this.numeroInscricao = numeroInscricao;
  }

  public RequisicaoRegistroBoletosBeneficiarioFinal nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome do beneficiário final
   * @return nome
  **/
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequisicaoRegistroBoletosBeneficiarioFinal requisicaoRegistroBoletosBeneficiarioFinal = (RequisicaoRegistroBoletosBeneficiarioFinal) o;
    return Objects.equals(this.tipoInscricao, requisicaoRegistroBoletosBeneficiarioFinal.tipoInscricao) &&
        Objects.equals(this.numeroInscricao, requisicaoRegistroBoletosBeneficiarioFinal.numeroInscricao) &&
        Objects.equals(this.nome, requisicaoRegistroBoletosBeneficiarioFinal.nome);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoInscricao, numeroInscricao, nome);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequisicaoRegistroBoletosBeneficiarioFinal {\n");
    
    sb.append("    tipoInscricao: ").append(toIndentedString(tipoInscricao)).append("\n");
    sb.append("    numeroInscricao: ").append(toIndentedString(numeroInscricao)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
