/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Objeto de requisição da baixa de boletos.
 */

public class RequisicaoBaixaBoleto {
  private Integer numeroConvenio = null;

  public RequisicaoBaixaBoleto numeroConvenio(Integer numeroConvenio) {
    this.numeroConvenio = numeroConvenio;
    return this;
  }

   /**
   * Identificador determinado pelo sistema de boleto bancário usado para emissão e liquidação do boleto e, portanto, usado para creditar o Beneficiário.
   * @return numeroConvenio
  **/
  public Integer getNumeroConvenio() {
    return numeroConvenio;
  }

  public void setNumeroConvenio(Integer numeroConvenio) {
    this.numeroConvenio = numeroConvenio;
  }	
}
