/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Código para identificação do tipo de multa para o Título de Cobrança, inteiro &gt;&#x3D; 0, sendo: 0 - Sem multa, 1 - Valor da Multa, 2 - Percentual da Multa.  Se informado ‘0’ (zero) os campos “DATA DE MULTA”, “PERCENTUAL DE MULTA” e “VALOR DA MULTA” não devem ser informados ou ser informados iguais a ‘0’ (zero).  O valor de juros e multa incidem sobre o valor atual do boleto (valor do boleto - valor de abatimento).
 */
	
public class RequisicaoRegistroBoletosMulta {
  private Integer tipo = null;

  private String data = null;

  private Float porcentagem = null;

  private Float valor = null;

  public RequisicaoRegistroBoletosMulta tipo(Integer tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Como a multa será concedida, inteiro &gt;&#x3D; 0.  Domínios:  0 - DISPENSAR;  1 - VALOR DIA ATRASO;  2 - TAXA MENSAL;  3 - ISENTO.
   * @return tipo
  **/
  public Integer getTipo() {
    return tipo;
  }

  public void setTipo(Integer tipo) {
    this.tipo = tipo;
  }

  public RequisicaoRegistroBoletosMulta data(String data) {
    this.data = data;
    return this;
  }

   /**
   * Se tipo &gt; 0, Definir uma data de multa, no formato \&quot;dd.mm.aaaa\&quot; 
   * @return data
  **/
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }

  public RequisicaoRegistroBoletosMulta porcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
    return this;
  }

   /**
   * Se tipo &#x3D; 2,  definir porcentagem &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return porcentagem
  **/
  public Float getPorcentagem() {
    return porcentagem;
  }

  public void setPorcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
  }

  public RequisicaoRegistroBoletosMulta valor(Float valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Se tipo &#x3D; 1, definir valor do juros &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return valor
  **/
  public Float getValor() {
    return valor;
  }

  public void setValor(Float valor) {
    this.valor = valor;
  }


}
