/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Define a ausência ou a forma como será concedido o desconto para o Título de Cobrança.
 */
public class RequisicaoRegistroBoletosDesconto {
  private Integer tipo = null;

  private String dataExpiracao = null;

  private Float porcentagem = null;

  private Float valor = null;

  public RequisicaoRegistroBoletosDesconto tipo(Integer tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Como o desconto será concedido, inteiro &gt;&#x3D; 0. Domínios:  0 - SEM DESCONTO; 1 - VLR FIXO ATE A DATA INFORMADA; 2 - PERCENTUAL ATE A DATA INFORMADA;  3 - DESCONTO POR DIA DE ANTECIPACAO.
   * @return tipo
  **/
  public Integer getTipo() {
    return tipo;
  }

  public void setTipo(Integer tipo) {
    this.tipo = tipo;
  }

  public RequisicaoRegistroBoletosDesconto dataExpiracao(String dataExpiracao) {
    this.dataExpiracao = dataExpiracao;
    return this;
  }

   /**
   * Se tipo &gt; 0, Definir uma data de expiração do desconto, no formato \&quot;dd.mm.aaaa\&quot;.
   * @return dataExpiracao
  **/
  public String getDataExpiracao() {
    return dataExpiracao;
  }

  public void setDataExpiracao(String dataExpiracao) {
    this.dataExpiracao = dataExpiracao;
  }

  public RequisicaoRegistroBoletosDesconto porcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
    return this;
  }

   /**
   * Se tipo &#x3D; 2, definir uma porcentagem de desconto &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return porcentagem
  **/
  public Float getPorcentagem() {
    return porcentagem;
  }

  public void setPorcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
  }

  public RequisicaoRegistroBoletosDesconto valor(Float valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Se tipo &#x3D; 1, definir um valor de desconto &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return valor
  **/
  public Float getValor() {
    return valor;
  }

  public void setValor(Float valor) {
    this.valor = valor;
  }

}
