/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * RequisicaoRegistroBoletosPagador
 */

public class RequisicaoRegistroBoletosPagador {
	private Integer tipoInscricao = null;
	private Long numeroInscricao = null;
	private String nome = null;
	private String endereco = null;
	private Integer cep = null;
	private String cidade = null;
	private String bairro = null;
	private String uf = null;
	private String telefone = null;

	public static final Integer TIPO_PESSSOA_FISICA = 1;
	public static final Integer TIPO_PESSSOA_JURIDICA = 2;

	public RequisicaoRegistroBoletosPagador tipoInscricao(Integer tipoInscricao) {
		this.tipoInscricao = tipoInscricao;
		return this;
	}

	public Integer getTipoInscricao() {
		return tipoInscricao;
	}

	public void setTipoInscricao(Integer tipoInscricao) {
		this.tipoInscricao = tipoInscricao;
	}

	public Long getNumeroInscricao() {
		return numeroInscricao;
	}

	public void setNumeroInscricao(Long numeroInscricao) {
		this.numeroInscricao = numeroInscricao;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public Integer getCep() {
		return cep;
	}

	public void setCep(Integer cep) {
		this.cep = cep;
	}

	public String getCidade() {
		return cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getUf() {
		return uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	/**
	 * Código que identifica o tipo de inscrição do Pagador. Domínios: 1 - CPF; 2 -
	 * CNPJ
	 * 
	 * @return tipoInscricao
	 **/
}
