/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Representação dos campos de requisição de uma solicitação de alteração dos dados de boletos bancários.
 */

public class RequisicaoAlterarBoleto {
  private Integer numeroConvenio = null;

  private String indicadorNovaDataVencimento = null;

  private AlteracaoData alteracaoData = null;

  private String indicadorAtribuirDesconto = null;

  private Desconto desconto = null;

  private String indicadorAlterarDesconto = null;

  private AlteracaoDesconto alteracaoDesconto = null;

  private String indicadorAlterarDataDesconto = null;

  private AlteracaoDataDesconto alteracaoDataDesconto = null;

  private String indicadorProtestar = null;

  private Protesto protesto = null;

  private String indicadorSustacaoProtesto = null;

  private String indicadorCancelarProtesto = null;

  private String indicadorIncluirAbatimento = null;

  private Abatimento abatimento = null;

  private String indicadorAlterarAbatimento = null;

  private AlteracaoAbatimento alteracaoAbatimento = null;

  private String indicadorCobrarJuros = null;

  private Juros juros = null;

  private String indicadorDispensarJuros = null;

  private String indicadorCobrarMulta = null;

  private Multa multa = null;

  private String indicadorDispensarMulta = null;

  private String indicadorNegativar = null;

  private Negativacao negativacao = null;

  private String indicadorAlterarSeuNumero = null;

  private AlteracaoSeuNumero alteracaoSeuNumero = null;

  private String indicadorAlterarEnderecoPagador = null;

  private AlteracaoEndereco alteracaoEndereco = null;

  private String indicadorAlterarPrazoBoletoVencido = null;

  private AlteracaoPrazo alteracaoPrazo = null;

  public RequisicaoAlterarBoleto numeroConvenio(Integer numeroConvenio) {
    this.numeroConvenio = numeroConvenio;
    return this;
  }

   /**
   * Identificador determinado pelo sistema de boleto bancário para fornecer a emissão e liquidação do boleto e, portanto, usado para creditar o Beneficiário.
   * @return numeroConvenio
  **/
  public Integer getNumeroConvenio() {
    return numeroConvenio;
  }

  public void setNumeroConvenio(Integer numeroConvenio) {
    this.numeroConvenio = numeroConvenio;
  }

  public RequisicaoAlterarBoleto indicadorNovaDataVencimento(String indicadorNovaDataVencimento) {
    this.indicadorNovaDataVencimento = indicadorNovaDataVencimento;
    return this;
  }

   /**
   * Indica a intenção de atribuir nova data de vencimento ao boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorNovaDataVencimento
  **/
  public String getIndicadorNovaDataVencimento() {
    return indicadorNovaDataVencimento;
  }

  public void setIndicadorNovaDataVencimento(String indicadorNovaDataVencimento) {
    this.indicadorNovaDataVencimento = indicadorNovaDataVencimento;
  }

  public RequisicaoAlterarBoleto alteracaoData(AlteracaoData alteracaoData) {
    this.alteracaoData = alteracaoData;
    return this;
  }

   /**
   * Get alteracaoData
   * @return alteracaoData
  **/
  public AlteracaoData getAlteracaoData() {
    return alteracaoData;
  }

  public void setAlteracaoData(AlteracaoData alteracaoData) {
    this.alteracaoData = alteracaoData;
  }

  public RequisicaoAlterarBoleto indicadorAtribuirDesconto(String indicadorAtribuirDesconto) {
    this.indicadorAtribuirDesconto = indicadorAtribuirDesconto;
    return this;
  }

   /**
   * Indica a intenção de atribuir desconto ao boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorAtribuirDesconto
  **/
  public String getIndicadorAtribuirDesconto() {
    return indicadorAtribuirDesconto;
  }

  public void setIndicadorAtribuirDesconto(String indicadorAtribuirDesconto) {
    this.indicadorAtribuirDesconto = indicadorAtribuirDesconto;
  }

  public RequisicaoAlterarBoleto desconto(Desconto desconto) {
    this.desconto = desconto;
    return this;
  }

   /**
   * Get desconto
   * @return desconto
  **/
  public Desconto getDesconto() {
    return desconto;
  }

  public void setDesconto(Desconto desconto) {
    this.desconto = desconto;
  }

  public RequisicaoAlterarBoleto indicadorAlterarDesconto(String indicadorAlterarDesconto) {
    this.indicadorAlterarDesconto = indicadorAlterarDesconto;
    return this;
  }

   /**
   * Indica a intenção de alterar desconto do boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorAlterarDesconto
  **/
  public String getIndicadorAlterarDesconto() {
    return indicadorAlterarDesconto;
  }

  public void setIndicadorAlterarDesconto(String indicadorAlterarDesconto) {
    this.indicadorAlterarDesconto = indicadorAlterarDesconto;
  }

  public RequisicaoAlterarBoleto alteracaoDesconto(AlteracaoDesconto alteracaoDesconto) {
    this.alteracaoDesconto = alteracaoDesconto;
    return this;
  }

   /**
   * Get alteracaoDesconto
   * @return alteracaoDesconto
  **/
  public AlteracaoDesconto getAlteracaoDesconto() {
    return alteracaoDesconto;
  }

  public void setAlteracaoDesconto(AlteracaoDesconto alteracaoDesconto) {
    this.alteracaoDesconto = alteracaoDesconto;
  }

  public RequisicaoAlterarBoleto indicadorAlterarDataDesconto(String indicadorAlterarDataDesconto) {
    this.indicadorAlterarDataDesconto = indicadorAlterarDataDesconto;
    return this;
  }

   /**
   * Indica a intenção de alterar a data do desconto do boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorAlterarDataDesconto
  **/
  public String getIndicadorAlterarDataDesconto() {
    return indicadorAlterarDataDesconto;
  }

  public void setIndicadorAlterarDataDesconto(String indicadorAlterarDataDesconto) {
    this.indicadorAlterarDataDesconto = indicadorAlterarDataDesconto;
  }

  public RequisicaoAlterarBoleto alteracaoDataDesconto(AlteracaoDataDesconto alteracaoDataDesconto) {
    this.alteracaoDataDesconto = alteracaoDataDesconto;
    return this;
  }

   /**
   * Get alteracaoDataDesconto
   * @return alteracaoDataDesconto
  **/
  public AlteracaoDataDesconto getAlteracaoDataDesconto() {
    return alteracaoDataDesconto;
  }

  public void setAlteracaoDataDesconto(AlteracaoDataDesconto alteracaoDataDesconto) {
    this.alteracaoDataDesconto = alteracaoDataDesconto;
  }

  public RequisicaoAlterarBoleto indicadorProtestar(String indicadorProtestar) {
    this.indicadorProtestar = indicadorProtestar;
    return this;
  }

   /**
   * Indica a intenção de protestar o boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorProtestar
  **/
  public String getIndicadorProtestar() {
    return indicadorProtestar;
  }

  public void setIndicadorProtestar(String indicadorProtestar) {
    this.indicadorProtestar = indicadorProtestar;
  }

  public RequisicaoAlterarBoleto protesto(Protesto protesto) {
    this.protesto = protesto;
    return this;
  }

   /**
   * Get protesto
   * @return protesto
  **/
  public Protesto getProtesto() {
    return protesto;
  }

  public void setProtesto(Protesto protesto) {
    this.protesto = protesto;
  }

  public RequisicaoAlterarBoleto indicadorSustacaoProtesto(String indicadorSustacaoProtesto) {
    this.indicadorSustacaoProtesto = indicadorSustacaoProtesto;
    return this;
  }

   /**
   * Indica a intenção de sustar/cancelar um comando de protesto do boleto que já tenha sido processado pelo Banco. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar.
   * @return indicadorSustacaoProtesto
  **/
  public String getIndicadorSustacaoProtesto() {
    return indicadorSustacaoProtesto;
  }

  public void setIndicadorSustacaoProtesto(String indicadorSustacaoProtesto) {
    this.indicadorSustacaoProtesto = indicadorSustacaoProtesto;
  }

  public RequisicaoAlterarBoleto indicadorCancelarProtesto(String indicadorCancelarProtesto) {
    this.indicadorCancelarProtesto = indicadorCancelarProtesto;
    return this;
  }

   /**
   * Deve ser utilizada para cancelar uma instrução de protesto enviada ao Banco na mesma data ou que ainda não tenha sido processada pelo Banco. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorCancelarProtesto
  **/
  public String getIndicadorCancelarProtesto() {
    return indicadorCancelarProtesto;
  }

  public void setIndicadorCancelarProtesto(String indicadorCancelarProtesto) {
    this.indicadorCancelarProtesto = indicadorCancelarProtesto;
  }

  public RequisicaoAlterarBoleto indicadorIncluirAbatimento(String indicadorIncluirAbatimento) {
    this.indicadorIncluirAbatimento = indicadorIncluirAbatimento;
    return this;
  }

   /**
   * Indica a intenção de incluir abatimento no boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorIncluirAbatimento
  **/
  public String getIndicadorIncluirAbatimento() {
    return indicadorIncluirAbatimento;
  }

  public void setIndicadorIncluirAbatimento(String indicadorIncluirAbatimento) {
    this.indicadorIncluirAbatimento = indicadorIncluirAbatimento;
  }

  public RequisicaoAlterarBoleto abatimento(Abatimento abatimento) {
    this.abatimento = abatimento;
    return this;
  }

   /**
   * Get abatimento
   * @return abatimento
  **/
  public Abatimento getAbatimento() {
    return abatimento;
  }

  public void setAbatimento(Abatimento abatimento) {
    this.abatimento = abatimento;
  }

  public RequisicaoAlterarBoleto indicadorAlterarAbatimento(String indicadorAlterarAbatimento) {
    this.indicadorAlterarAbatimento = indicadorAlterarAbatimento;
    return this;
  }

   /**
   * Indica a intenção de alterar o valor do abatimento no boleto. Domínio: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorAlterarAbatimento
  **/
  public String getIndicadorAlterarAbatimento() {
    return indicadorAlterarAbatimento;
  }

  public void setIndicadorAlterarAbatimento(String indicadorAlterarAbatimento) {
    this.indicadorAlterarAbatimento = indicadorAlterarAbatimento;
  }

  public RequisicaoAlterarBoleto alteracaoAbatimento(AlteracaoAbatimento alteracaoAbatimento) {
    this.alteracaoAbatimento = alteracaoAbatimento;
    return this;
  }

   /**
   * Get alteracaoAbatimento
   * @return alteracaoAbatimento
  **/
  public AlteracaoAbatimento getAlteracaoAbatimento() {
    return alteracaoAbatimento;
  }

  public void setAlteracaoAbatimento(AlteracaoAbatimento alteracaoAbatimento) {
    this.alteracaoAbatimento = alteracaoAbatimento;
  }

  public RequisicaoAlterarBoleto indicadorCobrarJuros(String indicadorCobrarJuros) {
    this.indicadorCobrarJuros = indicadorCobrarJuros;
    return this;
  }

   /**
   * Indica a intenção de cobrar juros no boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorCobrarJuros
  **/
  public String getIndicadorCobrarJuros() {
    return indicadorCobrarJuros;
  }

  public void setIndicadorCobrarJuros(String indicadorCobrarJuros) {
    this.indicadorCobrarJuros = indicadorCobrarJuros;
  }

  public RequisicaoAlterarBoleto juros(Juros juros) {
    this.juros = juros;
    return this;
  }

   /**
   * Get juros
   * @return juros
  **/
  public Juros getJuros() {
    return juros;
  }

  public void setJuros(Juros juros) {
    this.juros = juros;
  }

  public RequisicaoAlterarBoleto indicadorDispensarJuros(String indicadorDispensarJuros) {
    this.indicadorDispensarJuros = indicadorDispensarJuros;
    return this;
  }

   /**
   * Indica a intenção de dispensar juros no boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorDispensarJuros
  **/
  public String getIndicadorDispensarJuros() {
    return indicadorDispensarJuros;
  }

  public void setIndicadorDispensarJuros(String indicadorDispensarJuros) {
    this.indicadorDispensarJuros = indicadorDispensarJuros;
  }

  public RequisicaoAlterarBoleto indicadorCobrarMulta(String indicadorCobrarMulta) {
    this.indicadorCobrarMulta = indicadorCobrarMulta;
    return this;
  }

   /**
   * Indica a intenção de cobrar multa no boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorCobrarMulta
  **/
  public String getIndicadorCobrarMulta() {
    return indicadorCobrarMulta;
  }

  public void setIndicadorCobrarMulta(String indicadorCobrarMulta) {
    this.indicadorCobrarMulta = indicadorCobrarMulta;
  }

  public RequisicaoAlterarBoleto multa(Multa multa) {
    this.multa = multa;
    return this;
  }

   /**
   * Get multa
   * @return multa
  **/
  public Multa getMulta() {
    return multa;
  }

  public void setMulta(Multa multa) {
    this.multa = multa;
  }

  public RequisicaoAlterarBoleto indicadorDispensarMulta(String indicadorDispensarMulta) {
    this.indicadorDispensarMulta = indicadorDispensarMulta;
    return this;
  }

   /**
   * Indica a intenção de dispensar cobrança de multa no boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorDispensarMulta
  **/
  public String getIndicadorDispensarMulta() {
    return indicadorDispensarMulta;
  }

  public void setIndicadorDispensarMulta(String indicadorDispensarMulta) {
    this.indicadorDispensarMulta = indicadorDispensarMulta;
  }

  public RequisicaoAlterarBoleto indicadorNegativar(String indicadorNegativar) {
    this.indicadorNegativar = indicadorNegativar;
    return this;
  }

   /**
   * Indica a intenção de negativar ou cancelar negativação boleto. (Inclusão ou Cancelamento) Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorNegativar
  **/
  public String getIndicadorNegativar() {
    return indicadorNegativar;
  }

  public void setIndicadorNegativar(String indicadorNegativar) {
    this.indicadorNegativar = indicadorNegativar;
  }

  public RequisicaoAlterarBoleto negativacao(Negativacao negativacao) {
    this.negativacao = negativacao;
    return this;
  }

   /**
   * Get negativacao
   * @return negativacao
  **/
  public Negativacao getNegativacao() {
    return negativacao;
  }

  public void setNegativacao(Negativacao negativacao) {
    this.negativacao = negativacao;
  }

  public RequisicaoAlterarBoleto indicadorAlterarSeuNumero(String indicadorAlterarSeuNumero) {
    this.indicadorAlterarSeuNumero = indicadorAlterarSeuNumero;
    return this;
  }

   /**
   * Indica a intenção de alterar Seu Numero no boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorAlterarSeuNumero
  **/
  public String getIndicadorAlterarSeuNumero() {
    return indicadorAlterarSeuNumero;
  }

  public void setIndicadorAlterarSeuNumero(String indicadorAlterarSeuNumero) {
    this.indicadorAlterarSeuNumero = indicadorAlterarSeuNumero;
  }

  public RequisicaoAlterarBoleto alteracaoSeuNumero(AlteracaoSeuNumero alteracaoSeuNumero) {
    this.alteracaoSeuNumero = alteracaoSeuNumero;
    return this;
  }

   /**
   * Get alteracaoSeuNumero
   * @return alteracaoSeuNumero
  **/
  public AlteracaoSeuNumero getAlteracaoSeuNumero() {
    return alteracaoSeuNumero;
  }

  public void setAlteracaoSeuNumero(AlteracaoSeuNumero alteracaoSeuNumero) {
    this.alteracaoSeuNumero = alteracaoSeuNumero;
  }

  public RequisicaoAlterarBoleto indicadorAlterarEnderecoPagador(String indicadorAlterarEnderecoPagador) {
    this.indicadorAlterarEnderecoPagador = indicadorAlterarEnderecoPagador;
    return this;
  }

   /**
   * Indica a intenção de alterar endereço do Pagador no boleto. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorAlterarEnderecoPagador
  **/
  public String getIndicadorAlterarEnderecoPagador() {
    return indicadorAlterarEnderecoPagador;
  }

  public void setIndicadorAlterarEnderecoPagador(String indicadorAlterarEnderecoPagador) {
    this.indicadorAlterarEnderecoPagador = indicadorAlterarEnderecoPagador;
  }

  public RequisicaoAlterarBoleto alteracaoEndereco(AlteracaoEndereco alteracaoEndereco) {
    this.alteracaoEndereco = alteracaoEndereco;
    return this;
  }

   /**
   * Get alteracaoEndereco
   * @return alteracaoEndereco
  **/
  public AlteracaoEndereco getAlteracaoEndereco() {
    return alteracaoEndereco;
  }

  public void setAlteracaoEndereco(AlteracaoEndereco alteracaoEndereco) {
    this.alteracaoEndereco = alteracaoEndereco;
  }

  public RequisicaoAlterarBoleto indicadorAlterarPrazoBoletoVencido(String indicadorAlterarPrazoBoletoVencido) {
    this.indicadorAlterarPrazoBoletoVencido = indicadorAlterarPrazoBoletoVencido;
    return this;
  }

   /**
   * Indica a intenção de prazo de aceite de boleto vencido. Valores a informar: \&quot;S\&quot; -&gt; Sim, desejo alterar \&quot;N\&quot; -&gt; Não, não desejo alterar
   * @return indicadorAlterarPrazoBoletoVencido
  **/
  public String getIndicadorAlterarPrazoBoletoVencido() {
    return indicadorAlterarPrazoBoletoVencido;
  }

  public void setIndicadorAlterarPrazoBoletoVencido(String indicadorAlterarPrazoBoletoVencido) {
    this.indicadorAlterarPrazoBoletoVencido = indicadorAlterarPrazoBoletoVencido;
  }

  public RequisicaoAlterarBoleto alteracaoPrazo(AlteracaoPrazo alteracaoPrazo) {
    this.alteracaoPrazo = alteracaoPrazo;
    return this;
  }

   /**
   * Get alteracaoPrazo
   * @return alteracaoPrazo
  **/
  public AlteracaoPrazo getAlteracaoPrazo() {
    return alteracaoPrazo;
  }

  public void setAlteracaoPrazo(AlteracaoPrazo alteracaoPrazo) {
    this.alteracaoPrazo = alteracaoPrazo;
  }
}
