/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Representação dos campos de requisição de uma solicitação de criação de boletos bancários.
 */

public class RequisicaoRegistroBoletos {
  private Long numeroConvenio = null;

  private Integer numeroCarteira = null;

  private Integer numeroVariacaoCarteira = null;

  private Integer codigoModalidade = null;

  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd.MM.yyyy")
  private String dataEmissao = null;
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd.MM.yyyy")
  private String dataVencimento = null;

  private Float valorOriginal = null;

  private Float valorAbatimento = null;

  private Float quantidadeDiasProtesto = null;

  private Integer quantidadeDiasNegativacao = null;

  private Integer orgaoNegativador = null;

  private String indicadorAceiteTituloVencido = null;

  private Integer numeroDiasLimiteRecebimento = null;

  private String codigoAceite = null;

  private Integer codigoTipoTitulo = null;

  private String descricaoTipoTitulo = null;

  private String indicadorPermissaoRecebimentoParcial = null;

  private String numeroTituloBeneficiario = null;

  private String campoUtilizacaoBeneficiario = null;

  private String numeroTituloCliente = null;

  private String mensagemBloquetoOcorrencia = null;

  private RequisicaoRegistroBoletosDesconto desconto = null;

  private RequisicaoRegistroBoletosSegundoDesconto segundoDesconto = null;

  private RequisicaoRegistroBoletosTerceiroDesconto terceiroDesconto = null;

  private RequisicaoRegistroBoletosJurosMora jurosMora = null;

  private RequisicaoRegistroBoletosMulta multa = null;

  private RequisicaoRegistroBoletosPagador pagador = null;

  private RequisicaoRegistroBoletosBeneficiarioFinal beneficiarioFinal = null;

  private String indicadorPix = null;

  public RequisicaoRegistroBoletos numeroConvenio(Long numeroConvenio) {
    this.numeroConvenio = numeroConvenio;
    return this;
  }

   /**
   * Número do convênio de Cobrança do Cliente. Identificador determinado pelo sistema Cobrança para controlar a emissão de boletos, liquidação, crédito de valores ao Beneficiário e intercâmbio de dados com o cliente.
   * @return numeroConvenio
  **/
  public Long getNumeroConvenio() {
    return numeroConvenio;
  }

  public void setNumeroConvenio(Long numeroConvenio) {
    this.numeroConvenio = numeroConvenio;
  }

  public RequisicaoRegistroBoletos numeroCarteira(Integer numeroCarteira) {
    this.numeroCarteira = numeroCarteira;
    return this;
  }

   /**
   * Características do serviço de boleto bancário e como ele deve ser tratado pelo banco.
   * @return numeroCarteira
  **/
  public Integer getNumeroCarteira() {
    return numeroCarteira;
  }

  public void setNumeroCarteira(Integer numeroCarteira) {
    this.numeroCarteira = numeroCarteira;
  }

  public RequisicaoRegistroBoletos numeroVariacaoCarteira(Integer numeroVariacaoCarteira) {
    this.numeroVariacaoCarteira = numeroVariacaoCarteira;
    return this;
  }

   /**
   * Número da variação da carteira do convênio de cobrança.
   * @return numeroVariacaoCarteira
  **/
  public Integer getNumeroVariacaoCarteira() {
    return numeroVariacaoCarteira;
  }

  public void setNumeroVariacaoCarteira(Integer numeroVariacaoCarteira) {
    this.numeroVariacaoCarteira = numeroVariacaoCarteira;
  }

  public RequisicaoRegistroBoletos codigoModalidade(Integer codigoModalidade) {
    this.codigoModalidade = codigoModalidade;
    return this;
  }

   /**
   * Identifica  a característica dos boletos dentro das modalidades de cobrança existentes no banco.    Domínio: 01 - SIMPLES; 04 - VINCULADA
   * @return codigoModalidade
  **/
  public Integer getCodigoModalidade() {
    return codigoModalidade;
  }

  public void setCodigoModalidade(Integer codigoModalidade) {
    this.codigoModalidade = codigoModalidade;
  }

  public RequisicaoRegistroBoletos dataEmissao(String dataEmissao) {
    this.dataEmissao = dataEmissao;
    return this;
  }

   /**
   * Data de emissão do boleto (formato \&quot;dd.mm.aaaaa\&quot;). 
   * @return dataEmissao
  **/
  public String getDataEmissao() {
    return dataEmissao;
  }

  public void setDataEmissao(String dataEmissao) {
    this.dataEmissao = dataEmissao;
  }

  public RequisicaoRegistroBoletos dataVencimento(String dataVencimento) {
    this.dataVencimento = dataVencimento;
    return this;
  }

   /**
   * Data de vencimento do boleto (formato \&quot;dd.mm.aaaaa\&quot;).
   * @return dataVencimento
  **/
  public String getDataVencimento() {
    return dataVencimento;
  }

  public void setDataVencimento(String dataVencimento) {
    this.dataVencimento = dataVencimento;
  }

  public RequisicaoRegistroBoletos valorOriginal(Float valorOriginal) {
    this.valorOriginal = valorOriginal;
    return this;
  }

   /**
   * Valor de cobrança &gt; 0.00, emitido em Real (formato decimal separado por \&quot;.\&quot;). Valor do boleto no registro. Deve ser maior que a soma dos campos “VALOR DO DESCONTO DO TÍTULO” e “VALOR DO ABATIMENTO DO TÍTULO”, se informados. Informação não passível de alteração após a criação. No caso de emissão com valor equivocado, sugerimos cancelar e emitir novo boleto.
   * @return valorOriginal
  **/
  public Float getValorOriginal() {
    return valorOriginal;
  }

  public void setValorOriginal(Float valorOriginal) {
    this.valorOriginal = valorOriginal;
  }

  public RequisicaoRegistroBoletos valorAbatimento(Float valorAbatimento) {
    this.valorAbatimento = valorAbatimento;
    return this;
  }

   /**
   * Valor de dedução do boleto &gt;&#x3D; 0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return valorAbatimento
  **/
  public Float getValorAbatimento() {
    return valorAbatimento;
  }

  public void setValorAbatimento(Float valorAbatimento) {
    this.valorAbatimento = valorAbatimento;
  }

  public RequisicaoRegistroBoletos quantidadeDiasProtesto(Float quantidadeDiasProtesto) {
    this.quantidadeDiasProtesto = quantidadeDiasProtesto;
    return this;
  }

   /**
   * Quantos dias após a data de vencimento do boleto para iniciar o processo de cobrança através de protesto. (valor inteiro &gt;&#x3D; 0).
   * @return quantidadeDiasProtesto
  **/
  public Float getQuantidadeDiasProtesto() {
    return quantidadeDiasProtesto;
  }

  public void setQuantidadeDiasProtesto(Float quantidadeDiasProtesto) {
    this.quantidadeDiasProtesto = quantidadeDiasProtesto;
  }

  public RequisicaoRegistroBoletos quantidadeDiasNegativacao(Integer quantidadeDiasNegativacao) {
    this.quantidadeDiasNegativacao = quantidadeDiasNegativacao;
    return this;
  }

   /**
   * Quantos dias após a data de vencimento do boleto para iniciar o processo de negativação através da opção escolhida no campo orgaoNegativador. (valor inteiro &gt;&#x3D; 0).
   * @return quantidadeDiasNegativacao
  **/
  public Integer getQuantidadeDiasNegativacao() {
    return quantidadeDiasNegativacao;
  }

  public void setQuantidadeDiasNegativacao(Integer quantidadeDiasNegativacao) {
    this.quantidadeDiasNegativacao = quantidadeDiasNegativacao;
  }

  public RequisicaoRegistroBoletos orgaoNegativador(Integer orgaoNegativador) {
    this.orgaoNegativador = orgaoNegativador;
    return this;
  }

   /**
   * Código do Órgão Negativador.  Domínio: 10 - SERASA
   * @return orgaoNegativador
  **/
  public Integer getOrgaoNegativador() {
    return orgaoNegativador;
  }

  public void setOrgaoNegativador(Integer orgaoNegativador) {
    this.orgaoNegativador = orgaoNegativador;
  }

  public RequisicaoRegistroBoletos indicadorAceiteTituloVencido(String indicadorAceiteTituloVencido) {
    this.indicadorAceiteTituloVencido = indicadorAceiteTituloVencido;
    return this;
  }

   /**
   * Indicador de que o boleto pode ou não ser recebido após o vencimento. Campo não obrigatório  Se não informado, será assumido a informação de limite de recebimento que está definida no convênio.  Quando informado \&quot;S\&quot; em conjunto com o campo \&quot;numeroDiasLimiteRecebimento\&quot;, será definido a quantidade de dias (corridos) que este boleto ficará disponível para pagamento após seu vencimento.  Obs.: Se definido \&quot;S\&quot; e o campo \&quot;numeroDiasLimiteRecebimento\&quot; ficar com valor zero também será assumido a informação de limite de recebimento que está definida no convênio.  Quando informado \&quot;N\&quot;, fica definindo que o boleto NÃO permite pagamento em atraso, portanto só aceitará pagamento até a data do vencimento ou o próximo dia útil, quando o vencimento ocorrer em dia não útil.  Quando informado qualquer valor diferente de \&quot;S\&quot; ou \&quot;N\&quot; será assumido a informação de limite de recebimento que está definida no convênio.
   * @return indicadorAceiteTituloVencido
  **/
  public String getIndicadorAceiteTituloVencido() {
    return indicadorAceiteTituloVencido;
  }

  public void setIndicadorAceiteTituloVencido(String indicadorAceiteTituloVencido) {
    this.indicadorAceiteTituloVencido = indicadorAceiteTituloVencido;
  }

  public RequisicaoRegistroBoletos numeroDiasLimiteRecebimento(Integer numeroDiasLimiteRecebimento) {
    this.numeroDiasLimiteRecebimento = numeroDiasLimiteRecebimento;
    return this;
  }

   /**
   * Número de dias limite para recebimento. Informar valor inteiro &gt; 0.
   * @return numeroDiasLimiteRecebimento
  **/
  public Integer getNumeroDiasLimiteRecebimento() {
    return numeroDiasLimiteRecebimento;
  }

  public void setNumeroDiasLimiteRecebimento(Integer numeroDiasLimiteRecebimento) {
    this.numeroDiasLimiteRecebimento = numeroDiasLimiteRecebimento;
  }

  public RequisicaoRegistroBoletos codigoAceite(String codigoAceite) {
    this.codigoAceite = codigoAceite;
    return this;
  }

   /**
   * Código para  identificar se o boleto de cobrança foi aceito (reconhecimento da dívida pelo Pagador).  Domínios: A - ACEITE N - NAO ACEITE
   * @return codigoAceite
  **/
  public String getCodigoAceite() {
    return codigoAceite;
  }

  public void setCodigoAceite(String codigoAceite) {
    this.codigoAceite = codigoAceite;
  }

  public RequisicaoRegistroBoletos codigoTipoTitulo(Integer codigoTipoTitulo) {
    this.codigoTipoTitulo = codigoTipoTitulo;
    return this;
  }

   /**
   * Código para identificar o tipo de boleto de cobrança.  Domínios: 1- CHEQUE 2- DUPLICATA MERCANTIL 3- DUPLICATA MTIL POR INDICACAO 4- DUPLICATA DE SERVICO 5- DUPLICATA DE SRVC P/INDICACAO 6- DUPLICATA RURAL 7- LETRA DE CAMBIO 8- NOTA DE CREDITO COMERCIAL 9- NOTA DE CREDITO A EXPORTACAO 10- NOTA DE CREDITO INDULTRIAL 11- NOTA DE CREDITO RURAL 12- NOTA PROMISSORIA 13- NOTA PROMISSORIA RURAL 14- TRIPLICATA MERCANTIL 15- TRIPLICATA DE SERVICO 16- NOTA DE SEGURO 17- RECIBO 18- FATURA 19- NOTA DE DEBITO 20- APOLICE DE SEGURO 21- MENSALIDADE ESCOLAR 22- PARCELA DE CONSORCIO 23- DIVIDA ATIVA DA UNIAO 24- DIVIDA ATIVA DE ESTADO 25- DIVIDA ATIVA DE MUNICIPIO 31- CARTAO DE CREDITO 32- BOLETO PROPOSTA 33- BOLETO APORTE 99- OUTROS.
   * @return codigoTipoTitulo
  **/
  public Integer getCodigoTipoTitulo() {
    return codigoTipoTitulo;
  }

  public void setCodigoTipoTitulo(Integer codigoTipoTitulo) {
    this.codigoTipoTitulo = codigoTipoTitulo;
  }

  public RequisicaoRegistroBoletos descricaoTipoTitulo(String descricaoTipoTitulo) {
    this.descricaoTipoTitulo = descricaoTipoTitulo;
    return this;
  }

   /**
   * Descrição do tipo de boleto.
   * @return descricaoTipoTitulo
  **/
  public String getDescricaoTipoTitulo() {
    return descricaoTipoTitulo;
  }

  public void setDescricaoTipoTitulo(String descricaoTipoTitulo) {
    this.descricaoTipoTitulo = descricaoTipoTitulo;
  }

  public RequisicaoRegistroBoletos indicadorPermissaoRecebimentoParcial(String indicadorPermissaoRecebimentoParcial) {
    this.indicadorPermissaoRecebimentoParcial = indicadorPermissaoRecebimentoParcial;
    return this;
  }

   /**
   * Código para identificação da autorização de pagamento parcial do boleto.  Domínios: S - SIM N - NÃO 
   * @return indicadorPermissaoRecebimentoParcial
  **/
  public String getIndicadorPermissaoRecebimentoParcial() {
    return indicadorPermissaoRecebimentoParcial;
  }

  public void setIndicadorPermissaoRecebimentoParcial(String indicadorPermissaoRecebimentoParcial) {
    this.indicadorPermissaoRecebimentoParcial = indicadorPermissaoRecebimentoParcial;
  }

  public RequisicaoRegistroBoletos numeroTituloBeneficiario(String numeroTituloBeneficiario) {
    this.numeroTituloBeneficiario = numeroTituloBeneficiario;
    return this;
  }

   /**
   * Número de identificação do boleto (correspondente ao SEU NÚMERO), no formato STRING (Limitado a 15 caracteres - Letras Maiúsculas).
   * @return numeroTituloBeneficiario
  **/
  public String getNumeroTituloBeneficiario() {
    return numeroTituloBeneficiario;
  }

  public void setNumeroTituloBeneficiario(String numeroTituloBeneficiario) {
    this.numeroTituloBeneficiario = numeroTituloBeneficiario;
  }

  public RequisicaoRegistroBoletos campoUtilizacaoBeneficiario(String campoUtilizacaoBeneficiario) {
    this.campoUtilizacaoBeneficiario = campoUtilizacaoBeneficiario;
    return this;
  }

   /**
   * Informações adicionais sobre o beneficiário.
   * @return campoUtilizacaoBeneficiario
  **/
  public String getCampoUtilizacaoBeneficiario() {
    return campoUtilizacaoBeneficiario;
  }

  public void setCampoUtilizacaoBeneficiario(String campoUtilizacaoBeneficiario) {
    this.campoUtilizacaoBeneficiario = campoUtilizacaoBeneficiario;
  }

  public RequisicaoRegistroBoletos numeroTituloCliente(String numeroTituloCliente) {
    this.numeroTituloCliente = numeroTituloCliente;
    return this;
  }

   /**
   * Número de identificação do boleto (correspondente ao NOSSO NÚMERO), no formato STRING, com 20 dígitos, que deverá ser formatado da seguinte forma:  “000” +  (número do convênio com 7 dígitos) + (10 algarismos - se necessário, completar com zeros à esquerda).
   * @return numeroTituloCliente
  **/
  public String getNumeroTituloCliente() {
    return numeroTituloCliente;
  }

  public void setNumeroTituloCliente(String numeroTituloCliente) {
    this.numeroTituloCliente = numeroTituloCliente;
  }

  public RequisicaoRegistroBoletos mensagemBloquetoOcorrencia(String mensagemBloquetoOcorrencia) {
    this.mensagemBloquetoOcorrencia = mensagemBloquetoOcorrencia;
    return this;
  }

   /**
   * Mensagem definida pelo beneficiário para ser impressa no boleto. (Limitado a 30 caracteres)
   * @return mensagemBloquetoOcorrencia
  **/
  public String getMensagemBloquetoOcorrencia() {
    return mensagemBloquetoOcorrencia;
  }

  public void setMensagemBloquetoOcorrencia(String mensagemBloquetoOcorrencia) {
    this.mensagemBloquetoOcorrencia = mensagemBloquetoOcorrencia;
  }

  public RequisicaoRegistroBoletos desconto(RequisicaoRegistroBoletosDesconto desconto) {
    this.desconto = desconto;
    return this;
  }

   /**
   * Get desconto
   * @return desconto
  **/
  public RequisicaoRegistroBoletosDesconto getDesconto() {
    return desconto;
  }

  public void setDesconto(RequisicaoRegistroBoletosDesconto desconto) {
    this.desconto = desconto;
  }

  public RequisicaoRegistroBoletos segundoDesconto(RequisicaoRegistroBoletosSegundoDesconto segundoDesconto) {
    this.segundoDesconto = segundoDesconto;
    return this;
  }

   /**
   * Get segundoDesconto
   * @return segundoDesconto
  **/
  public RequisicaoRegistroBoletosSegundoDesconto getSegundoDesconto() {
    return segundoDesconto;
  }

  public void setSegundoDesconto(RequisicaoRegistroBoletosSegundoDesconto segundoDesconto) {
    this.segundoDesconto = segundoDesconto;
  }

  public RequisicaoRegistroBoletos terceiroDesconto(RequisicaoRegistroBoletosTerceiroDesconto terceiroDesconto) {
    this.terceiroDesconto = terceiroDesconto;
    return this;
  }

   /**
   * Get terceiroDesconto
   * @return terceiroDesconto
  **/
  public RequisicaoRegistroBoletosTerceiroDesconto getTerceiroDesconto() {
    return terceiroDesconto;
  }

  public void setTerceiroDesconto(RequisicaoRegistroBoletosTerceiroDesconto terceiroDesconto) {
    this.terceiroDesconto = terceiroDesconto;
  }

  public RequisicaoRegistroBoletos jurosMora(RequisicaoRegistroBoletosJurosMora jurosMora) {
    this.jurosMora = jurosMora;
    return this;
  }

   /**
   * Get jurosMora
   * @return jurosMora
  **/
  public RequisicaoRegistroBoletosJurosMora getJurosMora() {
    return jurosMora;
  }

  public void setJurosMora(RequisicaoRegistroBoletosJurosMora jurosMora) {
    this.jurosMora = jurosMora;
  }

  public RequisicaoRegistroBoletos multa(RequisicaoRegistroBoletosMulta multa) {
    this.multa = multa;
    return this;
  }

   /**
   * Get multa
   * @return multa
  **/
  public RequisicaoRegistroBoletosMulta getMulta() {
    return multa;
  }

  public void setMulta(RequisicaoRegistroBoletosMulta multa) {
    this.multa = multa;
  }

  public RequisicaoRegistroBoletos pagador(RequisicaoRegistroBoletosPagador pagador) {
    this.pagador = pagador;
    return this;
  }

   /**
   * Get pagador
   * @return pagador
  **/
  public RequisicaoRegistroBoletosPagador getPagador() {
    return pagador;
  }

  public void setPagador(RequisicaoRegistroBoletosPagador pagador) {
    this.pagador = pagador;
  }

  public RequisicaoRegistroBoletos beneficiarioFinal(RequisicaoRegistroBoletosBeneficiarioFinal beneficiarioFinal) {
    this.beneficiarioFinal = beneficiarioFinal;
    return this;
  }

   /**
   * Get beneficiarioFinal
   * @return beneficiarioFinal
  **/
  public RequisicaoRegistroBoletosBeneficiarioFinal getBeneficiarioFinal() {
    return beneficiarioFinal;
  }

  public void setBeneficiarioFinal(RequisicaoRegistroBoletosBeneficiarioFinal beneficiarioFinal) {
    this.beneficiarioFinal = beneficiarioFinal;
  }

  public RequisicaoRegistroBoletos indicadorPix(String indicadorPix) {
    this.indicadorPix = indicadorPix;
    return this;
  }

   /**
   * Código para informar se o boleto terá um QRCode Pix atrelado. Se informado caracter inválido,  assumirá &#x27;N&#x27;.  Domínios: &#x27;S&#x27; - QRCODE DINAMICO; &#x27;N&#x27; - SEM PIX; OUTRO - SEM PIX
   * @return indicadorPix
  **/
  public String getIndicadorPix() {
    return indicadorPix;
  }

  public void setIndicadorPix(String indicadorPix) {
    this.indicadorPix = indicadorPix;
  }

}
