/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Código utilizado pela FEBRABAN para identificar o tipo de taxa de juros, sendo:  0 - DISPENSAR, 1 - VALOR DIA ATRASO, 2 - TAXA MENSAL, 3 - ISENTO.  Se informado ‘0’ (zero) ou ‘3’ (três), os campos “PERCENTUAL DE JUROS DO TÍTULO” e “VALOR DO JUROS DO TÍTULO” não devem ser informados ou ser informados igual a ‘0’ (zero).   O valor de juros e multa incidem sobre o valor atual do boleto (valor do boleto - valor de abatimento).
 */

public class RequisicaoRegistroBoletosJurosMora {
  private Integer tipo = null;

  private Float porcentagem = null;

  private Float valor = null;

  public RequisicaoRegistroBoletosJurosMora tipo(Integer tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Código utilizado pela FEBRABAN para identificar o tipo de taxa de juros.  Domínios:  0 - DISPENSAR;  1 - VALOR DIA ATRASO;  2 - TAXA MENSAL;  3 - ISENTO.
   * @return tipo
  **/
  public Integer getTipo() {
    return tipo;
  }

  public void setTipo(Integer tipo) {
    this.tipo = tipo;
  }

  public RequisicaoRegistroBoletosJurosMora porcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
    return this;
  }

   /**
   * Se tipo &#x3D; 2, definir uma porcentagem de juros &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return porcentagem
  **/
  public Float getPorcentagem() {
    return porcentagem;
  }

  public void setPorcentagem(Float porcentagem) {
    this.porcentagem = porcentagem;
  }

  public RequisicaoRegistroBoletosJurosMora valor(Float valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Se tipo &#x3D; 1, definir um valor de juros &gt;&#x3D;  0.00 (formato decimal separado por \&quot;.\&quot;).
   * @return valor
  **/
  public Float getValor() {
    return valor;
  }

  public void setValor(Float valor) {
    this.valor = valor;
  }


 

}
