/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Representação dos campos de resposta de uma solicitação de alteração dos dados de boletos bancários.
 */

public class RespostaAlterarBoleto {
  private Integer numeroContratoCobranca = null;

  private String dataAtualizacao = null;

  private String horarioAtualizacao = null;

  public RespostaAlterarBoleto numeroContratoCobranca(Integer numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

   /**
   * Código adotado pelo Banco para identificar o Contrato entre este e a Empresa Cliente
   * @return numeroContratoCobranca
  **/
  public Integer getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }

  public void setNumeroContratoCobranca(Integer numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }

  public RespostaAlterarBoleto dataAtualizacao(String dataAtualizacao) {
    this.dataAtualizacao = dataAtualizacao;
    return this;
  }

   /**
   * Data do pedido de atualização do boleto bancário.
   * @return dataAtualizacao
  **/
  public String getDataAtualizacao() {
    return dataAtualizacao;
  }

  public void setDataAtualizacao(String dataAtualizacao) {
    this.dataAtualizacao = dataAtualizacao;
  }

  public RespostaAlterarBoleto horarioAtualizacao(String horarioAtualizacao) {
    this.horarioAtualizacao = horarioAtualizacao;
    return this;
  }

   /**
   * Horário do pedido de atualização do boleto bancário.HH:mm:ss
   * @return horarioAtualizacao
  **/
  public String getHorarioAtualizacao() {
    return horarioAtualizacao;
  }

  public void setHorarioAtualizacao(String horarioAtualizacao) {
    this.horarioAtualizacao = horarioAtualizacao;
  }

}
