/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.math.BigDecimal;
/**
 * Representação dos campos de resposta de uma solicitação de criação de boletos bancários.
 */
public class RespostaRegistroBoletos {
  private String numero = null;

  private BigDecimal numeroCarteira = null;

  private BigDecimal numeroVariacaoCarteira = null;

  private BigDecimal codigoCliente = null;

  private String linhaDigitavel = null;

  private String codigoBarraNumerico = null;

  private BigDecimal numeroContratoCobranca = null;

  private RespostaRegistroBoletosBeneficiario beneficiario = null;

  private RespostaRegistroBoletosQrCode qrCode = null;

  public RespostaRegistroBoletos numero(String numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Identificador exclusivo do boleto.
   * @return numero
  **/
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public RespostaRegistroBoletos numeroCarteira(BigDecimal numeroCarteira) {
    this.numeroCarteira = numeroCarteira;
    return this;
  }

   /**
   * Número da carteira do convênio de cobrança
   * @return numeroCarteira
  **/
  public BigDecimal getNumeroCarteira() {
    return numeroCarteira;
  }

  public void setNumeroCarteira(BigDecimal numeroCarteira) {
    this.numeroCarteira = numeroCarteira;
  }

  public RespostaRegistroBoletos numeroVariacaoCarteira(BigDecimal numeroVariacaoCarteira) {
    this.numeroVariacaoCarteira = numeroVariacaoCarteira;
    return this;
  }

   /**
   * Número da variação da carteira do convênio de cobrança
   * @return numeroVariacaoCarteira
  **/
  public BigDecimal getNumeroVariacaoCarteira() {
    return numeroVariacaoCarteira;
  }

  public void setNumeroVariacaoCarteira(BigDecimal numeroVariacaoCarteira) {
    this.numeroVariacaoCarteira = numeroVariacaoCarteira;
  }

  public RespostaRegistroBoletos codigoCliente(BigDecimal codigoCliente) {
    this.codigoCliente = codigoCliente;
    return this;
  }

   /**
   * Identificação do cliente.
   * @return codigoCliente
  **/
  public BigDecimal getCodigoCliente() {
    return codigoCliente;
  }

  public void setCodigoCliente(BigDecimal codigoCliente) {
    this.codigoCliente = codigoCliente;
  }

  public RespostaRegistroBoletos linhaDigitavel(String linhaDigitavel) {
    this.linhaDigitavel = linhaDigitavel;
    return this;
  }

   /**
   * Linha digitável do boleto.
   * @return linhaDigitavel
  **/
  public String getLinhaDigitavel() {
    return linhaDigitavel;
  }

  public void setLinhaDigitavel(String linhaDigitavel) {
    this.linhaDigitavel = linhaDigitavel;
  }

  public RespostaRegistroBoletos codigoBarraNumerico(String codigoBarraNumerico) {
    this.codigoBarraNumerico = codigoBarraNumerico;
    return this;
  }

   /**
   * Define o código de barras numérico do boleto.
   * @return codigoBarraNumerico
  **/
  public String getCodigoBarraNumerico() {
    return codigoBarraNumerico;
  }

  public void setCodigoBarraNumerico(String codigoBarraNumerico) {
    this.codigoBarraNumerico = codigoBarraNumerico;
  }

  public RespostaRegistroBoletos numeroContratoCobranca(BigDecimal numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

   /**
   * Define o número do contrato de cobrança do boleto.
   * @return numeroContratoCobranca
  **/
  public BigDecimal getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }

  public void setNumeroContratoCobranca(BigDecimal numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }

  public RespostaRegistroBoletos beneficiario(RespostaRegistroBoletosBeneficiario beneficiario) {
    this.beneficiario = beneficiario;
    return this;
  }

   /**
   * Get beneficiario
   * @return beneficiario
  **/
  public RespostaRegistroBoletosBeneficiario getBeneficiario() {
    return beneficiario;
  }

  public void setBeneficiario(RespostaRegistroBoletosBeneficiario beneficiario) {
    this.beneficiario = beneficiario;
  }

  public RespostaRegistroBoletos qrCode(RespostaRegistroBoletosQrCode qrCode) {
    this.qrCode = qrCode;
    return this;
  }

   /**
   * Get qrCode
   * @return qrCode
  **/
  public RespostaRegistroBoletosQrCode getQrCode() {
    return qrCode;
  }

  public void setQrCode(RespostaRegistroBoletosQrCode qrCode) {
    this.qrCode = qrCode;
  }

}
