/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Representação dos campos de resposta de uma solicitação de detalhamento de pix vinculado a boleto bancário.
 */

public class RespostaConsultaPixBoleto {
  private String id = null;

  private String dataRegistroTituloCobranca = null;

  private Integer agenciaBeneficiario = null;

  private Integer contaBeneficiario = null;

  private Float valorOriginalTituloCobranca = null;

  private String validadeTituloCobranca = null;

  private RespostaConsultaPixBoletoPix pix = null;

  private RespostaConsultaPixBoletoQrCode qrCode = null;

  public RespostaConsultaPixBoleto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Número de identificação do boleto (correspondente ao NOSSO NÚMERO, numeroTituloCliente), no formato STRING, com 20 dígitos, que deverá ser formatado da seguinte forma:  “000” +  (número do convênio com 7 dígitos) + (10 algarismos - se necessário, completar com zeros à esquerda). Campo Obrigatório.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RespostaConsultaPixBoleto dataRegistroTituloCobranca(String dataRegistroTituloCobranca) {
    this.dataRegistroTituloCobranca = dataRegistroTituloCobranca;
    return this;
  }

   /**
   * Data de registro do boleto no banco.
   * @return dataRegistroTituloCobranca
  **/
  public String getDataRegistroTituloCobranca() {
    return dataRegistroTituloCobranca;
  }

  public void setDataRegistroTituloCobranca(String dataRegistroTituloCobranca) {
    this.dataRegistroTituloCobranca = dataRegistroTituloCobranca;
  }

  public RespostaConsultaPixBoleto agenciaBeneficiario(Integer agenciaBeneficiario) {
    this.agenciaBeneficiario = agenciaBeneficiario;
    return this;
  }

   /**
   * Número da agência do beneficiário, sem o dígito verificador.
   * @return agenciaBeneficiario
  **/
  public Integer getAgenciaBeneficiario() {
    return agenciaBeneficiario;
  }

  public void setAgenciaBeneficiario(Integer agenciaBeneficiario) {
    this.agenciaBeneficiario = agenciaBeneficiario;
  }

  public RespostaConsultaPixBoleto contaBeneficiario(Integer contaBeneficiario) {
    this.contaBeneficiario = contaBeneficiario;
    return this;
  }

   /**
   * Número da conta do beneficiário, sem o dígito verificador.
   * @return contaBeneficiario
  **/
  public Integer getContaBeneficiario() {
    return contaBeneficiario;
  }

  public void setContaBeneficiario(Integer contaBeneficiario) {
    this.contaBeneficiario = contaBeneficiario;
  }

  public RespostaConsultaPixBoleto valorOriginalTituloCobranca(Float valorOriginalTituloCobranca) {
    this.valorOriginalTituloCobranca = valorOriginalTituloCobranca;
    return this;
  }

   /**
   * Valor original do boleto indicado quando do registro.
   * @return valorOriginalTituloCobranca
  **/
  public Float getValorOriginalTituloCobranca() {
    return valorOriginalTituloCobranca;
  }

  public void setValorOriginalTituloCobranca(Float valorOriginalTituloCobranca) {
    this.valorOriginalTituloCobranca = valorOriginalTituloCobranca;
  }

  public RespostaConsultaPixBoleto validadeTituloCobranca(String validadeTituloCobranca) {
    this.validadeTituloCobranca = validadeTituloCobranca;
    return this;
  }

   /**
   * Data de validade do boleto.
   * @return validadeTituloCobranca
  **/
  public String getValidadeTituloCobranca() {
    return validadeTituloCobranca;
  }

  public void setValidadeTituloCobranca(String validadeTituloCobranca) {
    this.validadeTituloCobranca = validadeTituloCobranca;
  }

  public RespostaConsultaPixBoleto pix(RespostaConsultaPixBoletoPix pix) {
    this.pix = pix;
    return this;
  }

   /**
   * Get pix
   * @return pix
  **/
  public RespostaConsultaPixBoletoPix getPix() {
    return pix;
  }

  public void setPix(RespostaConsultaPixBoletoPix pix) {
    this.pix = pix;
  }

  public RespostaConsultaPixBoleto qrCode(RespostaConsultaPixBoletoQrCode qrCode) {
    this.qrCode = qrCode;
    return this;
  }

   /**
   * Get qrCode
   * @return qrCode
  **/
  public RespostaConsultaPixBoletoQrCode getQrCode() {
    return qrCode;
  }

  public void setQrCode(RespostaConsultaPixBoletoQrCode qrCode) {
    this.qrCode = qrCode;
  }

}
