/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.util.ArrayList;
import java.util.List;
/**
 * Objeto de Resposta do recurso GET Lista Boletos
 */

public class RespostaListaBoletos {
  private String indicadorContinuidade = null;

  private Integer quantidadeRegistros = null;

  private Integer proximoIndice = null;

  private List<RespostaListaBoletosBoletos> boletos = null;

  public RespostaListaBoletos indicadorContinuidade(String indicadorContinuidade) {
    this.indicadorContinuidade = indicadorContinuidade;
    return this;
  }

   /**
   * Indicador de que a consulta resultou em uma quantidade superior a 300 boletos (capacidade de resposta por requisição do serviço). Uma nova requisição, nos mesmos moldes, deve ser feita para consultar o restante dos boletos. Para tanto, deverá ser utilizado o valor informado no atributo \&quot;Número Último Registro\&quot; como valor inicial da próxima consulta.
   * @return indicadorContinuidade
  **/
  public String getIndicadorContinuidade() {
    return indicadorContinuidade;
  }

  public void setIndicadorContinuidade(String indicadorContinuidade) {
    this.indicadorContinuidade = indicadorContinuidade;
  }

  public RespostaListaBoletos quantidadeRegistros(Integer quantidadeRegistros) {
    this.quantidadeRegistros = quantidadeRegistros;
    return this;
  }

   /**
   * Quantidade de boletos que atendem os critérios da requisição. 
   * @return quantidadeRegistros
  **/
  public Integer getQuantidadeRegistros() {
    return quantidadeRegistros;
  }

  public void setQuantidadeRegistros(Integer quantidadeRegistros) {
    this.quantidadeRegistros = quantidadeRegistros;
  }

  public RespostaListaBoletos proximoIndice(Integer proximoIndice) {
    this.proximoIndice = proximoIndice;
    return this;
  }

   /**
   * Número do último registro apresentado pela lista, que poderá ser utilizado como parâmetro inicial de uma nova requisição para consultar os boletos restantes.
   * @return proximoIndice
  **/
  public Integer getProximoIndice() {
    return proximoIndice;
  }

  public void setProximoIndice(Integer proximoIndice) {
    this.proximoIndice = proximoIndice;
  }

  public RespostaListaBoletos boletos(List<RespostaListaBoletosBoletos> boletos) {
    this.boletos = boletos;
    return this;
  }

  public RespostaListaBoletos addBoletosItem(RespostaListaBoletosBoletos boletosItem) {
    if (this.boletos == null) {
      this.boletos = new ArrayList<RespostaListaBoletosBoletos>();
    }
    this.boletos.add(boletosItem);
    return this;
  }

   /**
   * Get boletos
   * @return boletos
  **/
  public List<RespostaListaBoletosBoletos> getBoletos() {
    return boletos;
  }

  public void setBoletos(List<RespostaListaBoletosBoletos> boletos) {
    this.boletos = boletos;
  }

}
