/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * RespostaConsultaPixBoletoPix
 */

public class RespostaConsultaPixBoletoPix {
  private Float valorRecebido = null;

  private String timestamp = null;

  private String chave = null;

  private String textoRetorno = null;

  private Integer idInstituicaoPagador = null;

  private Integer agenciaPagador = null;

  private Integer contaPagador = null;

  private Integer tipoPessoaPagador = null;

  private Integer idPagador = null;

  public RespostaConsultaPixBoletoPix valorRecebido(Float valorRecebido) {
    this.valorRecebido = valorRecebido;
    return this;
  }

   /**
   * Valor recebido via Pix.
   * @return valorRecebido
  **/
  public Float getValorRecebido() {
    return valorRecebido;
  }

  public void setValorRecebido(Float valorRecebido) {
    this.valorRecebido = valorRecebido;
  }

  public RespostaConsultaPixBoletoPix timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Data e hora do recebimento via Pix.
   * @return timestamp
  **/
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public RespostaConsultaPixBoletoPix chave(String chave) {
    this.chave = chave;
    return this;
  }

   /**
   * Código chave do pagador do Pix.
   * @return chave
  **/
  public String getChave() {
    return chave;
  }

  public void setChave(String chave) {
    this.chave = chave;
  }

  public RespostaConsultaPixBoletoPix textoRetorno(String textoRetorno) {
    this.textoRetorno = textoRetorno;
    return this;
  }

   /**
   * Texto da mensagem de retorno do Pix.
   * @return textoRetorno
  **/
  public String getTextoRetorno() {
    return textoRetorno;
  }

  public void setTextoRetorno(String textoRetorno) {
    this.textoRetorno = textoRetorno;
  }

  public RespostaConsultaPixBoletoPix idInstituicaoPagador(Integer idInstituicaoPagador) {
    this.idInstituicaoPagador = idInstituicaoPagador;
    return this;
  }

   /**
   * Código identificador da instituição do pagador do Pix.
   * @return idInstituicaoPagador
  **/
  public Integer getIdInstituicaoPagador() {
    return idInstituicaoPagador;
  }

  public void setIdInstituicaoPagador(Integer idInstituicaoPagador) {
    this.idInstituicaoPagador = idInstituicaoPagador;
  }

  public RespostaConsultaPixBoletoPix agenciaPagador(Integer agenciaPagador) {
    this.agenciaPagador = agenciaPagador;
    return this;
  }

   /**
   * Prefixo da agência do pagador do Pix.
   * @return agenciaPagador
  **/
  public Integer getAgenciaPagador() {
    return agenciaPagador;
  }

  public void setAgenciaPagador(Integer agenciaPagador) {
    this.agenciaPagador = agenciaPagador;
  }

  public RespostaConsultaPixBoletoPix contaPagador(Integer contaPagador) {
    this.contaPagador = contaPagador;
    return this;
  }

   /**
   * Número da conta corrente do pagador do Pix.
   * @return contaPagador
  **/
  public Integer getContaPagador() {
    return contaPagador;
  }

  public void setContaPagador(Integer contaPagador) {
    this.contaPagador = contaPagador;
  }

  public RespostaConsultaPixBoletoPix tipoPessoaPagador(Integer tipoPessoaPagador) {
    this.tipoPessoaPagador = tipoPessoaPagador;
    return this;
  }

   /**
   * Código do tipo de pessoa do pagador do Pix. Este valor pode ser 1 para Pessoa Física ou 2 para Pessoa Jurídica.
   * minimum: 1
   * maximum: 2
   * @return tipoPessoaPagador
  **/
  public Integer getTipoPessoaPagador() {
    return tipoPessoaPagador;
  }

  public void setTipoPessoaPagador(Integer tipoPessoaPagador) {
    this.tipoPessoaPagador = tipoPessoaPagador;
  }

  public RespostaConsultaPixBoletoPix idPagador(Integer idPagador) {
    this.idPagador = idPagador;
    return this;
  }

   /**
   * Número do CPF ou CNPJ do pagador do Pix.
   * @return idPagador
  **/
  public Integer getIdPagador() {
    return idPagador;
  }

  public void setIdPagador(Integer idPagador) {
    this.idPagador = idPagador;
  }

}
