/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.math.BigDecimal;
/**
 * RespostaRegistroBoletosBeneficiario
 */

public class RespostaRegistroBoletosBeneficiario {
  private BigDecimal agencia = null;

  private BigDecimal contaCorrente = null;

  private BigDecimal tipoEndereco = null;

  private String logradouro = null;

  private String bairro = null;

  private String cidade = null;

  private BigDecimal codigoCidade = null;

  private String uf = null;

  private BigDecimal cep = null;

  private String indicadorComprovacao = null;

  public RespostaRegistroBoletosBeneficiario agencia(BigDecimal agencia) {
    this.agencia = agencia;
    return this;
  }

   /**
   * Agência do beneficiário.
   * @return agencia
  **/
  public BigDecimal getAgencia() {
    return agencia;
  }

  public void setAgencia(BigDecimal agencia) {
    this.agencia = agencia;
  }

  public RespostaRegistroBoletosBeneficiario contaCorrente(BigDecimal contaCorrente) {
    this.contaCorrente = contaCorrente;
    return this;
  }

   /**
   * Número da conta corrente do beneficiário.
   * @return contaCorrente
  **/
  public BigDecimal getContaCorrente() {
    return contaCorrente;
  }

  public void setContaCorrente(BigDecimal contaCorrente) {
    this.contaCorrente = contaCorrente;
  }

  public RespostaRegistroBoletosBeneficiario tipoEndereco(BigDecimal tipoEndereco) {
    this.tipoEndereco = tipoEndereco;
    return this;
  }

   /**
   * Código do tipo de endereço do beneficiário.
   * @return tipoEndereco
  **/
  public BigDecimal getTipoEndereco() {
    return tipoEndereco;
  }

  public void setTipoEndereco(BigDecimal tipoEndereco) {
    this.tipoEndereco = tipoEndereco;
  }

  public RespostaRegistroBoletosBeneficiario logradouro(String logradouro) {
    this.logradouro = logradouro;
    return this;
  }

   /**
   * Nome do logradouro do beneficiário.
   * @return logradouro
  **/
  public String getLogradouro() {
    return logradouro;
  }

  public void setLogradouro(String logradouro) {
    this.logradouro = logradouro;
  }

  public RespostaRegistroBoletosBeneficiario bairro(String bairro) {
    this.bairro = bairro;
    return this;
  }

   /**
   * Bairro do Beneficiário.
   * @return bairro
  **/
  public String getBairro() {
    return bairro;
  }

  public void setBairro(String bairro) {
    this.bairro = bairro;
  }

  public RespostaRegistroBoletosBeneficiario cidade(String cidade) {
    this.cidade = cidade;
    return this;
  }

   /**
   * Cidade do Beneficiário.
   * @return cidade
  **/
  public String getCidade() {
    return cidade;
  }

  public void setCidade(String cidade) {
    this.cidade = cidade;
  }

  public RespostaRegistroBoletosBeneficiario codigoCidade(BigDecimal codigoCidade) {
    this.codigoCidade = codigoCidade;
    return this;
  }

   /**
   * Identificador da cidade do beneficiário.
   * @return codigoCidade
  **/
  public BigDecimal getCodigoCidade() {
    return codigoCidade;
  }

  public void setCodigoCidade(BigDecimal codigoCidade) {
    this.codigoCidade = codigoCidade;
  }

  public RespostaRegistroBoletosBeneficiario uf(String uf) {
    this.uf = uf;
    return this;
  }

   /**
   * Sigla do Estado do beneficiário.
   * @return uf
  **/
  public String getUf() {
    return uf;
  }

  public void setUf(String uf) {
    this.uf = uf;
  }

  public RespostaRegistroBoletosBeneficiario cep(BigDecimal cep) {
    this.cep = cep;
    return this;
  }

   /**
   * Código Postal do Beneficiário.
   * @return cep
  **/
  public BigDecimal getCep() {
    return cep;
  }

  public void setCep(BigDecimal cep) {
    this.cep = cep;
  }

  public RespostaRegistroBoletosBeneficiario indicadorComprovacao(String indicadorComprovacao) {
    this.indicadorComprovacao = indicadorComprovacao;
    return this;
  }

   /**
   * Indicador de prova de vida do beneficiário.
   * @return indicadorComprovacao
  **/
  public String getIndicadorComprovacao() {
    return indicadorComprovacao;
  }

  public void setIndicadorComprovacao(String indicadorComprovacao) {
    this.indicadorComprovacao = indicadorComprovacao;
  }

}
