/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

import java.math.BigDecimal;

/**
 * Representação dos campos de resposta de uma solicitação de detalhamento de
 * boletos bancários.
 */
public class RespostaDetalhamentoBoleto {
	private String codigoLinhaDigitavel = null;

	private String textoEmailPagador = null;

	private String textoMensagemBloquetoTitulo = null;

	private BigDecimal codigoTipoMulta = null;

	private BigDecimal codigoCanalPagamento = null;

	private BigDecimal numeroContratoCobranca = null;

	private BigDecimal codigoTipoInscricaoSacado = null;

	private BigDecimal numeroInscricaoSacadoCobranca = null;

	private BigDecimal codigoEstadoTituloCobranca = null;

	private BigDecimal codigoTipoTituloCobranca = null;

	private BigDecimal codigoModalidadeTitulo = null;

	private String codigoAceiteTituloCobranca = null;

	private BigDecimal codigoPrefixoDependenciaCobrador = null;

	private BigDecimal codigoIndicadorEconomico = null;

	private String numeroTituloCedenteCobranca = null;

	private BigDecimal codigoTipoJuroMora = null;

	private String dataEmissaoTituloCobranca = null;

	private String dataRegistroTituloCobranca = null;

	private String dataVencimentoTituloCobranca = null;

	private Float valorOriginalTituloCobranca = null;

	private Float valorAtualTituloCobranca = null;

	private Float valorPagamentoParcialTitulo = null;

	private Float valorAbatimentoTituloCobranca = null;

	private Float percentualImpostoSobreOprFinanceirasTituloCobranca = null;

	private Float valorImpostoSobreOprFinanceirasTituloCobranca = null;

	private Float valorMoedaTituloCobranca = null;

	private BigDecimal percentualJuroMoraTitulo = null;

	private Float valorJuroMoraTitulo = null;

	private Float percentualMultaTitulo = null;

	private Float valorMultaTituloCobranca = null;

	private BigDecimal quantidadeParcelaTituloCobranca = null;

	private String dataBaixaAutomaticoTitulo = null;

	private String textoCampoUtilizacaoCedente = null;

	private String indicadorCobrancaPartilhadoTitulo = null;

	private String nomeSacadoCobranca = null;

	private String textoEnderecoSacadoCobranca = null;

	private String nomeBairroSacadoCobranca = null;

	private String nomeMunicipioSacadoCobranca = null;

	private String siglaUnidadeFederacaoSacadoCobranca = null;

	private BigDecimal numeroCepSacadoCobranca = null;

	private Float valorMoedaAbatimentoTitulo = null;

	private String dataProtestoTituloCobranca = null;

	private BigDecimal codigoTipoInscricaoSacador = null;

	private BigDecimal numeroInscricaoSacadorAvalista = null;

	private String nomeSacadorAvalistaTitulo = null;

	private Float percentualDescontoTitulo = null;

	private String dataDescontoTitulo = null;

	private Float valorDescontoTitulo = null;

	private BigDecimal codigoDescontoTitulo = null;

	private Float percentualSegundoDescontoTitulo = null;

	private String dataSegundoDescontoTitulo = null;

	private Float valorSegundoDescontoTitulo = null;

	private BigDecimal codigoSegundoDescontoTitulo = null;

	private Float percentualTerceiroDescontoTitulo = null;

	private String dataTerceiroDescontoTitulo = null;

	private Float valorTerceiroDescontoTitulo = null;

	private BigDecimal codigoTerceiroDescontoTitulo = null;

	private String dataMultaTitulo = null;

	private BigDecimal numeroCarteiraCobranca = null;

	private BigDecimal numeroVariacaoCarteiraCobranca = null;

	private BigDecimal quantidadeDiaProtesto = null;

	private BigDecimal quantidadeDiaPrazoLimiteRecebimento = null;

	private String dataLimiteRecebimentoTitulo = null;

	private String indicadorPermissaoRecebimentoParcial = null;

	private String textoCodigoBarrasTituloCobranca = null;

	private BigDecimal codigoOcorrenciaCartorio = null;

	private Float valorImpostoSobreOprFinanceirasRecebidoTitulo = null;

	private Float valorAbatimentoTotal = null;

	private Float valorJuroMoraRecebido = null;

	private Float valorDescontoUtilizado = null;

	private Float valorPagoSacado = null;

	private Float valorCreditoCedente = null;

	private BigDecimal codigoTipoLiquidacao = null;

	private String dataCreditoLiquidacao = null;

	private String dataRecebimentoTitulo = null;

	private BigDecimal codigoPrefixoDependenciaRecebedor = null;

	private BigDecimal codigoNaturezaRecebimento = null;

	private String numeroIdentidadeSacadoTituloCobranca = null;

	private String codigoResponsavelAtualizacao = null;

	private BigDecimal codigoTipoBaixaTitulo = null;

	private Float valorMultaRecebido = null;

	private Float valorReajuste = null;

	private Float valorOutroRecebido = null;

	private Float codigoIndicadorEconomicoUtilizadoInadimplencia = null;

	public RespostaDetalhamentoBoleto codigoLinhaDigitavel(String codigoLinhaDigitavel) {
		this.codigoLinhaDigitavel = codigoLinhaDigitavel;
		return this;
	}

	/**
	 * Campo correpondente à linha digitável do boleto.
	 * 
	 * @return codigoLinhaDigitavel
	 **/
	public String getCodigoLinhaDigitavel() {
		return codigoLinhaDigitavel;
	}

	public void setCodigoLinhaDigitavel(String codigoLinhaDigitavel) {
		this.codigoLinhaDigitavel = codigoLinhaDigitavel;
	}

	public RespostaDetalhamentoBoleto textoEmailPagador(String textoEmailPagador) {
		this.textoEmailPagador = textoEmailPagador;
		return this;
	}

	/**
	 * E-mail do Pagador.
	 * 
	 * @return textoEmailPagador
	 **/
	public String getTextoEmailPagador() {
		return textoEmailPagador;
	}

	public void setTextoEmailPagador(String textoEmailPagador) {
		this.textoEmailPagador = textoEmailPagador;
	}

	public RespostaDetalhamentoBoleto textoMensagemBloquetoTitulo(String textoMensagemBloquetoTitulo) {
		this.textoMensagemBloquetoTitulo = textoMensagemBloquetoTitulo;
		return this;
	}

	/**
	 * Mensagem para ser impressa no boleto.
	 * 
	 * @return textoMensagemBloquetoTitulo
	 **/
	public String getTextoMensagemBloquetoTitulo() {
		return textoMensagemBloquetoTitulo;
	}

	public void setTextoMensagemBloquetoTitulo(String textoMensagemBloquetoTitulo) {
		this.textoMensagemBloquetoTitulo = textoMensagemBloquetoTitulo;
	}

	public RespostaDetalhamentoBoleto codigoTipoMulta(BigDecimal codigoTipoMulta) {
		this.codigoTipoMulta = codigoTipoMulta;
		return this;
	}

	/**
	 * Código para identificação do tipo de multa para o Título de Cobrança.
	 * Domínios: 0 - Sem multa 1 - Valor da Multa 2 - Percentual da Multa.
	 * 
	 * @return codigoTipoMulta
	 **/
	public BigDecimal getCodigoTipoMulta() {
		return codigoTipoMulta;
	}

	public void setCodigoTipoMulta(BigDecimal codigoTipoMulta) {
		this.codigoTipoMulta = codigoTipoMulta;
	}

	public RespostaDetalhamentoBoleto codigoCanalPagamento(BigDecimal codigoCanalPagamento) {
		this.codigoCanalPagamento = codigoCanalPagamento;
		return this;
	}

	public BigDecimal getCodigoCanalPagamento() {
		return codigoCanalPagamento;
	}

	public void setCodigoCanalPagamento(BigDecimal codigoCanalPagamento) {
		this.codigoCanalPagamento = codigoCanalPagamento;
	}

	public BigDecimal getNumeroContratoCobranca() {
		return numeroContratoCobranca;
	}

	public void setNumeroContratoCobranca(BigDecimal numeroContratoCobranca) {
		this.numeroContratoCobranca = numeroContratoCobranca;
	}

	public BigDecimal getCodigoTipoInscricaoSacado() {
		return codigoTipoInscricaoSacado;
	}

	public void setCodigoTipoInscricaoSacado(BigDecimal codigoTipoInscricaoSacado) {
		this.codigoTipoInscricaoSacado = codigoTipoInscricaoSacado;
	}

	public BigDecimal getNumeroInscricaoSacadoCobranca() {
		return numeroInscricaoSacadoCobranca;
	}

	public void setNumeroInscricaoSacadoCobranca(BigDecimal numeroInscricaoSacadoCobranca) {
		this.numeroInscricaoSacadoCobranca = numeroInscricaoSacadoCobranca;
	}

	public BigDecimal getCodigoEstadoTituloCobranca() {
		return codigoEstadoTituloCobranca;
	}

	public void setCodigoEstadoTituloCobranca(BigDecimal codigoEstadoTituloCobranca) {
		this.codigoEstadoTituloCobranca = codigoEstadoTituloCobranca;
	}

	public BigDecimal getCodigoTipoTituloCobranca() {
		return codigoTipoTituloCobranca;
	}

	public void setCodigoTipoTituloCobranca(BigDecimal codigoTipoTituloCobranca) {
		this.codigoTipoTituloCobranca = codigoTipoTituloCobranca;
	}

	public BigDecimal getCodigoModalidadeTitulo() {
		return codigoModalidadeTitulo;
	}

	public void setCodigoModalidadeTitulo(BigDecimal codigoModalidadeTitulo) {
		this.codigoModalidadeTitulo = codigoModalidadeTitulo;
	}

	public String getCodigoAceiteTituloCobranca() {
		return codigoAceiteTituloCobranca;
	}

	public void setCodigoAceiteTituloCobranca(String codigoAceiteTituloCobranca) {
		this.codigoAceiteTituloCobranca = codigoAceiteTituloCobranca;
	}

	public BigDecimal getCodigoPrefixoDependenciaCobrador() {
		return codigoPrefixoDependenciaCobrador;
	}

	public void setCodigoPrefixoDependenciaCobrador(BigDecimal codigoPrefixoDependenciaCobrador) {
		this.codigoPrefixoDependenciaCobrador = codigoPrefixoDependenciaCobrador;
	}

	public BigDecimal getCodigoIndicadorEconomico() {
		return codigoIndicadorEconomico;
	}

	public void setCodigoIndicadorEconomico(BigDecimal codigoIndicadorEconomico) {
		this.codigoIndicadorEconomico = codigoIndicadorEconomico;
	}

	public String getNumeroTituloCedenteCobranca() {
		return numeroTituloCedenteCobranca;
	}

	public void setNumeroTituloCedenteCobranca(String numeroTituloCedenteCobranca) {
		this.numeroTituloCedenteCobranca = numeroTituloCedenteCobranca;
	}

	public BigDecimal getCodigoTipoJuroMora() {
		return codigoTipoJuroMora;
	}

	public void setCodigoTipoJuroMora(BigDecimal codigoTipoJuroMora) {
		this.codigoTipoJuroMora = codigoTipoJuroMora;
	}

	public String getDataEmissaoTituloCobranca() {
		return dataEmissaoTituloCobranca;
	}

	public void setDataEmissaoTituloCobranca(String dataEmissaoTituloCobranca) {
		this.dataEmissaoTituloCobranca = dataEmissaoTituloCobranca;
	}

	public String getDataRegistroTituloCobranca() {
		return dataRegistroTituloCobranca;
	}

	public void setDataRegistroTituloCobranca(String dataRegistroTituloCobranca) {
		this.dataRegistroTituloCobranca = dataRegistroTituloCobranca;
	}

	public String getDataVencimentoTituloCobranca() {
		return dataVencimentoTituloCobranca;
	}

	public void setDataVencimentoTituloCobranca(String dataVencimentoTituloCobranca) {
		this.dataVencimentoTituloCobranca = dataVencimentoTituloCobranca;
	}

	public Float getValorOriginalTituloCobranca() {
		return valorOriginalTituloCobranca;
	}

	public void setValorOriginalTituloCobranca(Float valorOriginalTituloCobranca) {
		this.valorOriginalTituloCobranca = valorOriginalTituloCobranca;
	}

	public Float getValorAtualTituloCobranca() {
		return valorAtualTituloCobranca;
	}

	public void setValorAtualTituloCobranca(Float valorAtualTituloCobranca) {
		this.valorAtualTituloCobranca = valorAtualTituloCobranca;
	}

	public Float getValorPagamentoParcialTitulo() {
		return valorPagamentoParcialTitulo;
	}

	public void setValorPagamentoParcialTitulo(Float valorPagamentoParcialTitulo) {
		this.valorPagamentoParcialTitulo = valorPagamentoParcialTitulo;
	}

	public Float getValorAbatimentoTituloCobranca() {
		return valorAbatimentoTituloCobranca;
	}

	public void setValorAbatimentoTituloCobranca(Float valorAbatimentoTituloCobranca) {
		this.valorAbatimentoTituloCobranca = valorAbatimentoTituloCobranca;
	}

	public Float getPercentualImpostoSobreOprFinanceirasTituloCobranca() {
		return percentualImpostoSobreOprFinanceirasTituloCobranca;
	}

	public void setPercentualImpostoSobreOprFinanceirasTituloCobranca(
			Float percentualImpostoSobreOprFinanceirasTituloCobranca) {
		this.percentualImpostoSobreOprFinanceirasTituloCobranca = percentualImpostoSobreOprFinanceirasTituloCobranca;
	}

	public Float getValorImpostoSobreOprFinanceirasTituloCobranca() {
		return valorImpostoSobreOprFinanceirasTituloCobranca;
	}

	public void setValorImpostoSobreOprFinanceirasTituloCobranca(Float valorImpostoSobreOprFinanceirasTituloCobranca) {
		this.valorImpostoSobreOprFinanceirasTituloCobranca = valorImpostoSobreOprFinanceirasTituloCobranca;
	}

	public Float getValorMoedaTituloCobranca() {
		return valorMoedaTituloCobranca;
	}

	public void setValorMoedaTituloCobranca(Float valorMoedaTituloCobranca) {
		this.valorMoedaTituloCobranca = valorMoedaTituloCobranca;
	}

	public BigDecimal getPercentualJuroMoraTitulo() {
		return percentualJuroMoraTitulo;
	}

	public void setPercentualJuroMoraTitulo(BigDecimal percentualJuroMoraTitulo) {
		this.percentualJuroMoraTitulo = percentualJuroMoraTitulo;
	}

	public Float getValorJuroMoraTitulo() {
		return valorJuroMoraTitulo;
	}

	public void setValorJuroMoraTitulo(Float valorJuroMoraTitulo) {
		this.valorJuroMoraTitulo = valorJuroMoraTitulo;
	}

	public Float getPercentualMultaTitulo() {
		return percentualMultaTitulo;
	}

	public void setPercentualMultaTitulo(Float percentualMultaTitulo) {
		this.percentualMultaTitulo = percentualMultaTitulo;
	}

	public Float getValorMultaTituloCobranca() {
		return valorMultaTituloCobranca;
	}

	public void setValorMultaTituloCobranca(Float valorMultaTituloCobranca) {
		this.valorMultaTituloCobranca = valorMultaTituloCobranca;
	}

	public BigDecimal getQuantidadeParcelaTituloCobranca() {
		return quantidadeParcelaTituloCobranca;
	}

	public void setQuantidadeParcelaTituloCobranca(BigDecimal quantidadeParcelaTituloCobranca) {
		this.quantidadeParcelaTituloCobranca = quantidadeParcelaTituloCobranca;
	}

	public String getDataBaixaAutomaticoTitulo() {
		return dataBaixaAutomaticoTitulo;
	}

	public void setDataBaixaAutomaticoTitulo(String dataBaixaAutomaticoTitulo) {
		this.dataBaixaAutomaticoTitulo = dataBaixaAutomaticoTitulo;
	}

	public String getTextoCampoUtilizacaoCedente() {
		return textoCampoUtilizacaoCedente;
	}

	public void setTextoCampoUtilizacaoCedente(String textoCampoUtilizacaoCedente) {
		this.textoCampoUtilizacaoCedente = textoCampoUtilizacaoCedente;
	}

	public String getIndicadorCobrancaPartilhadoTitulo() {
		return indicadorCobrancaPartilhadoTitulo;
	}

	public void setIndicadorCobrancaPartilhadoTitulo(String indicadorCobrancaPartilhadoTitulo) {
		this.indicadorCobrancaPartilhadoTitulo = indicadorCobrancaPartilhadoTitulo;
	}

	public String getNomeSacadoCobranca() {
		return nomeSacadoCobranca;
	}

	public void setNomeSacadoCobranca(String nomeSacadoCobranca) {
		this.nomeSacadoCobranca = nomeSacadoCobranca;
	}

	public String getTextoEnderecoSacadoCobranca() {
		return textoEnderecoSacadoCobranca;
	}

	public void setTextoEnderecoSacadoCobranca(String textoEnderecoSacadoCobranca) {
		this.textoEnderecoSacadoCobranca = textoEnderecoSacadoCobranca;
	}

	public String getNomeBairroSacadoCobranca() {
		return nomeBairroSacadoCobranca;
	}

	public void setNomeBairroSacadoCobranca(String nomeBairroSacadoCobranca) {
		this.nomeBairroSacadoCobranca = nomeBairroSacadoCobranca;
	}

	public String getNomeMunicipioSacadoCobranca() {
		return nomeMunicipioSacadoCobranca;
	}

	public void setNomeMunicipioSacadoCobranca(String nomeMunicipioSacadoCobranca) {
		this.nomeMunicipioSacadoCobranca = nomeMunicipioSacadoCobranca;
	}

	public String getSiglaUnidadeFederacaoSacadoCobranca() {
		return siglaUnidadeFederacaoSacadoCobranca;
	}

	public void setSiglaUnidadeFederacaoSacadoCobranca(String siglaUnidadeFederacaoSacadoCobranca) {
		this.siglaUnidadeFederacaoSacadoCobranca = siglaUnidadeFederacaoSacadoCobranca;
	}

	public BigDecimal getNumeroCepSacadoCobranca() {
		return numeroCepSacadoCobranca;
	}

	public void setNumeroCepSacadoCobranca(BigDecimal numeroCepSacadoCobranca) {
		this.numeroCepSacadoCobranca = numeroCepSacadoCobranca;
	}

	public Float getValorMoedaAbatimentoTitulo() {
		return valorMoedaAbatimentoTitulo;
	}

	public void setValorMoedaAbatimentoTitulo(Float valorMoedaAbatimentoTitulo) {
		this.valorMoedaAbatimentoTitulo = valorMoedaAbatimentoTitulo;
	}

	public String getDataProtestoTituloCobranca() {
		return dataProtestoTituloCobranca;
	}

	public void setDataProtestoTituloCobranca(String dataProtestoTituloCobranca) {
		this.dataProtestoTituloCobranca = dataProtestoTituloCobranca;
	}

	public BigDecimal getCodigoTipoInscricaoSacador() {
		return codigoTipoInscricaoSacador;
	}

	public void setCodigoTipoInscricaoSacador(BigDecimal codigoTipoInscricaoSacador) {
		this.codigoTipoInscricaoSacador = codigoTipoInscricaoSacador;
	}

	public BigDecimal getNumeroInscricaoSacadorAvalista() {
		return numeroInscricaoSacadorAvalista;
	}

	public void setNumeroInscricaoSacadorAvalista(BigDecimal numeroInscricaoSacadorAvalista) {
		this.numeroInscricaoSacadorAvalista = numeroInscricaoSacadorAvalista;
	}

	public String getNomeSacadorAvalistaTitulo() {
		return nomeSacadorAvalistaTitulo;
	}

	public void setNomeSacadorAvalistaTitulo(String nomeSacadorAvalistaTitulo) {
		this.nomeSacadorAvalistaTitulo = nomeSacadorAvalistaTitulo;
	}

	public Float getPercentualDescontoTitulo() {
		return percentualDescontoTitulo;
	}

	public void setPercentualDescontoTitulo(Float percentualDescontoTitulo) {
		this.percentualDescontoTitulo = percentualDescontoTitulo;
	}

	public String getDataDescontoTitulo() {
		return dataDescontoTitulo;
	}

	public void setDataDescontoTitulo(String dataDescontoTitulo) {
		this.dataDescontoTitulo = dataDescontoTitulo;
	}

	public Float getValorDescontoTitulo() {
		return valorDescontoTitulo;
	}

	public void setValorDescontoTitulo(Float valorDescontoTitulo) {
		this.valorDescontoTitulo = valorDescontoTitulo;
	}

	public BigDecimal getCodigoDescontoTitulo() {
		return codigoDescontoTitulo;
	}

	public void setCodigoDescontoTitulo(BigDecimal codigoDescontoTitulo) {
		this.codigoDescontoTitulo = codigoDescontoTitulo;
	}

	public Float getPercentualSegundoDescontoTitulo() {
		return percentualSegundoDescontoTitulo;
	}

	public void setPercentualSegundoDescontoTitulo(Float percentualSegundoDescontoTitulo) {
		this.percentualSegundoDescontoTitulo = percentualSegundoDescontoTitulo;
	}

	public String getDataSegundoDescontoTitulo() {
		return dataSegundoDescontoTitulo;
	}

	public void setDataSegundoDescontoTitulo(String dataSegundoDescontoTitulo) {
		this.dataSegundoDescontoTitulo = dataSegundoDescontoTitulo;
	}

	public Float getValorSegundoDescontoTitulo() {
		return valorSegundoDescontoTitulo;
	}

	public void setValorSegundoDescontoTitulo(Float valorSegundoDescontoTitulo) {
		this.valorSegundoDescontoTitulo = valorSegundoDescontoTitulo;
	}

	public BigDecimal getCodigoSegundoDescontoTitulo() {
		return codigoSegundoDescontoTitulo;
	}

	public void setCodigoSegundoDescontoTitulo(BigDecimal codigoSegundoDescontoTitulo) {
		this.codigoSegundoDescontoTitulo = codigoSegundoDescontoTitulo;
	}

	public Float getPercentualTerceiroDescontoTitulo() {
		return percentualTerceiroDescontoTitulo;
	}

	public void setPercentualTerceiroDescontoTitulo(Float percentualTerceiroDescontoTitulo) {
		this.percentualTerceiroDescontoTitulo = percentualTerceiroDescontoTitulo;
	}

	public String getDataTerceiroDescontoTitulo() {
		return dataTerceiroDescontoTitulo;
	}

	public void setDataTerceiroDescontoTitulo(String dataTerceiroDescontoTitulo) {
		this.dataTerceiroDescontoTitulo = dataTerceiroDescontoTitulo;
	}

	public Float getValorTerceiroDescontoTitulo() {
		return valorTerceiroDescontoTitulo;
	}

	public void setValorTerceiroDescontoTitulo(Float valorTerceiroDescontoTitulo) {
		this.valorTerceiroDescontoTitulo = valorTerceiroDescontoTitulo;
	}

	public BigDecimal getCodigoTerceiroDescontoTitulo() {
		return codigoTerceiroDescontoTitulo;
	}

	public void setCodigoTerceiroDescontoTitulo(BigDecimal codigoTerceiroDescontoTitulo) {
		this.codigoTerceiroDescontoTitulo = codigoTerceiroDescontoTitulo;
	}

	public String getDataMultaTitulo() {
		return dataMultaTitulo;
	}

	public void setDataMultaTitulo(String dataMultaTitulo) {
		this.dataMultaTitulo = dataMultaTitulo;
	}

	public BigDecimal getNumeroCarteiraCobranca() {
		return numeroCarteiraCobranca;
	}

	public void setNumeroCarteiraCobranca(BigDecimal numeroCarteiraCobranca) {
		this.numeroCarteiraCobranca = numeroCarteiraCobranca;
	}

	public BigDecimal getNumeroVariacaoCarteiraCobranca() {
		return numeroVariacaoCarteiraCobranca;
	}

	public void setNumeroVariacaoCarteiraCobranca(BigDecimal numeroVariacaoCarteiraCobranca) {
		this.numeroVariacaoCarteiraCobranca = numeroVariacaoCarteiraCobranca;
	}

	public BigDecimal getQuantidadeDiaProtesto() {
		return quantidadeDiaProtesto;
	}

	public void setQuantidadeDiaProtesto(BigDecimal quantidadeDiaProtesto) {
		this.quantidadeDiaProtesto = quantidadeDiaProtesto;
	}

	public BigDecimal getQuantidadeDiaPrazoLimiteRecebimento() {
		return quantidadeDiaPrazoLimiteRecebimento;
	}

	public void setQuantidadeDiaPrazoLimiteRecebimento(BigDecimal quantidadeDiaPrazoLimiteRecebimento) {
		this.quantidadeDiaPrazoLimiteRecebimento = quantidadeDiaPrazoLimiteRecebimento;
	}

	public String getDataLimiteRecebimentoTitulo() {
		return dataLimiteRecebimentoTitulo;
	}

	public void setDataLimiteRecebimentoTitulo(String dataLimiteRecebimentoTitulo) {
		this.dataLimiteRecebimentoTitulo = dataLimiteRecebimentoTitulo;
	}

	public String getIndicadorPermissaoRecebimentoParcial() {
		return indicadorPermissaoRecebimentoParcial;
	}

	public void setIndicadorPermissaoRecebimentoParcial(String indicadorPermissaoRecebimentoParcial) {
		this.indicadorPermissaoRecebimentoParcial = indicadorPermissaoRecebimentoParcial;
	}

	public String getTextoCodigoBarrasTituloCobranca() {
		return textoCodigoBarrasTituloCobranca;
	}

	public void setTextoCodigoBarrasTituloCobranca(String textoCodigoBarrasTituloCobranca) {
		this.textoCodigoBarrasTituloCobranca = textoCodigoBarrasTituloCobranca;
	}

	public BigDecimal getCodigoOcorrenciaCartorio() {
		return codigoOcorrenciaCartorio;
	}

	public void setCodigoOcorrenciaCartorio(BigDecimal codigoOcorrenciaCartorio) {
		this.codigoOcorrenciaCartorio = codigoOcorrenciaCartorio;
	}

	public Float getValorImpostoSobreOprFinanceirasRecebidoTitulo() {
		return valorImpostoSobreOprFinanceirasRecebidoTitulo;
	}

	public void setValorImpostoSobreOprFinanceirasRecebidoTitulo(Float valorImpostoSobreOprFinanceirasRecebidoTitulo) {
		this.valorImpostoSobreOprFinanceirasRecebidoTitulo = valorImpostoSobreOprFinanceirasRecebidoTitulo;
	}

	public Float getValorAbatimentoTotal() {
		return valorAbatimentoTotal;
	}

	public void setValorAbatimentoTotal(Float valorAbatimentoTotal) {
		this.valorAbatimentoTotal = valorAbatimentoTotal;
	}

	public Float getValorJuroMoraRecebido() {
		return valorJuroMoraRecebido;
	}

	public void setValorJuroMoraRecebido(Float valorJuroMoraRecebido) {
		this.valorJuroMoraRecebido = valorJuroMoraRecebido;
	}

	public Float getValorDescontoUtilizado() {
		return valorDescontoUtilizado;
	}

	public void setValorDescontoUtilizado(Float valorDescontoUtilizado) {
		this.valorDescontoUtilizado = valorDescontoUtilizado;
	}

	public Float getValorPagoSacado() {
		return valorPagoSacado;
	}

	public void setValorPagoSacado(Float valorPagoSacado) {
		this.valorPagoSacado = valorPagoSacado;
	}

	public Float getValorCreditoCedente() {
		return valorCreditoCedente;
	}

	public void setValorCreditoCedente(Float valorCreditoCedente) {
		this.valorCreditoCedente = valorCreditoCedente;
	}

	public BigDecimal getCodigoTipoLiquidacao() {
		return codigoTipoLiquidacao;
	}

	public void setCodigoTipoLiquidacao(BigDecimal codigoTipoLiquidacao) {
		this.codigoTipoLiquidacao = codigoTipoLiquidacao;
	}

	public String getDataCreditoLiquidacao() {
		return dataCreditoLiquidacao;
	}

	public void setDataCreditoLiquidacao(String dataCreditoLiquidacao) {
		this.dataCreditoLiquidacao = dataCreditoLiquidacao;
	}

	public String getDataRecebimentoTitulo() {
		return dataRecebimentoTitulo;
	}

	public void setDataRecebimentoTitulo(String dataRecebimentoTitulo) {
		this.dataRecebimentoTitulo = dataRecebimentoTitulo;
	}

	public BigDecimal getCodigoPrefixoDependenciaRecebedor() {
		return codigoPrefixoDependenciaRecebedor;
	}

	public void setCodigoPrefixoDependenciaRecebedor(BigDecimal codigoPrefixoDependenciaRecebedor) {
		this.codigoPrefixoDependenciaRecebedor = codigoPrefixoDependenciaRecebedor;
	}

	public BigDecimal getCodigoNaturezaRecebimento() {
		return codigoNaturezaRecebimento;
	}

	public void setCodigoNaturezaRecebimento(BigDecimal codigoNaturezaRecebimento) {
		this.codigoNaturezaRecebimento = codigoNaturezaRecebimento;
	}

	public String getNumeroIdentidadeSacadoTituloCobranca() {
		return numeroIdentidadeSacadoTituloCobranca;
	}

	public void setNumeroIdentidadeSacadoTituloCobranca(String numeroIdentidadeSacadoTituloCobranca) {
		this.numeroIdentidadeSacadoTituloCobranca = numeroIdentidadeSacadoTituloCobranca;
	}

	public String getCodigoResponsavelAtualizacao() {
		return codigoResponsavelAtualizacao;
	}

	public void setCodigoResponsavelAtualizacao(String codigoResponsavelAtualizacao) {
		this.codigoResponsavelAtualizacao = codigoResponsavelAtualizacao;
	}

	public BigDecimal getCodigoTipoBaixaTitulo() {
		return codigoTipoBaixaTitulo;
	}

	public void setCodigoTipoBaixaTitulo(BigDecimal codigoTipoBaixaTitulo) {
		this.codigoTipoBaixaTitulo = codigoTipoBaixaTitulo;
	}

	public Float getValorMultaRecebido() {
		return valorMultaRecebido;
	}

	public void setValorMultaRecebido(Float valorMultaRecebido) {
		this.valorMultaRecebido = valorMultaRecebido;
	}

	public Float getValorReajuste() {
		return valorReajuste;
	}

	public void setValorReajuste(Float valorReajuste) {
		this.valorReajuste = valorReajuste;
	}

	public Float getValorOutroRecebido() {
		return valorOutroRecebido;
	}

	public void setValorOutroRecebido(Float valorOutroRecebido) {
		this.valorOutroRecebido = valorOutroRecebido;
	}

	public Float getCodigoIndicadorEconomicoUtilizadoInadimplencia() {
		return codigoIndicadorEconomicoUtilizadoInadimplencia;
	}

	public void setCodigoIndicadorEconomicoUtilizadoInadimplencia(
			Float codigoIndicadorEconomicoUtilizadoInadimplencia) {
		this.codigoIndicadorEconomicoUtilizadoInadimplencia = codigoIndicadorEconomicoUtilizadoInadimplencia;
	}

	/**
	 * Código para identificação da forma de pagamento e do canal onde foi pago o
	 * boleto. Composto por 3 dígitos. O primeiro dígito é: 1 Espécie 2 Débito em
	 * conta 3 Cartão de crédito 4 Cheque Os dois últimos: 01 Agencias - Postos
	 * tradicionais 02 Terminal de Auto-atendimento 03 Internet (home / office
	 * banking) 05 Correspondente bancário 06 Central de atendimento(Call Center) 07
	 * Arquivo Eletrônico 08 DDA 61 Pix
	 * 
	 * @return codigoCanalPagamento
	 **/

}
