/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * Objeto de resposta da baixa de boletos.
 */
public class RespostaBaixaBoleto {
  private String numeroContratoCobranca = null;

  private String dataBaixa = null;

  private String horarioBaixa = null;

  public RespostaBaixaBoleto numeroContratoCobranca(String numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

   /**
   * Número do contrato de cobrança do boleto bancário.
   * @return numeroContratoCobranca
  **/
  public String getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }

  public void setNumeroContratoCobranca(String numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }

  public RespostaBaixaBoleto dataBaixa(String dataBaixa) {
    this.dataBaixa = dataBaixa;
    return this;
  }

   /**
   * Data do pedido de baixa do boleto bancário.
   * @return dataBaixa
  **/
  public String getDataBaixa() {
    return dataBaixa;
  }

  public void setDataBaixa(String dataBaixa) {
    this.dataBaixa = dataBaixa;
  }

  public RespostaBaixaBoleto horarioBaixa(String horarioBaixa) {
    this.horarioBaixa = horarioBaixa;
    return this;
  }

   /**
   * Horário do pedido de baixa do boleto bancário.HH:mm:ss
   * @return horarioBaixa
  **/
  public String getHorarioBaixa() {
    return horarioBaixa;
  }

  public void setHorarioBaixa(String horarioBaixa) {
    this.horarioBaixa = horarioBaixa;
  }

}
