/*
 * Cobranças API
 * API para gerenciar os serviços de cobranças de cliente do Banco do Brasil S.A.
 *
 * OpenAPI spec version: 2.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.bankslip.api.bb;

/**
 * RespostaListaBoletosBoletos
 */


public class RespostaListaBoletosBoletos {
  private String numeroBoletoBB = null;

  private String estadoTituloCobranca = null;

  private String dataRegistro = null;

  private String dataVencimento = null;

  private String dataMovimento = null;

  private Float valorOriginal = null;

  private Float valorAtual = null;

  private Float valorPago = null;

  private Integer contrato = null;

  private Integer carteiraConvenio = null;

  private Integer variacaoCarteiraConvenio = null;

  private Integer codigoEstadoTituloCobranca = null;

  private String dataCredito = null;

  public RespostaListaBoletosBoletos numeroBoletoBB(String numeroBoletoBB) {
    this.numeroBoletoBB = numeroBoletoBB;
    return this;
  }

   /**
   * Número de identificação do boleto (correspondente ao NOSSO NÚMERO), no formato STRING, com 20 dígitos. Corresponde aos campos numeroTituloCliente (requisição do registro do boleto), numero (resposta do registro) e id (detalhamento do boleto).
   * @return numeroBoletoBB
  **/
  public String getNumeroBoletoBB() {
    return numeroBoletoBB;
  }

  public void setNumeroBoletoBB(String numeroBoletoBB) {
    this.numeroBoletoBB = numeroBoletoBB;
  }

  public RespostaListaBoletosBoletos estadoTituloCobranca(String estadoTituloCobranca) {
    this.estadoTituloCobranca = estadoTituloCobranca;
    return this;
  }

   /**
   * Texto da situação atual do boleto.  Possíveis valores de retorno: - NORMAL   - MOVIMENTO CARTORIO - EM CARTORIO - TITULO COM OCORRENCIA DE CARTORIO - PROTESTADO ELETRONICO  - LIQUIDADO    - BAIXADO  - TITULO COM PENDENCIA DE CARTORIO  - TITULO PROTESTADO MANUAL
   * @return estadoTituloCobranca
  **/
  public String getEstadoTituloCobranca() {
    return estadoTituloCobranca;
  }

  public void setEstadoTituloCobranca(String estadoTituloCobranca) {
    this.estadoTituloCobranca = estadoTituloCobranca;
  }

  public RespostaListaBoletosBoletos dataRegistro(String dataRegistro) {
    this.dataRegistro = dataRegistro;
    return this;
  }

   /**
   * Data de registro do boleto. 
   * @return dataRegistro
  **/
  public String getDataRegistro() {
    return dataRegistro;
  }

  public void setDataRegistro(String dataRegistro) {
    this.dataRegistro = dataRegistro;
  }

  public RespostaListaBoletosBoletos dataVencimento(String dataVencimento) {
    this.dataVencimento = dataVencimento;
    return this;
  }

   /**
   * Data de vencimento do boleto 
   * @return dataVencimento
  **/
  public String getDataVencimento() {
    return dataVencimento;
  }

  public void setDataVencimento(String dataVencimento) {
    this.dataVencimento = dataVencimento;
  }

  public RespostaListaBoletosBoletos dataMovimento(String dataMovimento) {
    this.dataMovimento = dataMovimento;
    return this;
  }

   /**
   * Data do evento que baixou, protestou ou liquidou o boleto. No caso de títulos vigentes, ainda que vencidos, equivale a data de registro. 
   * @return dataMovimento
  **/
  public String getDataMovimento() {
    return dataMovimento;
  }

  public void setDataMovimento(String dataMovimento) {
    this.dataMovimento = dataMovimento;
  }

  public RespostaListaBoletosBoletos valorOriginal(Float valorOriginal) {
    this.valorOriginal = valorOriginal;
    return this;
  }

   /**
   * Valor do boleto no registro. 
   * @return valorOriginal
  **/
  public Float getValorOriginal() {
    return valorOriginal;
  }

  public void setValorOriginal(Float valorOriginal) {
    this.valorOriginal = valorOriginal;
  }

  public RespostaListaBoletosBoletos valorAtual(Float valorAtual) {
    this.valorAtual = valorAtual;
    return this;
  }

   /**
   * Valor atualizado do boleto. 
   * @return valorAtual
  **/
  public Float getValorAtual() {
    return valorAtual;
  }

  public void setValorAtual(Float valorAtual) {
    this.valorAtual = valorAtual;
  }

  public RespostaListaBoletosBoletos valorPago(Float valorPago) {
    this.valorPago = valorPago;
    return this;
  }

   /**
   * Valor pago pelo pagador/sacado. 
   * @return valorPago
  **/
  public Float getValorPago() {
    return valorPago;
  }

  public void setValorPago(Float valorPago) {
    this.valorPago = valorPago;
  }

  public RespostaListaBoletosBoletos contrato(Integer contrato) {
    this.contrato = contrato;
    return this;
  }

   /**
   * Código do contrato entre o Banco do Brasil e a empresa cliente.
   * @return contrato
  **/
  public Integer getContrato() {
    return contrato;
  }

  public void setContrato(Integer contrato) {
    this.contrato = contrato;
  }

  public RespostaListaBoletosBoletos carteiraConvenio(Integer carteiraConvenio) {
    this.carteiraConvenio = carteiraConvenio;
    return this;
  }

   /**
   * Número da carteira do convênio de cobrança. 
   * @return carteiraConvenio
  **/
  public Integer getCarteiraConvenio() {
    return carteiraConvenio;
  }

  public void setCarteiraConvenio(Integer carteiraConvenio) {
    this.carteiraConvenio = carteiraConvenio;
  }

  public RespostaListaBoletosBoletos variacaoCarteiraConvenio(Integer variacaoCarteiraConvenio) {
    this.variacaoCarteiraConvenio = variacaoCarteiraConvenio;
    return this;
  }

   /**
   * Número da variação da carteira do convênio de cobrança.
   * @return variacaoCarteiraConvenio
  **/
  public Integer getVariacaoCarteiraConvenio() {
    return variacaoCarteiraConvenio;
  }

  public void setVariacaoCarteiraConvenio(Integer variacaoCarteiraConvenio) {
    this.variacaoCarteiraConvenio = variacaoCarteiraConvenio;
  }

  public RespostaListaBoletosBoletos codigoEstadoTituloCobranca(Integer codigoEstadoTituloCobranca) {
    this.codigoEstadoTituloCobranca = codigoEstadoTituloCobranca;
    return this;
  }

   /**
   * Código da situação atual do boleto:  Domínios: 01 - NORMAL   02 - MOVIMENTO CARTORIO 03 - EM CARTORIO 04 - TITULO COM OCORRENCIA DE CARTORIO 05 - PROTESTADO ELETRONICO  06 - LIQUIDADO    07 - BAIXADO  08 - TITULO COM PENDENCIA DE CARTORIO  09 - TITULO PROTESTADO MANUAL
   * @return codigoEstadoTituloCobranca
  **/
  public Integer getCodigoEstadoTituloCobranca() {
    return codigoEstadoTituloCobranca;
  }

  public void setCodigoEstadoTituloCobranca(Integer codigoEstadoTituloCobranca) {
    this.codigoEstadoTituloCobranca = codigoEstadoTituloCobranca;
  }

  public RespostaListaBoletosBoletos dataCredito(String dataCredito) {
    this.dataCredito = dataCredito;
    return this;
  }

   /**
   * Data do crédito dos valores ao beneficiário
   * @return dataCredito
  **/
  public String getDataCredito() {
    return dataCredito;
  }

  public void setDataCredito(String dataCredito) {
    this.dataCredito = dataCredito;
  }

}
