/*
 * Token
 * Serviço de geração de token, para acesso a diversas APIs dos Correios. <br></br> <b>Geração do token</b> <ul>     <li>Para solicitar um token é necessário fazer uma requisição com <b>'Authorization: Basic'</b>, passando o usuário (Meu Correios) e senha (código de acesso).</li> </ul> <b>Expiração do token</b> <ul>     <li>O token obtido tem uma data de expiração no atributo <b>'expiraEm'</b>, com isso o mesmo token pode ser utilizado até a data de expiração.</li>     <li>Recomendamos que solicite um novo token próximo da data de expiração, alguns minutos antes do token expirar.</li>     <li>Será devolvido um <b>NOVO</b> token quando:</li>     <ul>         <li>O token estiver expirado;</li>         <li>Caso haja alguma alteração nas permissões de acesso;</li>         <li>Dentro da tolerância de até <b>30 minutos</b> antes da data de expiração.</li>         <li>Nos demais casos, será devolvido um token já solicitado.</li>     </ul> </ul> <b>Limite de solicitações</b> <ul>     <li>A API 'token' tem um limite de  <b>3</b> solitações por segundo.</li>     <li>Caso ultrapasse esse limite é disparado status HTTP 429 - Too Many Requests.</li>     <li>Para evitar receber o status HTTP 429, sempre verifique a data de expiração do token antes de enviar uma nova solicitação.</li> </ul>
 *
 * OpenAPI spec version: 1.11.29
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.correios.api.token;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonAlias;


public class Token implements Serializable{

	private static final long serialVersionUID = 316187157075457602L;

	private String ambiente = null;

	private String id = null;

	private String ip = null;

	private String perfil = null;

	private String cnpj = null;

	private Long pjInternacional = null;

	private String cpf = null;

	private String cie = null;
	
	@JsonAlias("cartaoPostagem")
	private CartaoPostagem cartaoPostagem = null;

	private Contrato contrato = null;

	private List<Integer> api = null;

	private List<String> paths = null;

	private Timestamp emissao = null;

	private Timestamp expiraEm = null;

	private String zoneOffset = null;

	private String token = null;


	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getPerfil() {
		return perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	public String getAmbiente() {
		return ambiente;
	}

	public void setAmbiente(String ambiente) {
		this.ambiente = ambiente;
	}

	public String getCnpj() {
		return cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	public Long getPjInternacional() {
		return pjInternacional;
	}

	public void setPjInternacional(Long pjInternacional) {
		this.pjInternacional = pjInternacional;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getCie() {
		return cie;
	}

	public void setCie(String cie) {
		this.cie = cie;
	}

	public CartaoPostagem getCartaoPostagem() {
		return cartaoPostagem;
	}

	public void setCartaoPostagem(CartaoPostagem cartaoPostagem) {
		this.cartaoPostagem = cartaoPostagem;
	}

	public Contrato getContrato() {
		return contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	public List<Integer> getApi() {
		return api;
	}

	public void setApi(List<Integer> api) {
		this.api = api;
	}

	public List<String> getPaths() {
		return paths;
	}

	public void setPaths(List<String> paths) {
		this.paths = paths;
	}

	public Timestamp getEmissao() {
		return emissao;
	}

	public void setEmissao(Timestamp emissao) {
		this.emissao = emissao;
	}

	public Timestamp getExpiraEm() {
		return expiraEm;
	}

	public void setExpiraEm(Timestamp expiraEm) {
		this.expiraEm = expiraEm;
	}

	public String getZoneOffset() {
		return zoneOffset;
	}

	public void setZoneOffset(String zoneOffset) {
		this.zoneOffset = zoneOffset;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
