SET SQLBLANKLINES ON
SET DEFINE OFF

CREATE OR REPLACE FUNCTION "ADEMPIERE"."UNACCENT_UPPER" (P_STRING VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
	RETURN UPPER(UTL_RAW.CAST_TO_VARCHAR2((NLSSORT(P_STRING, 'nls_sort=binary_ai'))));
END;
/

-- 22/06/2018 15h53min3s BRT
SELECT Register_Migration_Script ('201806221450_IDEMPIERE-3734_UnaccentSearch.sql') FROM DUAL
;