source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               lib/,\
               lib/converter-jackson.jar,\
               lib/fixedformat4j.jar,\
               lib/kotlin-stdlib.jar,\
               lib/logging-interceptor.jar,\
               lib/okhttp3.jar,\
               lib/okio-jvm.jar,\
               lib/retrofit.jar
