<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.kenos.idempiere</groupId>
		<artifactId>org.kenos.idempiere.lbr</artifactId>
		<version>6.2.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<artifactId>org.kenos.idempiere.lbr.correios</artifactId>
	<packaging>eclipse-plugin</packaging>
	<repositories>
		<repository>
			<id>github-maven-repo</id>
			<url>https://raw.githubusercontent.com/KenosSGI/maven-repository/master/repository/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<artifactItems>
								<!-- https://mvnrepository.com/artifact/com.ancientprogramming.fixedformat4j/fixedformat4j -->
								<artifactItem>
									<groupId>org.kenos</groupId>
									<artifactId>fixedformat4j</artifactId>
									<version>1.3.5</version>
									<destFileName>fixedformat4j.jar</destFileName>
								</artifactItem>
								<artifactItem>
									<groupId>com.squareup.okhttp3</groupId>
									<artifactId>okhttp</artifactId>
									<version>${okhttp-version}</version>
									<destFileName>okhttp3.jar</destFileName>
								</artifactItem>
								<artifactItem>
									<groupId>com.squareup.okhttp3</groupId>
									<artifactId>logging-interceptor</artifactId>
									<version>${okhttp-version}</version>
									<destFileName>logging-interceptor.jar</destFileName>
								</artifactItem>
								<artifactItem>
									<groupId>com.squareup.retrofit2</groupId>
									<artifactId>retrofit</artifactId>
									<version>${retrofit-version}</version>
									<destFileName>retrofit.jar</destFileName>
								</artifactItem>
								<artifactItem>
									<groupId>com.squareup.retrofit2</groupId>
									<artifactId>converter-jackson</artifactId>
									<version>${retrofit-version}</version>
									<destFileName>converter-jackson.jar</destFileName>
								</artifactItem>
								<!-- https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib -->
								<artifactItem>
									<groupId>org.jetbrains.kotlin</groupId>
									<artifactId>kotlin-stdlib</artifactId>
									<version>${stdlib-version}</version>
									<destFileName>kotlin-stdlib.jar</destFileName>
								</artifactItem>
								<!-- https://mvnrepository.com/artifact/com.squareup.okio/okio-jvm -->
								<artifactItem>
									<groupId>com.squareup.okio</groupId>
									<artifactId>okio-jvm</artifactId>
									<version>${okio-jvm-version}</version>
									<destFileName>okio-jvm.jar</destFileName>
								</artifactItem>
							</artifactItems>
							<outputDirectory>lib</outputDirectory>
							<stripVersion>true</stripVersion>
							<overWriteReleases>true</overWriteReleases>
							<overWriteSnapshots>true</overWriteSnapshots>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>