/*
 * Preço
 * Preço
 *
 * OpenAPI spec version: 3.10.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.correios.api.preco;

import java.util.List;

public class BeneficioResponse {

	private String codigo = null;

	private String tipoBeneficio = null;

	private String tipo = null;

	private String abrangencia = null;

	private String coPacote = null;

	private String noPacote = null;

	private String incondicional = null;

	private List<CriterioAtendidoResponse> criterio = null;

	private String vlBaseCalculo = null;

	private String percentual = null;

	private String valor = null;

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getTipoBeneficio() {
		return tipoBeneficio;
	}

	public void setTipoBeneficio(String tipoBeneficio) {
		this.tipoBeneficio = tipoBeneficio;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getAbrangencia() {
		return abrangencia;
	}

	public void setAbrangencia(String abrangencia) {
		this.abrangencia = abrangencia;
	}

	public String getCoPacote() {
		return coPacote;
	}

	public void setCoPacote(String coPacote) {
		this.coPacote = coPacote;
	}

	public String getNoPacote() {
		return noPacote;
	}

	public void setNoPacote(String noPacote) {
		this.noPacote = noPacote;
	}

	public String getIncondicional() {
		return incondicional;
	}

	public void setIncondicional(String incondicional) {
		this.incondicional = incondicional;
	}

	public List<CriterioAtendidoResponse> getCriterio() {
		return criterio;
	}

	public void setCriterio(List<CriterioAtendidoResponse> criterio) {
		this.criterio = criterio;
	}

	public String getVlBaseCalculo() {
		return vlBaseCalculo;
	}

	public void setVlBaseCalculo(String vlBaseCalculo) {
		this.vlBaseCalculo = vlBaseCalculo;
	}

	public String getPercentual() {
		return percentual;
	}

	public void setPercentual(String percentual) {
		this.percentual = percentual;
	}

	public String getValor() {
		return valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
