/*
 * Preço
 * Preço
 *
 * OpenAPI spec version: 3.10.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.correios.api.preco;

public class CriterioAtendidoResponse {
	// ("nuCriterio")
	private String nuCriterio = null;

	// ("noCriterio")
	private String noCriterio = null;

	// ("atendido")
	private String atendido = null;

	public String getNuCriterio() {
		return nuCriterio;
	}

	public void setNuCriterio(String nuCriterio) {
		this.nuCriterio = nuCriterio;
	}

	public String getNoCriterio() {
		return noCriterio;
	}

	public void setNoCriterio(String noCriterio) {
		this.noCriterio = noCriterio;
	}

	public String getAtendido() {
		return atendido;
	}

	public void setAtendido(String atendido) {
		this.atendido = atendido;
	}

	public String getPeNegociado() {
		return peNegociado;
	}

	public void setPeNegociado(String peNegociado) {
		this.peNegociado = peNegociado;
	}

	public String getPeConcedido() {
		return peConcedido;
	}

	public void setPeConcedido(String peConcedido) {
		this.peConcedido = peConcedido;
	}

//("peNegociado")
	private String peNegociado = null;

	// ("peConcedido")
	private String peConcedido = null;

}
