/*
 * Preço
 * Preço
 *
 * OpenAPI spec version: 3.10.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.correios.api.preco;

import java.util.List;

public class LotePrecoInternacionalParam {
	private String idLote = null;

	private List<PrecoInternacionalParam> parametrosProduto = null;

	public String getIdLote() {
		return idLote;
	}

	public void setIdLote(String idLote) {
		this.idLote = idLote;
	}

	public List<PrecoInternacionalParam> getParametrosProduto() {
		return parametrosProduto;
	}

	public void setParametrosProduto(List<PrecoInternacionalParam> parametrosProduto) {
		this.parametrosProduto = parametrosProduto;
	}
	
	

}
