/*
 * Preço
 * Preço
 *
 * OpenAPI spec version: 3.10.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.correios.api.preco;

public class PrecoServicoAdicional {
	
	private String coServAdicional = null;

	private String tpServAdicional = null;

	private String pcServicoAdicional = null;

	public String getCoServAdicional() {
		return coServAdicional;
	}

	public void setCoServAdicional(String coServAdicional) {
		this.coServAdicional = coServAdicional;
	}

	public String getTpServAdicional() {
		return tpServAdicional;
	}

	public void setTpServAdicional(String tpServAdicional) {
		this.tpServAdicional = tpServAdicional;
	}

	public String getPcServicoAdicional() {
		return pcServicoAdicional;
	}

	public void setPcServicoAdicional(String pcServicoAdicional) {
		this.pcServicoAdicional = pcServicoAdicional;
	}

	
}
