/*
 * Preço
 * Preço
 *
 * OpenAPI spec version: 3.10.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.correios.api.preco;

import java.sql.Timestamp;

public class ServicoAdicionalExcludenteResponse {
	
	private String coExcludente = null;

	private Timestamp dtIniVigencia = null;

	private Timestamp dtFimVigencia = null;

	public String getCoExcludente() {
		return coExcludente;
	}

	public void setCoExcludente(String coExcludente) {
		this.coExcludente = coExcludente;
	}

	public Timestamp getDtIniVigencia() {
		return dtIniVigencia;
	}

	public void setDtIniVigencia(Timestamp dtIniVigencia) {
		this.dtIniVigencia = dtIniVigencia;
	}

	public Timestamp getDtFimVigencia() {
		return dtFimVigencia;
	}

	public void setDtFimVigencia(Timestamp dtFimVigencia) {
		this.dtFimVigencia = dtFimVigencia;
	}

}
