/*
 * Preço
 * Preço
 *
 * OpenAPI spec version: 3.10.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.correios.api.preco;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

public class ServicoAdicionalResponse {
	
	private String codigo = null;

	private String nome = null;

	private String sigla = null;

	private String sgPais = null;

	private BigDecimal preco = null;

	private String tipo = null;

	private String coIndicador = null;

	private String noIndicador = null;

	private String sgIndicador = null;

	private BigDecimal vlMinDeclarado = null;

	private BigDecimal vlMaxDeclarado = null;

	private String mensagem = null;

	private List<ServicoAdicionalRequeridoResponse> requeridos = null;

	private List<ServicoAdicionalExcludenteResponse> excludentes = null;

	private Timestamp dtIniVigencia = null;

	private Timestamp dtFimVigencia = null;

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSigla() {
		return sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	public String getSgPais() {
		return sgPais;
	}

	public void setSgPais(String sgPais) {
		this.sgPais = sgPais;
	}

	public BigDecimal getPreco() {
		return preco;
	}

	public void setPreco(BigDecimal preco) {
		this.preco = preco;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getCoIndicador() {
		return coIndicador;
	}

	public void setCoIndicador(String coIndicador) {
		this.coIndicador = coIndicador;
	}

	public String getNoIndicador() {
		return noIndicador;
	}

	public void setNoIndicador(String noIndicador) {
		this.noIndicador = noIndicador;
	}

	public String getSgIndicador() {
		return sgIndicador;
	}

	public void setSgIndicador(String sgIndicador) {
		this.sgIndicador = sgIndicador;
	}

	public BigDecimal getVlMinDeclarado() {
		return vlMinDeclarado;
	}

	public void setVlMinDeclarado(BigDecimal vlMinDeclarado) {
		this.vlMinDeclarado = vlMinDeclarado;
	}

	public BigDecimal getVlMaxDeclarado() {
		return vlMaxDeclarado;
	}

	public void setVlMaxDeclarado(BigDecimal vlMaxDeclarado) {
		this.vlMaxDeclarado = vlMaxDeclarado;
	}

	public String getMensagem() {
		return mensagem;
	}

	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}

	public List<ServicoAdicionalRequeridoResponse> getRequeridos() {
		return requeridos;
	}

	public void setRequeridos(List<ServicoAdicionalRequeridoResponse> requeridos) {
		this.requeridos = requeridos;
	}

	public List<ServicoAdicionalExcludenteResponse> getExcludentes() {
		return excludentes;
	}

	public void setExcludentes(List<ServicoAdicionalExcludenteResponse> excludentes) {
		this.excludentes = excludentes;
	}

	public Timestamp getDtIniVigencia() {
		return dtIniVigencia;
	}

	public void setDtIniVigencia(Timestamp dtIniVigencia) {
		this.dtIniVigencia = dtIniVigencia;
	}

	public Timestamp getDtFimVigencia() {
		return dtFimVigencia;
	}

	public void setDtFimVigencia(Timestamp dtFimVigencia) {
		this.dtFimVigencia = dtFimVigencia;
	}

}
