/*
 * Preço
 * Preço
 *
 * OpenAPI spec version: 3.10.3.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.kenos.idempiere.lbr.correios.api.preco;

public class TaxaExtraResponse {

	private String codigo = null;

	private String tipo = null;

	private String vlTaxa = null;

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getVlTaxa() {
		return vlTaxa;
	}

	public void setVlTaxa(String vlTaxa) {
		this.vlTaxa = vlTaxa;
	}

}
