/*
Script generated by Aqua Data Studio 6.5.7 on Jan-09-2008 11:21:53 AM
Database: adempiere
Schema: adempiere
Objects: TABLE
*/
CREATE TABLE adempiere.lbr_bank ( 
	lbr_bank_id         	number(10,0) NOT NULL,
	ad_org_id           	number(10,0) NOT NULL,
	ad_client_id        	number(10,0) NOT NULL,
	isactive            	char(1) DEFAULT 'Y' NOT NULL,
	created             	date NOT NULL,
	createdby           	number(10,0) NOT NULL,
	updated             	date NOT NULL,
	updatedby           	number(10,0) NOT NULL,
	routingno           	nvarchar2(20) NOT NULL,
	name                	nvarchar2(60) NOT NULL,
	description         	nvarchar2(255) NULL,
	lbr_jboletono       	nvarchar2(3) NULL,
	lbr_paymentlocation1	nvarchar2(60) NULL,
	lbr_paymentlocation2	nvarchar2(60) NULL 
	);

CREATE TABLE adempiere.lbr_bankinfo ( 
	lbr_bankinfo_id	number(10,0) NOT NULL,
	ad_org_id      	number(10,0) NOT NULL,
	ad_client_id   	number(10,0) NOT NULL,
	isactive       	char(1) DEFAULT 'Y' NOT NULL,
	created        	date NOT NULL,
	createdby      	number(10,0) NOT NULL,
	updated        	date NOT NULL,
	updatedby      	number(10,0) NOT NULL,
	lbr_bank_id    	number(10,0) NOT NULL,
	lbr_occurtype  	nvarchar2(1) NOT NULL,
	description    	nvarchar2(255) NULL,
	lbr_occurno    	nvarchar2(5) NOT NULL 
	);

CREATE TABLE adempiere.lbr_boleto ( 
	lbr_boleto_id       	number(10,0) NOT NULL,
	ad_org_id           	number(10,0) NOT NULL,
	ad_client_id        	number(10,0) NOT NULL,
	isactive            	char(1) DEFAULT 'Y' NOT NULL,
	created             	date NOT NULL,
	createdby           	number(10,0) NOT NULL,
	updated             	date NOT NULL,
	updatedby           	number(10,0) NOT NULL,
	c_invoice_id        	number(10,0) NOT NULL,
	address1            	nvarchar2(60) NULL,
	address2            	nvarchar2(60) NULL,
	address3            	nvarchar2(60) NULL,
	address4            	nvarchar2(60) NULL,
	city                	nvarchar2(60) NULL,
	regionname          	nvarchar2(2) NULL,
	postal              	nvarchar2(10) NULL,
	accountno           	nvarchar2(20) NOT NULL,
	documentno          	nvarchar2(60) NOT NULL,
	routingno           	nvarchar2(20) NOT NULL,
	lbr_docdate         	date NOT NULL,
	lbr_cessionary      	nvarchar2(200) NOT NULL,
	lbr_receivername    	nvarchar2(200) NOT NULL,
	lbr_bptypebr        	nvarchar2(2) NOT NULL,
	lbr_billkind        	nvarchar2(10) NULL,
	lbr_agencyno        	nvarchar2(10) NOT NULL,
	lbr_billfold        	nvarchar2(10) NOT NULL,
	lbr_clientcode      	nvarchar2(30) NULL,
	lbr_paymentlocation1	nvarchar2(60) NULL,
	lbr_paymentlocation2	nvarchar2(60) NULL,
	lbr_instruction1    	nvarchar2(60) NULL,
	lbr_instruction2    	nvarchar2(60) NULL,
	lbr_instruction3    	nvarchar2(60) NULL,
	lbr_iscancelled     	char(1) DEFAULT 'N' NOT NULL,
	c_bpartner_id       	number(10,0) NOT NULL,
	lbr_payscheduleno   	nvarchar2(2) NULL,
	grandtotal          	number NOT NULL,
	discountamt         	number NOT NULL,
	duedate             	date NOT NULL,
	discountdate        	date NOT NULL,
	lbr_jboletono       	nvarchar2(3) NOT NULL 
	);

CREATE TABLE adempiere.lbr_bpartnercategory ( 
	lbr_bpartnercategory_id	number(10,0) NOT NULL,
	ad_org_id              	number(10,0) NOT NULL,
	ad_client_id           	number(10,0) NOT NULL,
	isactive               	char(1) DEFAULT 'Y' NOT NULL,
	created                	date NOT NULL,
	createdby              	number(10,0) NOT NULL,
	updated                	date NOT NULL,
	updatedby              	number(10,0) NOT NULL,
	name                   	nvarchar2(60) NOT NULL,
	description            	nvarchar2(255) NULL 
	);

CREATE TABLE adempiere.lbr_cfop ( 
	lbr_cfop_id 	number(10,0) NOT NULL,
	ad_org_id   	number(10,0) NOT NULL,
	ad_client_id	number(10,0) NOT NULL,
	isactive    	char(1) DEFAULT 'Y' NOT NULL,
	created     	date NOT NULL,
	createdby   	number(10,0) NOT NULL,
	updated     	date NOT NULL,
	updatedby   	number(10,0) NULL,
	value       	nvarchar2(5) NOT NULL,
	description 	nvarchar2(255) NULL 
	);

CREATE TABLE adempiere.lbr_cfopline ( 
	lbr_cfopline_id        	number(10,0) NOT NULL,
	ad_org_id              	number(10,0) NOT NULL,
	ad_client_id           	number(10,0) NOT NULL,
	isactive               	char(1) DEFAULT 'Y' NOT NULL,
	created                	date NOT NULL,
	createdby              	number(10,0) NOT NULL,
	updated                	date NOT NULL,
	updatedby              	number(10,0) NOT NULL,
	lbr_cfop_id            	number(10,0) NOT NULL,
	lbr_destionationtype   	nvarchar2(1) NOT NULL,
	lbr_productcategory_id 	number(10,0) NULL,
	c_doctype_id           	number(10,0) NOT NULL,
	lbr_issubtributaria    	char(1) DEFAULT 'N' NOT NULL,
	lbr_transactiontype    	nvarchar2(3) NULL,
	lbr_ismanufactured     	char(1) DEFAULT 'N' NOT NULL,
	lbr_bpartnercategory_id	number(10,0) NULL,
	lbr_tax_id             	number(10,0) NULL 
	);

CREATE TABLE adempiere.lbr_cnab ( 
	lbr_cnab_id    	number(10,0) NOT NULL,
	ad_org_id      	number(10,0) NOT NULL,
	ad_client_id   	number(10,0) NOT NULL,
	isactive       	char(1) DEFAULT 'Y' NOT NULL,
	created        	date NOT NULL,
	createdby      	number(10,0) NOT NULL,
	updated        	date NOT NULL,
	updatedby      	number(10,0) NOT NULL,
	routingno      	nvarchar2(20) NOT NULL,
	lbr_iscancelled	char(1) DEFAULT 'N' NOT NULL,
	lbr_cnabfield1 	nvarchar2(60) NULL,
	lbr_cnabfield2 	nvarchar2(60) NULL,
	lbr_cnabfield3 	nvarchar2(60) NULL,
	lbr_cnabfield4 	nvarchar2(60) NULL,
	lbr_cnabfield5 	nvarchar2(60) NULL,
	lbr_cnabfield6 	nvarchar2(60) NULL,
	lbr_cnabfield7 	nvarchar2(60) NULL,
	lbr_cnabfield8 	nvarchar2(60) NULL,
	lbr_cnabfield9 	nvarchar2(60) NULL,
	lbr_cnabfield10	nvarchar2(60) NULL,
	lbr_cnabfield11	nvarchar2(60) NULL,
	lbr_cnabfield12	nvarchar2(60) NULL,
	lbr_cnabfield13	nvarchar2(60) NULL,
	lbr_cnabfield14	nvarchar2(60) NULL,
	lbr_cnabfield15	nvarchar2(60) NULL,
	lbr_cnabfield16	nvarchar2(60) NULL,
	lbr_cnabfield17	nvarchar2(60) NULL,
	lbr_cnabfield18	nvarchar2(60) NULL,
	lbr_cnabfield19	nvarchar2(60) NULL,
	lbr_cnabfield20	nvarchar2(60) NULL,
	lbr_cnabfield21	nvarchar2(60) NULL,
	lbr_cnabfield22	nvarchar2(60) NULL,
	lbr_cnabfield23	nvarchar2(60) NULL,
	lbr_cnabfield24	nvarchar2(60) NULL,
	lbr_cnabfield25	nvarchar2(60) NULL,
	lbr_cnabfield26	nvarchar2(60) NULL,
	lbr_cnabfield27	nvarchar2(60) NULL,
	lbr_cnabfield28	nvarchar2(60) NULL,
	lbr_cnabfield29	nvarchar2(60) NULL,
	lbr_cnabfield30	nvarchar2(60) NULL,
	lbr_cnabfield31	nvarchar2(60) NULL,
	lbr_cnabfield32	nvarchar2(60) NULL,
	lbr_cnabfield33	nvarchar2(60) NULL,
	lbr_cnabfield34	nvarchar2(60) NULL,
	lbr_cnabfield35	nvarchar2(60) NULL,
	lbr_cnabfield36	nvarchar2(60) NULL,
	lbr_cnabfield37	nvarchar2(60) NULL,
	lbr_cnabfield38	nvarchar2(60) NULL,
	lbr_cnabfield39	nvarchar2(60) NULL,
	lbr_cnabfield40	nvarchar2(60) NULL,
	lbr_cnabfield41	nvarchar2(60) NULL,
	lbr_cnabfield42	nvarchar2(60) NULL,
	lbr_cnabfield43	nvarchar2(60) NULL,
	lbr_cnabfield44	nvarchar2(60) NULL,
	lbr_cnabfield45	nvarchar2(60) NULL,
	lbr_cnabfield46	nvarchar2(60) NULL,
	lbr_docdate    	date NOT NULL 
	);

CREATE TABLE adempiere.lbr_docprint ( 
	lbr_docprint_id 	number(10,0) NOT NULL,
	ad_org_id       	number(10,0) NOT NULL,
	ad_client_id    	number(10,0) NOT NULL,
	isactive        	char(1) DEFAULT 'Y' NOT NULL,
	created         	date NOT NULL,
	createdby       	number(10,0) NOT NULL,
	updated         	date NOT NULL,
	updatedby       	number(10,0) NOT NULL,
	name            	nvarchar2(60) NOT NULL,
	description     	nvarchar2(255) NULL,
	lbr_createfields	char(1) NULL,
	lbr_tablename   	nvarchar2(60) NOT NULL,
	lbr_hassubdoc   	char(1) DEFAULT 'N' NOT NULL,
	lbr_subdoc_id   	number(10,0) NULL,
	lbr_subdocrow   	number(10,0) NULL,
	lbr_norows      	number(10,0) NULL,
	lbr_nocols      	number(10,0) NULL,
	lbr_issubdoc    	char(1) DEFAULT 'N' NOT NULL 
	);

CREATE TABLE adempiere.lbr_docprintfield ( 
	lbr_docprintfield_id	number(10,0) NOT NULL,
	ad_org_id           	number(10,0) NOT NULL,
	ad_client_id        	number(10,0) NOT NULL,
	isactive            	char(1) DEFAULT 'Y' NOT NULL,
	created             	date NOT NULL,
	createdby           	number(10,0) NOT NULL,
	updated             	date NOT NULL,
	updatedby           	number(10,0) NOT NULL,
	lbr_docprint_id     	number(10,0) NOT NULL,
	name                	nvarchar2(60) NOT NULL,
	lbr_rowno           	number(10,0) NULL,
	lbr_columnno        	number(10,0) NULL,
	comments            	nvarchar2(255) NULL,
	lbr_printformat     	nvarchar2(1) DEFAULT 'S' NULL,
	lbr_isheader        	char(1) DEFAULT 'N' NOT NULL,
	lbr_fieldalignment  	nvarchar2(1) DEFAULT 'L' NULL,
	lbr_fieldlength     	number(10,0) NULL 
	);

CREATE TABLE adempiere.lbr_fiscalgroup_bpartner ( 
	lbr_fiscalgroup_bpartner_id	number(10,0) NOT NULL,
	ad_org_id                  	number(10,0) NOT NULL,
	ad_client_id               	number(10,0) NOT NULL,
	isactive                   	char(1) DEFAULT 'Y' NOT NULL,
	created                    	date NOT NULL,
	createdby                  	number(10,0) NOT NULL,
	updated                    	date NOT NULL,
	updatedby                  	number(10,0) NOT NULL,
	name                       	nvarchar2(60) NOT NULL,
	description                	nvarchar2(255) NULL 
	);

CREATE TABLE adempiere.lbr_fiscalgroup_product ( 
	lbr_fiscalgroup_product_id	number(10,0) NOT NULL,
	ad_org_id                 	number(10,0) NOT NULL,
	ad_client_id              	number(10,0) NOT NULL,
	isactive                  	char(1) DEFAULT 'Y' NOT NULL,
	created                   	date NOT NULL,
	createdby                 	number(10,0) NOT NULL,
	updated                   	date NOT NULL,
	updatedby                 	number(10,0) NOT NULL,
	name                      	nvarchar2(60) NOT NULL,
	description               	nvarchar2(255) NULL 
	);

CREATE TABLE adempiere.lbr_icmsmatrix ( 
	lbr_icmsmatrix_id	number(10,0) NOT NULL,
	ad_org_id        	number(10,0) NOT NULL,
	ad_client_id     	number(10,0) NOT NULL,
	isactive         	char(1) DEFAULT 'Y' NOT NULL,
	created          	date NOT NULL,
	createdby        	number(10,0) NOT NULL,
	updated          	date NOT NULL,
	updatedby        	number(10,0) NOT NULL,
	c_region_id      	number(10,0) NOT NULL,
	to_region_id     	number(10,0) NOT NULL,
	lbr_tax_id       	number(10,0) NULL 
	);

CREATE TABLE adempiere.lbr_ncm ( 
	lbr_ncm_id  	number(10,0) NOT NULL,
	ad_org_id   	number(10,0) NOT NULL,
	ad_client_id	number(10,0) NOT NULL,
	isactive    	char(1) DEFAULT 'Y' NOT NULL,
	created     	date NOT NULL,
	createdby   	number(10,0) NOT NULL,
	updated     	date NOT NULL,
	updatedby   	number(10,0) NOT NULL,
	value       	nvarchar2(60) NOT NULL,
	description 	nvarchar2(255) NULL,
	lbr_tax_id      number(10,0) NULL 
	);

CREATE TABLE adempiere.lbr_notafiscal ( 
	lbr_notafiscal_id     	number(10,0) NOT NULL,
	ad_org_id             	number(10,0) NOT NULL,
	ad_client_id          	number(10,0) NOT NULL,
	isactive              	char(1) DEFAULT 'Y' NOT NULL,
	created               	date NOT NULL,
	createdby             	number(10,0) NOT NULL,
	updated               	date NOT NULL,
	updatedby             	number(10,0) NOT NULL,
	c_bpartner_id         	number(10,0) NULL,
	c_bpartner_location_id	number(10,0) NULL,
	c_doctype_id          	number(10,0) NULL,
	c_doctypetarget_id    	number(10,0) NULL,
	c_invoice_id          	number(10,0) NULL,
	c_order_id            	number(10,0) NULL,
	c_paymentterm_id      	number(10,0) NULL,
	m_inout_id            	number(10,0) NULL,
	m_shipper_id          	number(10,0) NULL,
	bill_location_id      	number(10,0) NULL,
	documentno            	nvarchar2(30) NOT NULL,
	description           	nvarchar2(255) NULL,
	issotrx               	char(1) DEFAULT 'Y' NOT NULL,
	isprinted             	char(1) DEFAULT 'N' NOT NULL,
	iscancelled           	char(1) DEFAULT 'N' NOT NULL,
	bpname                	nvarchar2(60) NULL,
	lbr_bpaddress1        	nvarchar2(60) NULL,
	lbr_bpaddress2        	nvarchar2(60) NULL,
	lbr_bpaddress3        	nvarchar2(60) NULL,
	lbr_bpaddress4        	nvarchar2(60) NULL,
	lbr_bpcnpj            	nvarchar2(30) NULL,
	lbr_bpcity            	nvarchar2(60) NULL,
	lbr_bpcountry         	nvarchar2(60) NULL,
	lbr_bpie              	nvarchar2(30) NULL,
	lbr_bpphone           	nvarchar2(30) NULL,
	lbr_bppostal          	nvarchar2(30) NULL,
	lbr_bpregion          	nvarchar2(2) NULL,
	lbr_bpdeliveryaddress1	nvarchar2(60) NULL,
	lbr_bpdeliveryaddress2	nvarchar2(60) NULL,
	lbr_bpdeliveryaddress3	nvarchar2(60) NULL,
	lbr_bpdeliveryaddress4	nvarchar2(60) NULL,
	lbr_bpdeliverycnpj    	nvarchar2(30) NULL,
	lbr_bpdeliverycity    	nvarchar2(60) NULL,
	lbr_bpdeliverycountry 	nvarchar2(60) NULL,
	lbr_bpdeliveryie      	nvarchar2(30) NULL,
	lbr_bpdeliverypostal  	nvarchar2(30) NULL,
	lbr_bpdeliveryregion  	nvarchar2(2) NULL,
	lbr_bpinvoiceaddress1 	nvarchar2(60) NULL,
	lbr_bpinvoiceaddress2 	nvarchar2(60) NULL,
	lbr_bpinvoiceaddress3 	nvarchar2(60) NULL,
	lbr_bpinvoiceaddress4 	nvarchar2(60) NULL,
	lbr_bpinvoicecnpj     	nvarchar2(30) NULL,
	lbr_bpinvoicecity     	nvarchar2(60) NULL,
	lbr_bpinvoicecountry  	nvarchar2(60) NULL,
	lbr_bpinvoiceie       	nvarchar2(30) NULL,
	lbr_bpinvoiceregion   	nvarchar2(2) NULL,
	lbr_bpshipperaddress1 	nvarchar2(60) NULL,
	lbr_bpshipperaddress2 	nvarchar2(60) NULL,
	lbr_bpshipperaddress3 	nvarchar2(60) NULL,
	lbr_bpshipperaddress4 	nvarchar2(60) NULL,
	lbr_bpshippercnpj     	nvarchar2(30) NULL,
	lbr_bpshippercity     	nvarchar2(60) NULL,
	lbr_bpshippercountry  	nvarchar2(60) NULL,
	lbr_bpshipperie       	nvarchar2(30) NULL,
	lbr_bpshipperpostal   	nvarchar2(30) NULL,
	lbr_bpshipperregion   	nvarchar2(2) NULL,
	lbr_bpinvoicepostal   	nvarchar2(30) NULL,
	lbr_cnpj              	nvarchar2(18) NULL,
	lbr_ie                	nvarchar2(30) NULL,
	datedoc               	date NULL,
	freightamt            	number NULL,
	freightcostrule       	char(1) NULL,
	lbr_grossweight       	number NULL,
	lbr_netweight         	number NULL,
	nopackages            	number NULL,
	totallines            	number NULL,
	grandtotal            	number NULL,
	lbr_insuranceamt      	number NULL,
	processed             	char(1) DEFAULT 'N' NOT NULL,
	processing            	char(1) NULL,
	lbr_ncmreference      	nvarchar2(300) NULL,
	lbr_cfopreference     	nvarchar2(300) NULL,
	documentnote          	nvarchar2(300) NULL 
	);

CREATE TABLE adempiere.lbr_notafiscalline ( 
	lbr_notafiscalline_id	number(10,0) NOT NULL,
	ad_org_id            	number(10,0) NOT NULL,
	ad_client_id         	number(10,0) NOT NULL,
	isactive             	char(1) DEFAULT 'Y' NOT NULL,
	created              	date NOT NULL,
	createdby            	number(10,0) NOT NULL,
	updated              	date NOT NULL,
	updatedby            	number(10,0) NOT NULL,
	c_invoiceline_id     	number(10,0) NULL,
	lbr_notafiscal_id    	number(10,0) NULL,
	m_product_id         	number(10,0) NULL,
	c_uom_id             	number(10,0) NULL,
	lbr_ncm_id           	number(10,0) NULL,
	lbr_cfop_id          	number(10,0) NULL,
	productname          	nvarchar2(100) NULL,
	productvalue         	nvarchar2(60) NULL,
	price                	number NULL,
	linetotalamt         	number NULL,
	pricelistamt         	number NULL,
	qty                  	number NULL,
	lbr_uomname          	nvarchar2(60) NULL,
	description          	nvarchar2(255) NULL,
	discount             	number NULL,
	line                 	number(10,0) NULL,
	lbr_ncmname          	nvarchar2(60) NULL,
	lbr_cfopname         	nvarchar2(60) NULL,
	vendorproductno      	nvarchar2(60) NULL 
	);

CREATE TABLE adempiere.lbr_productcategory ( 
	lbr_productcategory_id	number(10,0) NOT NULL,
	ad_org_id             	number(10,0) NOT NULL,
	ad_client_id          	number(10,0) NOT NULL,
	isactive              	char(1) DEFAULT 'Y' NOT NULL,
	created               	date NOT NULL,
	createdby             	number(10,0) NOT NULL,
	updated               	date NOT NULL,
	updatedby             	number(10,0) NOT NULL,
	name                  	nvarchar2(60) NOT NULL,
	description           	nvarchar2(255) NULL 
	);

CREATE TABLE adempiere.lbr_tax ( 
	lbr_tax_id  	number(10,0) NOT NULL,
	ad_org_id   	number(10,0) NOT NULL,
	ad_client_id	number(10,0) NOT NULL,
	isactive    	char(1) DEFAULT 'Y' NOT NULL,
	created     	date NOT NULL,
	createdby   	number(10,0) NOT NULL,
	updated     	date NOT NULL,
	updatedby   	number(10,0) NOT NULL,
	description 	nvarchar2(255) NULL 
	);

CREATE TABLE adempiere.lbr_taxconfig_bpartner ( 
	lbr_taxconfig_bpartner_id	number(10,0) NOT NULL,
	ad_org_id                	number(10,0) NOT NULL,
	ad_client_id             	number(10,0) NOT NULL,
	isactive                 	char(1) DEFAULT 'Y' NOT NULL,
	created                  	date NOT NULL,
	createdby                	number(10,0) NOT NULL,
	updated                  	date NOT NULL,
	updatedby                	number(10,0) NOT NULL,
	lbr_taxconfiguration_id  	number(10,0) NOT NULL,
	c_bpartner_id            	number(10,0) NOT NULL,
	lbr_tax_id               	number(10,0) NOT NULL 
	);

CREATE TABLE adempiere.lbr_taxconfig_bpgroup ( 
	lbr_taxconfig_bpgroup_id   	number(10,0) NOT NULL,
	ad_org_id                  	number(10,0) NOT NULL,
	ad_client_id               	number(10,0) NOT NULL,
	isactive                   	char(1) DEFAULT 'Y' NOT NULL,
	created                    	date NOT NULL,
	createdby                  	number(10,0) NOT NULL,
	updated                    	date NOT NULL,
	updatedby                  	number(10,0) NOT NULL,
	lbr_taxconfiguration_id    	number(10,0) NOT NULL,
	lbr_fiscalgroup_bpartner_id	number(10,0) NOT NULL,
	lbr_tax_id                 	number(10,0) NOT NULL 
	);

CREATE TABLE adempiere.lbr_taxconfig_product ( 
	lbr_taxconfig_product_id	number(10,0) NOT NULL,
	ad_org_id               	number(10,0) NOT NULL,
	ad_client_id            	number(10,0) NOT NULL,
	isactive                	char(1) DEFAULT 'Y' NOT NULL,
	created                 	date NOT NULL,
	createdby               	number(10,0) NOT NULL,
	updated                 	date NOT NULL,
	updatedby               	number(10,0) NOT NULL,
	lbr_taxconfiguration_id 	number(10,0) NOT NULL,
	lbr_tax_id             	number(10,0) NOT NULL 
	);

CREATE TABLE adempiere.lbr_taxconfig_productgroup ( 
	lbr_taxconfig_productgroup_id	number(10,0) NOT NULL,
	ad_org_id                    	number(10,0) NOT NULL,
	ad_client_id                 	number(10,0) NOT NULL,
	isactive                     	char(1) DEFAULT 'Y' NOT NULL,
	created                      	date NOT NULL,
	createdby                    	number(10,0) NOT NULL,
	updated                      	date NOT NULL,
	updatedby                    	number(10,0) NOT NULL,
	lbr_taxconfiguration_id      	number(10,0) NOT NULL,
	lbr_tax_id                   	number(10,0) NOT NULL 
	);

CREATE TABLE adempiere.lbr_taxconfig_region ( 
	lbr_taxconfig_region_id	number(10,0) NOT NULL,
	ad_org_id              	number(10,0) NOT NULL,
	ad_client_id           	number(10,0) NOT NULL,
	isactive               	char(1) DEFAULT 'Y' NOT NULL,
	created                	date NOT NULL,
	createdby              	number(10,0) NOT NULL,
	updated                	date NOT NULL,
	updatedby              	number(10,0) NOT NULL,
	lbr_taxconfiguration_id	number(10,0) NOT NULL,
	c_region_id            	number(10,0) NOT NULL,
	to_region_id           	number(10,0) NOT NULL,
	lbr_tax_id             	number(10,0) NOT NULL 
	);

CREATE TABLE adempiere.lbr_taxconfiguration ( 
	lbr_taxconfiguration_id   	number(10,0) NOT NULL,
	ad_org_id                 	number(10,0) NOT NULL,
	ad_client_id              	number(10,0) NOT NULL,
	isactive                  	char(1) DEFAULT 'Y' NOT NULL,
	created                   	date NOT NULL,
	createdby                 	number(10,0) NOT NULL,
	updated                   	date NOT NULL,
	updatedby                 	number(10,0) NOT NULL,
	lbr_exceptiontype         	char(1) DEFAULT 'P' NULL,
	m_product_id              	number(10,0) NULL,
	lbr_fiscalgroup_product_id	number(10,0) NULL 
	);

CREATE TABLE adempiere.lbr_taxformula ( 
	lbr_taxformula_id  	number(10,0) NOT NULL,
	ad_org_id          	number(10,0) NOT NULL,
	ad_client_id       	number(10,0) NOT NULL,
	isactive           	char(1) DEFAULT 'Y' NOT NULL,
	created            	date NOT NULL,
	createdby          	number(10,0) NOT NULL,
	updated            	date NOT NULL,
	updatedby          	number(10,0) NOT NULL,
	lbr_taxname_id     	number(10,0) NOT NULL,
	lbr_transactiontype	char(3) NOT NULL,
	lbr_formula        	nvarchar2(2000) NULL,
	lbr_formulanetworth	nvarchar2(2000) NULL 
	);

CREATE TABLE adempiere.lbr_taxline ( 
	lbr_taxline_id	number(10,0) NOT NULL,
	ad_org_id     	number(10,0) NOT NULL,
	ad_client_id  	number(10,0) NOT NULL,
	isactive      	char(1) DEFAULT 'Y' NOT NULL,
	created       	date NOT NULL,
	createdby     	number(10,0) NOT NULL,
	updated       	date NOT NULL,
	updatedby     	number(10,0) NOT NULL,
	lbr_tax_id    	number(10,0) NOT NULL,
	lbr_taxrate   	number NULL,
	lbr_taxbase   	number NULL,
	lbr_posttax   	char(1) DEFAULT 'Y' NOT NULL,
	lbr_taxamt    	number NULL,
	lbr_taxname_id	number(10,0) NOT NULL,
	lbr_taxbaseamt	number NULL 
	);

CREATE TABLE adempiere.lbr_taxname ( 
	lbr_taxname_id   	number(10,0) NOT NULL,
	ad_org_id        	number(10,0) NOT NULL,
	ad_client_id     	number(10,0) NOT NULL,
	isactive         	char(1) DEFAULT 'Y' NOT NULL,
	created          	date NOT NULL,
	createdby        	number(10,0) NOT NULL,
	updated          	date NOT NULL,
	updatedby        	number(10,0) NOT NULL,
	name             	nvarchar2(60) NOT NULL,
	description      	nvarchar2(255) NULL,
	lbr_taxtype      	char(1) DEFAULT 'P' NOT NULL,
	haswithhold      	char(1) DEFAULT 'N' NOT NULL,
	withholdthreshold	number NULL 
	);

ALTER TABLE adempiere.lbr_bank
	ADD CONSTRAINT lbr_bank_key
	PRIMARY KEY (lbr_bank_id);

ALTER TABLE adempiere.lbr_bankinfo
	ADD CONSTRAINT lbr_bankinfo_key
	PRIMARY KEY (lbr_bankinfo_id);

ALTER TABLE adempiere.lbr_boleto
	ADD CONSTRAINT lbr_boleto_key
	PRIMARY KEY (lbr_boleto_id);

ALTER TABLE adempiere.lbr_bpartnercategory
	ADD CONSTRAINT lbr_bpartnercategory_key
	PRIMARY KEY (lbr_bpartnercategory_id);

ALTER TABLE adempiere.lbr_cfop
	ADD CONSTRAINT lbr_cfop_key
	PRIMARY KEY (lbr_cfop_id);

ALTER TABLE adempiere.lbr_cfopline
	ADD CONSTRAINT lbr_cfopline_key
	PRIMARY KEY (lbr_cfopline_id);

ALTER TABLE adempiere.lbr_cnab
	ADD CONSTRAINT lbr_cnab_key
	PRIMARY KEY (lbr_cnab_id);

ALTER TABLE adempiere.lbr_docprint
	ADD CONSTRAINT lbr_docprint_key
	PRIMARY KEY (lbr_docprint_id);

ALTER TABLE adempiere.lbr_docprintfield
	ADD CONSTRAINT lbr_docprintfield_key
	PRIMARY KEY (lbr_docprintfield_id);

ALTER TABLE adempiere.lbr_fiscalgroup_bpartner
	ADD CONSTRAINT lbr_fiscalgroup_bpartner_key
	PRIMARY KEY (lbr_fiscalgroup_bpartner_id);

ALTER TABLE adempiere.lbr_fiscalgroup_product
	ADD CONSTRAINT lbr_fiscalgroup_product_key
	PRIMARY KEY (lbr_fiscalgroup_product_id);

ALTER TABLE adempiere.lbr_icmsmatrix
	ADD CONSTRAINT lbr_icmsmatrix_key
	PRIMARY KEY (lbr_icmsmatrix_id);

ALTER TABLE adempiere.lbr_ncm
	ADD CONSTRAINT lbr_ncm_key
	PRIMARY KEY (lbr_ncm_id);

ALTER TABLE adempiere.lbr_notafiscal
	ADD CONSTRAINT lbr_notafiscal_key
	PRIMARY KEY (lbr_notafiscal_id);

ALTER TABLE adempiere.lbr_notafiscalline
	ADD CONSTRAINT lbr_notafiscalline_key
	PRIMARY KEY (lbr_notafiscalline_id);

ALTER TABLE adempiere.lbr_productcategory
	ADD CONSTRAINT lbr_productcategory_key
	PRIMARY KEY (lbr_productcategory_id);

ALTER TABLE adempiere.lbr_tax
	ADD CONSTRAINT lbr_tax_key
	PRIMARY KEY (lbr_tax_id);

ALTER TABLE adempiere.lbr_taxconfig_bpartner
	ADD CONSTRAINT lbr_taxconfig_bpartner_key
	PRIMARY KEY (lbr_taxconfig_bpartner_id);

ALTER TABLE adempiere.lbr_taxconfig_bpgroup
	ADD CONSTRAINT lbr_taxconfig_bpgroup_key
	PRIMARY KEY (lbr_taxconfig_bpgroup_id);

ALTER TABLE adempiere.lbr_taxconfig_product
	ADD CONSTRAINT lbr_taxconfig_product_key
	PRIMARY KEY (lbr_taxconfig_product_id);

ALTER TABLE adempiere.lbr_taxconfig_productgroup
	ADD CONSTRAINT lbr_taxconfig_prodgroup_key
	PRIMARY KEY (lbr_taxconfig_productgroup_id);

ALTER TABLE adempiere.lbr_taxconfig_region
	ADD CONSTRAINT lbr_taxconfig_region_key
	PRIMARY KEY (lbr_taxconfig_region_id);

ALTER TABLE adempiere.lbr_taxconfiguration
	ADD CONSTRAINT lbr_taxconfiguration_key
	PRIMARY KEY (lbr_taxconfiguration_id);

ALTER TABLE adempiere.lbr_taxformula
	ADD CONSTRAINT lbr_taxformula_key
	PRIMARY KEY (lbr_taxformula_id);

ALTER TABLE adempiere.lbr_taxline
	ADD CONSTRAINT lbr_taxline_key
	PRIMARY KEY (lbr_taxline_id);

ALTER TABLE adempiere.lbr_taxname
	ADD CONSTRAINT lbr_taxname_key
	PRIMARY KEY (lbr_taxname_id);

ALTER TABLE adempiere.lbr_bank
	ADD CONSTRAINT lbr_bank_routingkey
	UNIQUE (routingno);

ALTER TABLE adempiere.lbr_bankinfo
	ADD CONSTRAINT lbr_bankinfo_key2
	UNIQUE (lbr_bank_id, lbr_bankinfo_id);

ALTER TABLE adempiere.lbr_icmsmatrix
	ADD CONSTRAINT lbr_icmsmatrix_key2
	UNIQUE (c_region_id, to_region_id);

ALTER TABLE adempiere.lbr_taxconfig_bpartner
	ADD CONSTRAINT lbr_taxconfig_bpartner_key2
	UNIQUE (c_bpartner_id, lbr_taxconfiguration_id);

ALTER TABLE adempiere.lbr_taxconfig_bpgroup
	ADD CONSTRAINT lbr_taxconfig_bpgroup_key2
	UNIQUE (lbr_fiscalgroup_bpartner_id, lbr_taxconfiguration_id);

ALTER TABLE adempiere.lbr_taxconfig_product
	ADD CONSTRAINT lbr_taxconfig_product_key2
	UNIQUE (lbr_taxconfiguration_id);

ALTER TABLE adempiere.lbr_taxconfig_productgroup
	ADD CONSTRAINT lbr_taxconfig_prodgroup_key2
	UNIQUE (lbr_taxconfiguration_id);

ALTER TABLE adempiere.lbr_taxconfig_region
	ADD CONSTRAINT lbr_taxconfig_region_key2
	UNIQUE (c_region_id, lbr_taxconfiguration_id, to_region_id);

ALTER TABLE adempiere.lbr_taxconfiguration
	ADD CONSTRAINT lbr_taxconfiguration_key2
	UNIQUE (lbr_exceptiontype, lbr_fiscalgroup_product_id, m_product_id);

ALTER TABLE adempiere.lbr_taxformula
	ADD CONSTRAINT lbr_taxformula_key2
	UNIQUE (lbr_taxname_id, lbr_transactiontype);

ALTER TABLE adempiere.lbr_taxline
	ADD CONSTRAINT lbr_taxline_key2
	UNIQUE (lbr_tax_id, lbr_taxname_id);

ALTER TABLE adempiere.lbr_bank
	ADD CONSTRAINT lbr_bank_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_bankinfo
	ADD CONSTRAINT lbr_bankinfo_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_boleto
	ADD CONSTRAINT lbr_boleto_lbr_iscancel_check
	CHECK (lbr_iscancelled IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_boleto
	ADD CONSTRAINT lbr_boleto_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_bpartnercategory
	ADD CONSTRAINT lbr_bpcategory_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_cfop
	ADD CONSTRAINT lbr_cfop_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_cfopline
	ADD CONSTRAINT lbr_cfopline_issubtrib_check
	CHECK (lbr_issubtributaria IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_cfopline
	ADD CONSTRAINT lbr_cfopline_ismanuf_check
	CHECK (lbr_ismanufactured IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_cfopline
	ADD CONSTRAINT lbr_cfopline_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_cnab
	ADD CONSTRAINT lbr_cnab_iscancel_check
	CHECK (lbr_iscancelled IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_cnab
	ADD CONSTRAINT lbr_cnab_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_docprint
	ADD CONSTRAINT lbr_docprint_issubdoc_check
	CHECK (lbr_issubdoc IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_docprint
	ADD CONSTRAINT lbr_docprint_hassubdoc_check
	CHECK (lbr_hassubdoc IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_docprint
	ADD CONSTRAINT lbr_docprint_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_docprintfield
	ADD CONSTRAINT lbr_docprintfield_ishdr_check
	CHECK (lbr_isheader IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_docprintfield
	ADD CONSTRAINT lbr_docprintfield_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_fiscalgroup_bpartner
	ADD CONSTRAINT lbr_fiscalgroup_bp_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_fiscalgroup_product
	ADD CONSTRAINT lbr_fiscalgrp_prod_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_icmsmatrix
	ADD CONSTRAINT lbr_icmsmatrix_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_ncm
	ADD CONSTRAINT lbr_ncm_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_notafiscal
	ADD CONSTRAINT lbr_notafiscal_proc_check
	CHECK (processed IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_notafiscal
	ADD CONSTRAINT lbr_notafiscal_issotrx_check
	CHECK (issotrx IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_notafiscal
	ADD CONSTRAINT lbr_notafiscal_isprinted_check
	CHECK (isprinted IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_notafiscal
	ADD CONSTRAINT lbr_notafiscal_iscancel_check
	CHECK (iscancelled IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_notafiscal
	ADD CONSTRAINT lbr_notafiscal_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_notafiscalline
	ADD CONSTRAINT lbr_notafiscalline_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_productcategory
	ADD CONSTRAINT lbr_prodcategory_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_tax
	ADD CONSTRAINT lbr_tax_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxconfig_bpartner
	ADD CONSTRAINT lbr_taxconfig_bp_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxconfig_bpgroup
	ADD CONSTRAINT lbr_taxconfig_bpgr_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxconfig_product
	ADD CONSTRAINT lbr_taxconfig_prod_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxconfig_productgroup
	ADD CONSTRAINT lbr_taxconf_prdgrp_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxconfig_region
	ADD CONSTRAINT lbr_taxconfig_reg_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxconfiguration
	ADD CONSTRAINT lbr_taxconfig_isact_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxformula
	ADD CONSTRAINT lbr_taxformula_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxline
	ADD CONSTRAINT lbr_taxline_lbr_posttax_check
	CHECK (lbr_posttax IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxline
	ADD CONSTRAINT lbr_taxline_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxname
	ADD CONSTRAINT lbr_taxname_isactive_check
	CHECK (isactive IN ('Y', 'N'));

ALTER TABLE adempiere.lbr_taxname
	ADD CONSTRAINT lbr_taxname_haswithhold_check
	CHECK (haswithhold IN ('Y', 'N'));

exit
