/*
Script generated by Aqua Data Studio 6.5.7 on Jan-09-2008 11:27:13 AM
Database: adempiere
Schema: adempiere
Objects: TABLE
*/
ALTER TABLE adempiere.ad_orginfo ADD	lbr_cnpj      	nvarchar2(18) NULL;
ALTER TABLE adempiere.ad_orginfo ADD	lbr_ie        	nvarchar2(30) NULL;
ALTER TABLE adempiere.ad_orginfo ADD	lbr_ccm       	nvarchar2(30) NULL;
ALTER TABLE adempiere.ad_orginfo ADD	lbr_suframa   	nvarchar2(30) NULL;
ALTER TABLE adempiere.ad_orginfo ADD	lbr_interest  	number DEFAULT 0 NOT NULL;
ALTER TABLE adempiere.ad_orginfo ADD	lbr_tax_id    	number(10,0) NULL;

ALTER TABLE adempiere.c_bank ADD	lbr_bank_id  	number(10,0) NULL;

ALTER TABLE adempiere.c_bankaccount ADD	lbr_billfold     	nvarchar2(20) NULL;
ALTER TABLE adempiere.c_bankaccount ADD	lbr_agencyno     	nvarchar2(10) NULL;
ALTER TABLE adempiere.c_bankaccount ADD	lbr_clientcode   	nvarchar2(30) NULL;
ALTER TABLE adempiere.c_bankaccount ADD	lbr_isbillprinted	char(1) DEFAULT 'N' NOT NULL;
ALTER TABLE adempiere.c_bankaccount ADD	ad_sequence_id   	number(10,0) NULL;
ALTER TABLE adempiere.c_bankaccount ADD	lbr_billkind     	nvarchar2(10) NULL;

ALTER TABLE adempiere.c_bpartner ADD	lbr_bptypebr               	nvarchar2(2) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_cnpj                   	nvarchar2(18) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_cpf                    	nvarchar2(14) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_rg                     	nvarchar2(30) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_ccm                    	nvarchar2(30) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_suframa                	nvarchar2(30) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_ie                     	nvarchar2(30) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_isieexempt             	char(1) DEFAULT 'N' NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_bptypebrisvalid        	char(1) DEFAULT 'N' NOT NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_customercategory_id    	number(10,0) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_vendorcategory_id      	number(10,0) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_fiscalgroup_customer_id	number(10,0) NULL;
ALTER TABLE adempiere.c_bpartner ADD	lbr_fiscalgroup_vendor_id  	number(10,0) NULL;

ALTER TABLE adempiere.c_invoice ADD	lbr_isbillprinted     	char(1) DEFAULT 'N' NOT NULL;
ALTER TABLE adempiere.c_invoice ADD	c_bankaccount_id      	number(10,0) NULL;
ALTER TABLE adempiere.c_invoice ADD	lbr_transactiontype   	char(3) NULL;

ALTER TABLE adempiere.c_invoiceline ADD	lbr_tax_id               	number(10,0) NULL;
ALTER TABLE adempiere.c_invoiceline ADD	lbr_cfop_id              	number(10,0) NULL; 

ALTER TABLE adempiere.c_order ADD	lbr_transactiontype   	char(3) NULL;

ALTER TABLE adempiere.c_orderline ADD	lbr_tax_id               	number(10,0) NULL;
ALTER TABLE adempiere.c_orderline ADD	lbr_cfop_id              	number(10,0) NULL;

ALTER TABLE adempiere.c_tax ADD	lbr_taxname_id        	number(10,0) NULL;

ALTER TABLE adempiere.m_product ADD	lbr_productcategory_id    	number(10,0) NULL;
ALTER TABLE adempiere.m_product ADD	lbr_ismanufactured        	char(1) DEFAULT 'N' NOT NULL;
ALTER TABLE adempiere.m_product ADD	lbr_ncm_id                	number(10,0) NULL;
ALTER TABLE adempiere.m_product ADD	lbr_fiscalgroup_product_id	number(10,0) NULL;

exit
