INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000000, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Bank', NULL, NULL, 1000003, 1000000, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000001, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Document', NULL, NULL, 1000004, 1000001, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000002, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Fields', NULL, NULL, 1000005, 1000001, 20, 1, 'N', 'N', 'N', 'N', 1000163, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'N', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000003, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Info', NULL, NULL, 1000008, 1000000, 20, 1, 'N', 'N', 'N', 'N', 1000234, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, '@lbr_jBoletoNo@!''''', 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000004, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'NCM', NULL, NULL, 1000009, 1000002, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000005, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'CFOP', NULL, NULL, 1000010, 1000003, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000006, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Category', NULL, NULL, 1000013, 1000008, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000007, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Category', NULL, NULL, 1000014, 1000009, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000008, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Line', NULL, NULL, 1000012, 1000003, 20, 1, 'N', 'N', 'N', 'N', 1000284, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000009, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Matrix', NULL, NULL, 1000015, 1000010, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000011, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Group', NULL, NULL, 1000018, 1000012, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000012, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Header', NULL, NULL, 1000016, 1000013, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000013, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Business Partner', NULL, NULL, 1000019, 1000013, 20, 1, 'N', 'N', 'N', 'N', 1000372, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000018, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Tax', NULL, NULL, 1000025, 1000014, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000010, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Group', NULL, NULL, 1000017, 1000011, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000014, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Business Partner Group', NULL, NULL, 1000020, 1000013, 30, 1, 'N', 'N', 'N', 'N', 1000383, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000019, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Formula', NULL, NULL, 1000026, 1000014, 20, 1, 'N', 'N', 'N', 'N', 1000463, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000020, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Header', NULL, NULL, 1000027, 1000015, 10, 0, 'N', 'N', 'N', 'N', NULL, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000021, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Line', NULL, NULL, 1000028, 1000015, 20, 1, 'N', 'N', 'N', 'N', 1000557, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, NULL, 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000015, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Product', NULL, NULL, 1000021, 1000013, 50, 1, 'N', 'N', 'N', 'N', 1000394, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, '@lbr_ExceptionType@=''P''', 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000016, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Product Group', NULL, NULL, 1000022, 1000013, 60, 1, 'N', 'N', 'N', 'N', 1000405, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, '@lbr_ExceptionType@=''G''', 'Y', 'N');
INSERT INTO ADEMPIERE.AD_TAB(ad_tab_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_table_id, ad_window_id, seqno, tablevel, issinglerow, isinfotab, istranslationtab, isreadonly, ad_column_id, hastree, whereclause, orderbyclause, commitwarning, ad_process_id, processing, ad_image_id, importfields, ad_columnsortorder_id, ad_columnsortyesno_id, issorttab, entitytype, included_tab_id, readonlylogic, displaylogic, isinsertrecord, isadvancedtab)
  VALUES(1000017, 0, 0, 'Y', sysdate, 100, sysdate, 100, 'Region', NULL, NULL, 1000023, 1000013, 40, 1, 'N', 'N', 'N', 'N', 1000416, 'N', NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'LBRA', NULL, NULL, '@lbr_ExceptionType@!''''', 'Y', 'N');
exit
