INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000015, 0, 0, 'Y', sysdate, 100, sysdate, 'Taxes', 100, NULL, 'Y', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000014, 0, 0, 'Y', sysdate, 100, sysdate, 'CFOP', 100, NULL, 'Y', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000004, 0, 0, 'Y', sysdate, 100, sysdate, 'Print', 100, NULL, 'Y', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000008, 0, 0, 'Y', sysdate, 100, sysdate, 'Fiscal', 100, NULL, 'Y', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000000, 0, 0, 'Y', sysdate, 100, sysdate, 'Localization Brazil', 100, NULL, 'Y', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000001, 0, 0, 'Y', sysdate, 100, sysdate, 'Bank', 100, NULL, 'Y', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000020, 0, 0, 'Y', sysdate, 100, sysdate, 'Nota Fiscal', 100, NULL, 'N', 'N', 'N', 'W', 1000015, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000002, 0, 0, 'Y', sysdate, 100, sysdate, 'Brazilian Banks', 100, 'Brazilian Banks', 'N', 'N', 'N', 'W', 1000000, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000005, 0, 0, 'Y', sysdate, 100, sysdate, 'Document Print', 100, NULL, 'N', 'N', 'N', 'W', 1000001, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000010, 0, 0, 'Y', sysdate, 100, sysdate, 'CFOP', 100, NULL, 'N', 'N', 'N', 'W', 1000003, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000017, 0, 0, 'Y', sysdate, 100, sysdate, 'Fiscal Group - Business Partner', 100, NULL, 'N', 'N', 'N', 'W', 1000012, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000012, 0, 0, 'Y', sysdate, 100, sysdate, 'BPartner Category (CFOP)', 100, NULL, 'N', 'N', 'N', 'W', 1000009, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000011, 0, 0, 'Y', sysdate, 100, sysdate, 'Product Category (CFOP)', 100, NULL, 'N', 'N', 'N', 'W', 1000008, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000013, 0, 0, 'Y', sysdate, 100, sysdate, 'ICMS Matrix', 100, NULL, 'N', 'N', 'N', 'W', 1000010, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000018, 0, 0, 'Y', sysdate, 100, sysdate, 'Tax Configuration', 100, NULL, 'N', 'N', 'N', 'W', 1000013, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000009, 0, 0, 'Y', sysdate, 100, sysdate, 'NCM', 100, NULL, 'N', 'N', 'N', 'W', 1000002, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000016, 0, 0, 'Y', sysdate, 100, sysdate, 'Fiscal Group - Product', 100, NULL, 'N', 'N', 'N', 'W', 1000011, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000019, 0, 0, 'Y', sysdate, 100, sysdate, 'Tax Brazil', 100, NULL, 'N', 'N', 'N', 'W', 1000014, NULL, NULL, NULL, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000006, 0, 0, 'Y', sysdate, 100, sysdate, 'Generate CNAB', 100, NULL, 'N', 'N', 'N', 'P', NULL, NULL, NULL, 1000001, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000007, 0, 0, 'Y', sysdate, 100, sysdate, 'Return CNAB', 100, NULL, 'N', 'N', 'N', 'P', NULL, NULL, NULL, 1000002, NULL, NULL, 'LBRA');
INSERT INTO ADEMPIERE.AD_MENU(ad_menu_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, name, updatedby, description, issummary, issotrx, isreadonly, action, ad_window_id, ad_workflow_id, ad_task_id, ad_process_id, ad_form_id, ad_workbench_id, entitytype)
  VALUES(1000003, 0, 0, 'Y', sysdate, 100, sysdate, 'Generate Bills', 100, NULL, 'N', 'Y', 'N', 'X', NULL, NULL, NULL, NULL, 1000000, NULL, 'LBRA');
exit
