INSERT INTO ADEMPIERE.LBR_TAXFormula(lbr_taxformula_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_taxname_id, lbr_transactiontype, lbr_formula, lbr_formulanetworth)
  VALUES(1000016, 0, 11, 'Y', sysdate, 100, sysdate, 100, 1000000, 'MAN', '(@AMT@*(1+(@PISPROD@+@COFINSPROD@)/(1-(@PISPROD@+@COFINSPROD@)-@ICMSPROD@)))/(1-@ICMSPROD@)', '((@AMT@/(1+@IPI@)) *(1-@ICMSPROD@))-(((@AMT@/(1+@IPI@)) * @PISPROD@) +((@AMT@/(1+@IPI@)) * @COFINSPROD@))');
INSERT INTO ADEMPIERE.LBR_TAXFormula(lbr_taxformula_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_taxname_id, lbr_transactiontype, lbr_formula, lbr_formulanetworth)
  VALUES(1000013, 0, 11, 'Y', sysdate, 100, sysdate, 100, 1000001, 'MAN', '(@AMT@*(1+(@PISPROD@+@COFINSPROD@)/(1-(@PISPROD@+@COFINSPROD@)-@ICMSPROD@)))/(1-@ICMSPROD@)', '((@AMT@/(1+@IPI@)) *(1-@ICMSPROD@))-(((@AMT@/(1+@IPI@)) * @PISPROD@) +((@AMT@/(1+@IPI@)) * @COFINSPROD@))');
INSERT INTO ADEMPIERE.LBR_TAXFormula(lbr_taxformula_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_taxname_id, lbr_transactiontype, lbr_formula, lbr_formulanetworth)
  VALUES(1000015, 0, 11, 'Y', sysdate, 100, sysdate, 100, 1000002, 'MAN', '(@AMT@*(1+(@PISPROD@+@COFINSPROD@)/(1-(@PISPROD@+@COFINSPROD@)-@ICMSPROD@)))/(1-@ICMSPROD@)', '((@AMT@/(1+@IPI@)) *(1-@ICMSPROD@))-(((@AMT@/(1+@IPI@)) * @PISPROD@) +((@AMT@/(1+@IPI@)) * @COFINSPROD@))');
INSERT INTO ADEMPIERE.LBR_TAXFormula(lbr_taxformula_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_taxname_id, lbr_transactiontype, lbr_formula, lbr_formulanetworth)
  VALUES(1000017, 0, 11, 'Y', sysdate, 100, sysdate, 100, 1000000, 'END', '((@AMT@*(1+(@PISPROD@+@COFINSPROD@)/(1-(@PISPROD@+@COFINSPROD@)-@ICMSPROD@*(1+@IPI@))))/(1-@ICMSPROD@*(1+@IPI@)))*(1+@IPI@)', '(@AMT@/(1+@IPI@))*(1-@ICMSPROD@*(1+@IPI@))-(((@AMT@/(1+@IPI@))*@PISPROD@)+((@AMT@/(1+@IPI@))*@COFINSPROD@))');
INSERT INTO ADEMPIERE.LBR_TAXFormula(lbr_taxformula_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_taxname_id, lbr_transactiontype, lbr_formula, lbr_formulanetworth)
  VALUES(1000012, 0, 11, 'Y', sysdate, 100, sysdate, 100, 1000001, 'END', '(@AMT@*(1+(@PISPROD@+@COFINSPROD@)/(1-(@PISPROD@+@COFINSPROD@)-@ICMSPROD@*(1+@IPI@))))/(1-@ICMSPROD@*(1+@IPI@))', '(@AMT@/(1+@IPI@))*(1-@ICMSPROD@*(1+@IPI@))-(((@AMT@/(1+@IPI@))*@PISPROD@)+((@AMT@/(1+@IPI@))*@COFINSPROD@))');
INSERT INTO ADEMPIERE.LBR_TAXFormula(lbr_taxformula_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_taxname_id, lbr_transactiontype, lbr_formula, lbr_formulanetworth)
  VALUES(1000014, 0, 11, 'Y', sysdate, 100, sysdate, 100, 1000002, 'END', '(@AMT@*(1+(@PISPROD@+@COFINSPROD@)/(1-(@PISPROD@+@COFINSPROD@)-@ICMSPROD@*(1+@IPI@))))/(1-@ICMSPROD*(1+@IPI@))', '(@AMT@/(1+@IPI@))*(1-@ICMSPROD@*(1+@IPI@))-(((@AMT@/(1+@IPI@))*@PISPROD@)+((@AMT@/(1+@IPI@))*@COFINSPROD@))');
INSERT INTO ADEMPIERE.LBR_TAXFormula(lbr_taxformula_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_taxname_id, lbr_transactiontype, lbr_formula, lbr_formulanetworth)
  VALUES(1000018, 0, 11, 'Y', sysdate, 100, sysdate, 100, 1000003, 'MAN', '(@AMT@*(1+(@PISPROD@+@COFINSPROD@)/(1-(@PISPROD@+@COFINSPROD@)-@ICMSPROD@)))/(1-@ICMSPROD@)', '((@AMT@/(1+@IPI@)) *(1-@ICMSPROD@))-(((@AMT@/(1+@IPI@)) * @PISPROD@) +((@AMT@/(1+@IPI@)) * @COFINSPROD@))');
INSERT INTO ADEMPIERE.LBR_TAXFormula(lbr_taxformula_id, ad_org_id, ad_client_id, isactive, created, createdby, updated, updatedby, lbr_taxname_id, lbr_transactiontype, lbr_formula, lbr_formulanetworth)
  VALUES(1000019, 0, 11, 'Y', sysdate, 100, sysdate, 100, 1000003, 'END', '((@AMT@*(1+(@PISPROD@+@COFINSPROD@)/(1-(@PISPROD@+@COFINSPROD@)-@ICMSPROD@*(1+@IPI@))))/(1-@ICMSPROD@*(1+@IPI@)))*(1+@IPI@)', '(@AMT@/(1+@IPI@))*(1-@ICMSPROD@*(1+@IPI@))-(((@AMT@/(1+@IPI@))*@PISPROD@)+((@AMT@/(1+@IPI@))*@COFINSPROD@))');
exit
