/*
Script generated by Aqua Data Studio 6.5.7 on Jan-09-2008 11:27:13 AM
Database: adempiere
Schema: adempiere
Objects: TABLE
*/
ALTER TABLE adempiere.ad_orginfo ADD COLUMN	lbr_cnpj      	varchar(18) NULL;
ALTER TABLE adempiere.ad_orginfo ADD COLUMN	lbr_ie        	varchar(30) NULL;
ALTER TABLE adempiere.ad_orginfo ADD COLUMN	lbr_ccm       	varchar(30) NULL;
ALTER TABLE adempiere.ad_orginfo ADD COLUMN	lbr_suframa   	varchar(30) NULL;
ALTER TABLE adempiere.ad_orginfo ADD COLUMN	lbr_interest  	numeric NOT NULL DEFAULT (0)::numeric;
ALTER TABLE adempiere.ad_orginfo ADD COLUMN	lbr_tax_id	numeric(10,0) NULL;

ALTER TABLE adempiere.c_bank ADD COLUMN	lbr_bank_id  	numeric(10,0) NULL;

ALTER TABLE adempiere.c_bankaccount ADD COLUMN	lbr_billfold     	varchar(20) NULL;
ALTER TABLE adempiere.c_bankaccount ADD COLUMN	lbr_agencyno     	varchar(10) NULL;
ALTER TABLE adempiere.c_bankaccount ADD COLUMN	lbr_clientcode   	varchar(30) NULL;
ALTER TABLE adempiere.c_bankaccount ADD COLUMN	lbr_isbillprinted	char(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE adempiere.c_bankaccount ADD COLUMN	ad_sequence_id   	numeric(10,0) NULL;
ALTER TABLE adempiere.c_bankaccount ADD COLUMN	lbr_billkind     	varchar(10) NULL;

ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_bptypebr               	varchar(2) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_cnpj                   	varchar(18) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_cpf                    	varchar(14) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_rg                     	varchar(30) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_ccm                    	varchar(30) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_suframa                	varchar(30) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_ie                     	varchar(30) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_isieexempt             	char(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_bptypebrisvalid        	char(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_customercategory_id    	numeric(10,0) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_vendorcategory_id      	numeric(10,0) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_fiscalgroup_customer_id	numeric(10,0) NULL;
ALTER TABLE adempiere.c_bpartner ADD COLUMN	lbr_fiscalgroup_vendor_id  	numeric(10,0) NULL;

ALTER TABLE adempiere.c_invoice ADD COLUMN	lbr_isbillprinted     	char(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE adempiere.c_invoice ADD COLUMN	c_bankaccount_id      	numeric(10,0) NULL;
ALTER TABLE adempiere.c_invoice ADD COLUMN	lbr_transactiontype   	char(3) NULL;

ALTER TABLE adempiere.c_invoiceline ADD COLUMN	lbr_tax_id	numeric(10,0) NULL;
ALTER TABLE adempiere.c_invoiceline ADD COLUMN	lbr_cfop_id              	numeric(10,0) NULL; 

ALTER TABLE adempiere.c_order ADD COLUMN	lbr_transactiontype   	char(3) NULL;

ALTER TABLE adempiere.c_orderline ADD COLUMN	lbr_tax_id	numeric(10,0) NULL;
ALTER TABLE adempiere.c_orderline ADD COLUMN	lbr_cfop_id              	numeric(10,0) NULL;

ALTER TABLE adempiere.c_tax ADD COLUMN	lbr_taxname_id        	numeric(10,0) NULL;

ALTER TABLE adempiere.m_product ADD COLUMN	lbr_productcategory_id    	numeric(10,0) NULL;
ALTER TABLE adempiere.m_product ADD COLUMN	lbr_ismanufactured        	char(1) NOT NULL DEFAULT 'N'::bpchar;
ALTER TABLE adempiere.m_product ADD COLUMN	lbr_ncm_id                	numeric(10,0) NULL;
ALTER TABLE adempiere.m_product ADD COLUMN	lbr_fiscalgroup_product_id	numeric(10,0) NULL;