INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000072, 0, 0, 'Y', '2007-11-07 10:32:18.0', 100, '2007-11-07 10:32:18.0', 100, 'lbr_CNABField44', 'LBRA', 'CNAB Field44', 'CNAB Field44', 'CNAB Field44', 'CNAB Field44', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000000, 0, 0, 'Y', '2007-10-30 10:18:24.0', 100, '2007-10-30 10:18:24.0', 100, 'lbr_BillFold', 'LBRA', 'Bill Fold', 'Bill Fold', 'Type of Bill Fold - For Bank Usage', 'Type of Bill Fold - For Bank Usage', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000001, 0, 0, 'Y', '2007-10-30 10:19:44.0', 100, '2007-10-30 10:19:44.0', 100, 'lbr_AgencyNo', 'LBRA', 'Agency Number', 'Agency Number', 'Agency Number', 'Agency Number', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000003, 0, 0, 'Y', '2007-10-30 10:22:58.0', 100, '2007-10-30 10:22:58.0', 100, 'lbr_IsBillPrinted', 'LBRA', 'Print Bill', 'Print Bill', 'Indicates if this Account is used to Print Bills', 'Indicates if this Account is used to Print Bills', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000008, 0, 0, 'Y', '2007-10-31 11:09:10.0', 100, '2007-10-31 11:09:10.0', 100, 'lbr_BPTypeBR', 'LBRA', 'Brazilian BP Type', 'Brazilian BP Type', 'Brazilian BP Type (Identifies if the BP is a Legal Entity or an Individual)', 'Used to identify if the Business partner is a legal entity or an individual', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000009, 0, 0, 'Y', '2007-10-31 11:11:36.0', 100, '2007-10-31 11:11:36.0', 100, 'lbr_CNPJ', 'LBRA', 'CNPJ', 'CNPJ', 'Used to identify Legal Entities in Brazil', 'Used to identify Legal Entities in Brazil', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000011, 0, 0, 'Y', '2007-10-31 11:16:15.0', 100, '2007-10-31 11:16:15.0', 100, 'lbr_RG', 'LBRA', 'RG', 'RG', 'Used to identify individuals in Brazil', 'Used to identify individuals in Brazil', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000012, 0, 0, 'Y', '2007-10-31 11:17:42.0', 100, '2007-10-31 11:17:42.0', 100, 'lbr_CCM', 'LBRA', 'CCM', 'CCM', 'City Identification Code used in Brazil (City Tax ID)', 'City Identification Code used in Brazil (City Tax ID)', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000013, 0, 0, 'Y', '2007-10-31 11:19:50.0', 100, '2007-10-31 11:19:50.0', 100, 'lbr_Suframa', 'LBRA', 'Suframa', 'Suframa', 'Brazilian SUFRAMA Identification Number', 'Brazilian SUFRAMA Identification Number', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000015, 0, 0, 'Y', '2007-10-31 11:23:03.0', 100, '2007-10-31 11:23:03.0', 100, 'lbr_IsIEExempt', 'LBRA', 'IE Exempt', 'IE Exempt', 'Business Partner is IE Exempt', 'Business Partner is IE Exempt', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000016, 0, 0, 'Y', '2007-10-31 11:25:10.0', 100, '2007-10-31 11:25:10.0', 100, 'lbr_BPTypeBRIsValid', 'LBRA', 'Brazilian BP Valid', 'Brazilian BP Valid', 'Brazilian BP is Valid', 'Indicates that the CNPJ or CPF is valid and there are no duplicates in the database. It is not possible to change the CNPJ or CPF after the validation.', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000017, 0, 0, 'Y', '2007-11-01 11:28:37.0', 100, '2007-11-01 11:28:37.0', 100, 'LBR_Boleto_ID', 'LBRA', 'Boleto', 'Boleto', 'Primary Key table LBR_Boleto', 'Primary Key table LBR_Boleto', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000010, 0, 0, 'Y', '2007-10-31 11:14:20.0', 100, '2007-11-07 09:22:26.0', 100, 'lbr_CPF', 'LBRA', 'CPF', 'CPF', 'Used to identify individuals in Brazil', 'Used to identify individuals in Brazil', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000014, 0, 0, 'Y', '2007-10-31 11:21:30.0', 100, '2007-11-07 09:22:47.0', 100, 'lbr_IE', 'LBRA', 'IE', 'IE', 'Used to Identify the IE (State Tax ID)', 'Used to Identify the IE (State Tax ID)', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000018, 0, 0, 'Y', '2007-11-07 09:38:06.0', 100, '2007-11-07 09:38:06.0', 100, 'lbr_DocDate', 'LBRA', 'Document Date', 'Document Date', 'Identifies the Document Date', 'Identifies the Document Date', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000019, 0, 0, 'Y', '2007-11-07 09:39:38.0', 100, '2007-11-07 09:39:38.0', 100, 'lbr_Cessionary', 'LBRA', 'Cessionary', 'Cessionary', 'Identifies the Cessionary', 'Identifies the Cessionary', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000021, 0, 0, 'Y', '2007-11-07 09:44:27.0', 100, '2007-11-07 09:44:27.0', 100, 'lbr_BillKind', 'LBRA', 'Bill Kind', 'Bill Kind', 'Defines the kind of Bill', 'Defines the kind of Bill', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000022, 0, 0, 'Y', '2007-11-07 09:47:22.0', 100, '2007-11-07 09:47:22.0', 100, 'lbr_PaymentLocation1', 'LBRA', 'Payment Location 1', 'Payment Location 1', 'Identifies the Payment Location 1', 'Identifies the Payment Location 1', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000023, 0, 0, 'Y', '2007-11-07 09:48:17.0', 100, '2007-11-07 09:48:17.0', 100, 'lbr_PaymentLocation2', 'LBRA', 'Payment Location 2', 'Payment Location 2', 'Identifies the Payment Location 2', 'Identifies the Payment Location 2', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000024, 0, 0, 'Y', '2007-11-07 09:49:42.0', 100, '2007-11-07 09:49:42.0', 100, 'lbr_Instruction1', 'LBRA', 'Instruction 1', 'Instruction 1', 'Identifies the Instrucion 1', 'Identifies the Instrucion 1', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000025, 0, 0, 'Y', '2007-11-07 09:50:09.0', 100, '2007-11-07 09:50:09.0', 100, 'lbr_Instruction2', 'LBRA', 'Instruction 2', 'Instruction 2', 'Identifies the Instrucion 2', 'Identifies the Instrucion 2', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000026, 0, 0, 'Y', '2007-11-07 09:50:33.0', 100, '2007-11-07 09:50:33.0', 100, 'lbr_Instruction3', 'LBRA', 'Instruction 3', 'Instruction 3', 'Identifies the Instrucion 3', 'Identifies the Instrucion 3', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000027, 0, 0, 'Y', '2007-11-07 09:58:32.0', 100, '2007-11-07 09:58:32.0', 100, 'lbr_IsCancelled', 'LBRA', 'IsCancelled', 'IsCancelled', 'Defines if the Document IsCancelled', 'Defines if the Document IsCancelled', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000028, 0, 0, 'Y', '2007-11-07 10:07:49.0', 100, '2007-11-07 10:07:56.0', 100, 'LBR_CNAB_ID', 'LBRA', 'CNAB', 'CNAB', 'Primary Key table LBR_CNAB', 'Primary Key table LBR_CNAB', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000029, 0, 0, 'Y', '2007-11-07 10:16:19.0', 100, '2007-11-07 10:16:19.0', 100, 'lbr_CNABField1', 'LBRA', 'CNAB Field1', 'CNAB Field1', 'CNAB Field1', 'CNAB Field1', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000030, 0, 0, 'Y', '2007-11-07 10:16:40.0', 100, '2007-11-07 10:16:40.0', 100, 'lbr_CNABField2', 'LBRA', 'CNAB Field2', 'CNAB Field2', 'CNAB Field2', 'CNAB Field2', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000031, 0, 0, 'Y', '2007-11-07 10:17:20.0', 100, '2007-11-07 10:17:20.0', 100, 'lbr_CNABField3', 'LBRA', 'CNAB Field3', 'CNAB Field3', 'CNAB Field3', 'CNAB Field3', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000032, 0, 0, 'Y', '2007-11-07 10:17:47.0', 100, '2007-11-07 10:17:47.0', 100, 'lbr_CNABField4', 'LBRA', 'CNAB Field4', 'CNAB Field4', 'CNAB Field4', 'CNAB Field4', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000033, 0, 0, 'Y', '2007-11-07 10:18:06.0', 100, '2007-11-07 10:18:06.0', 100, 'lbr_CNABField5', 'LBRA', 'CNAB Field5', 'CNAB Field5', 'CNAB Field5', 'CNAB Field5', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000034, 0, 0, 'Y', '2007-11-07 10:18:31.0', 100, '2007-11-07 10:18:31.0', 100, 'lbr_CNABField6', 'LBRA', 'CNAB Field6', 'CNAB Field6', 'CNAB Field6', 'CNAB Field6', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000035, 0, 0, 'Y', '2007-11-07 10:19:08.0', 100, '2007-11-07 10:19:08.0', 100, 'lbr_CNABField7', 'LBRA', 'CNAB Field7', 'CNAB Field7', 'CNAB Field7', 'CNAB Field7', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000036, 0, 0, 'Y', '2007-11-07 10:19:26.0', 100, '2007-11-07 10:19:26.0', 100, 'lbr_CNABField8', 'LBRA', 'CNAB Field8', 'CNAB Field8', 'CNAB Field8', 'CNAB Field8', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000037, 0, 0, 'Y', '2007-11-07 10:19:46.0', 100, '2007-11-07 10:19:46.0', 100, 'lbr_CNABField9', 'LBRA', 'CNAB Field9', 'CNAB Field9', 'CNAB Field9', 'CNAB Field9', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000038, 0, 0, 'Y', '2007-11-07 10:20:08.0', 100, '2007-11-07 10:20:08.0', 100, 'lbr_CNABField10', 'LBRA', 'CNAB Field10', 'CNAB Field10', 'CNAB Field10', 'CNAB Field10', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000039, 0, 0, 'Y', '2007-11-07 10:20:28.0', 100, '2007-11-07 10:20:28.0', 100, 'lbr_CNABField11', 'LBRA', 'CNAB Field11', 'CNAB Field11', 'CNAB Field11', 'CNAB Field11', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000040, 0, 0, 'Y', '2007-11-07 10:20:52.0', 100, '2007-11-07 10:20:52.0', 100, 'lbr_CNABField12', 'LBRA', 'CNAB Field12', 'CNAB Field12', 'CNAB Field12', 'CNAB Field12', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000041, 0, 0, 'Y', '2007-11-07 10:21:12.0', 100, '2007-11-07 10:21:12.0', 100, 'lbr_CNABField13', 'LBRA', 'CNAB Field13', 'CNAB Field13', 'CNAB Field13', 'CNAB Field13', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000042, 0, 0, 'Y', '2007-11-07 10:21:49.0', 100, '2007-11-07 10:21:49.0', 100, 'lbr_CNABField14', 'LBRA', 'CNAB Field14', 'CNAB Field14', 'CNAB Field14', 'CNAB Field14', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000043, 0, 0, 'Y', '2007-11-07 10:22:14.0', 100, '2007-11-07 10:22:14.0', 100, 'lbr_CNABField15', 'LBRA', 'CNAB Field15', 'CNAB Field15', 'CNAB Field15', 'CNAB Field15', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000044, 0, 0, 'Y', '2007-11-07 10:22:31.0', 100, '2007-11-07 10:22:31.0', 100, 'lbr_CNABField16', 'LBRA', 'CNAB Field16', 'CNAB Field16', 'CNAB Field16', 'CNAB Field16', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000045, 0, 0, 'Y', '2007-11-07 10:22:51.0', 100, '2007-11-07 10:22:51.0', 100, 'lbr_CNABField17', 'LBRA', 'CNAB Field17', 'CNAB Field17', 'CNAB Field17', 'CNAB Field17', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000046, 0, 0, 'Y', '2007-11-07 10:23:11.0', 100, '2007-11-07 10:23:24.0', 100, 'lbr_CNABField18', 'LBRA', 'CNAB Field18', 'CNAB Field18', 'CNAB Field18', 'CNAB Field18', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000047, 0, 0, 'Y', '2007-11-07 10:23:46.0', 100, '2007-11-07 10:23:46.0', 100, 'lbr_CNABField19', 'LBRA', 'CNAB Field19', 'CNAB Field19', 'CNAB Field19', 'CNAB Field19', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000048, 0, 0, 'Y', '2007-11-07 10:24:17.0', 100, '2007-11-07 10:24:17.0', 100, 'lbr_CNABField20', 'LBRA', 'CNAB Field20', 'CNAB Field20', 'CNAB Field20', 'CNAB Field20', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000049, 0, 0, 'Y', '2007-11-07 10:24:48.0', 100, '2007-11-07 10:24:48.0', 100, 'lbr_CNABField21', 'LBRA', 'CNAB Field21', 'CNAB Field21', 'CNAB Field21', 'CNAB Field21', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000050, 0, 0, 'Y', '2007-11-07 10:25:09.0', 100, '2007-11-07 10:25:09.0', 100, 'lbr_CNABField22', 'LBRA', 'CNAB Field22', 'CNAB Field22', 'CNAB Field22', 'CNAB Field22', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000051, 0, 0, 'Y', '2007-11-07 10:25:28.0', 100, '2007-11-07 10:25:28.0', 100, 'lbr_CNABField23', 'LBRA', 'CNAB Field23', 'CNAB Field23', 'CNAB Field23', 'CNAB Field23', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000052, 0, 0, 'Y', '2007-11-07 10:25:46.0', 100, '2007-11-07 10:25:46.0', 100, 'lbr_CNABField24', 'LBRA', 'CNAB Field24', 'CNAB Field24', 'CNAB Field24', 'CNAB Field24', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000053, 0, 0, 'Y', '2007-11-07 10:26:06.0', 100, '2007-11-07 10:26:06.0', 100, 'lbr_CNABField25', 'LBRA', 'CNAB Field25', 'CNAB Field25', 'CNAB Field25', 'CNAB Field25', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000054, 0, 0, 'Y', '2007-11-07 10:26:23.0', 100, '2007-11-07 10:26:23.0', 100, 'lbr_CNABField26', 'LBRA', 'CNAB Field26', 'CNAB Field26', 'CNAB Field26', 'CNAB Field26', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000055, 0, 0, 'Y', '2007-11-07 10:26:44.0', 100, '2007-11-07 10:26:44.0', 100, 'lbr_CNABField27', 'LBRA', 'CNAB Field27', 'CNAB Field27', 'CNAB Field27', 'CNAB Field27', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000056, 0, 0, 'Y', '2007-11-07 10:27:01.0', 100, '2007-11-07 10:27:01.0', 100, 'lbr_CNABField28', 'LBRA', 'CNAB Field28', 'CNAB Field28', 'CNAB Field28', 'CNAB Field28', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000057, 0, 0, 'Y', '2007-11-07 10:27:17.0', 100, '2007-11-07 10:27:17.0', 100, 'lbr_CNABField29', 'LBRA', 'CNAB Field29', 'CNAB Field29', 'CNAB Field29', 'CNAB Field29', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000058, 0, 0, 'Y', '2007-11-07 10:27:42.0', 100, '2007-11-07 10:27:42.0', 100, 'lbr_CNABField30', 'LBRA', 'CNAB Field30', 'CNAB Field30', 'CNAB Field30', 'CNAB Field30', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000059, 0, 0, 'Y', '2007-11-07 10:28:04.0', 100, '2007-11-07 10:28:04.0', 100, 'lbr_CNABField31', 'LBRA', 'CNAB Field31', 'CNAB Field31', 'CNAB Field31', 'CNAB Field31', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000060, 0, 0, 'Y', '2007-11-07 10:28:22.0', 100, '2007-11-07 10:28:22.0', 100, 'lbr_CNABField32', 'LBRA', 'CNAB Field32', 'CNAB Field32', 'CNAB Field32', 'CNAB Field32', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000061, 0, 0, 'Y', '2007-11-07 10:28:40.0', 100, '2007-11-07 10:28:40.0', 100, 'lbr_CNABField33', 'LBRA', 'CNAB Field33', 'CNAB Field33', 'CNAB Field33', 'CNAB Field33', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000062, 0, 0, 'Y', '2007-11-07 10:28:58.0', 100, '2007-11-07 10:28:58.0', 100, 'lbr_CNABField34', 'LBRA', 'CNAB Field34', 'CNAB Field34', 'CNAB Field34', 'CNAB Field34', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000063, 0, 0, 'Y', '2007-11-07 10:29:22.0', 100, '2007-11-07 10:29:22.0', 100, 'lbr_CNABField35', 'LBRA', 'CNAB Field35', 'CNAB Field35', 'CNAB Field35', 'CNAB Field35', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000064, 0, 0, 'Y', '2007-11-07 10:29:42.0', 100, '2007-11-07 10:29:42.0', 100, 'lbr_CNABField36', 'LBRA', 'CNAB Field36', 'CNAB Field36', 'CNAB Field36', 'CNAB Field36', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000065, 0, 0, 'Y', '2007-11-07 10:30:02.0', 100, '2007-11-07 10:30:02.0', 100, 'lbr_CNABField37', 'LBRA', 'CNAB Field37', 'CNAB Field37', 'CNAB Field37', 'CNAB Field37', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000066, 0, 0, 'Y', '2007-11-07 10:30:20.0', 100, '2007-11-07 10:30:20.0', 100, 'lbr_CNABField38', 'LBRA', 'CNAB Field38', 'CNAB Field38', 'CNAB Field38', 'CNAB Field38', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000067, 0, 0, 'Y', '2007-11-07 10:30:41.0', 100, '2007-11-07 10:30:41.0', 100, 'lbr_CNABField39', 'LBRA', 'CNAB Field39', 'CNAB Field39', 'CNAB Field39', 'CNAB Field39', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000068, 0, 0, 'Y', '2007-11-07 10:31:03.0', 100, '2007-11-07 10:31:03.0', 100, 'lbr_CNABField40', 'LBRA', 'CNAB Field40', 'CNAB Field40', 'CNAB Field40', 'CNAB Field40', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000069, 0, 0, 'Y', '2007-11-07 10:31:20.0', 100, '2007-11-07 10:31:20.0', 100, 'lbr_CNABField41', 'LBRA', 'CNAB Field41', 'CNAB Field41', 'CNAB Field41', 'CNAB Field41', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000070, 0, 0, 'Y', '2007-11-07 10:31:42.0', 100, '2007-11-07 10:31:42.0', 100, 'lbr_CNABField42', 'LBRA', 'CNAB Field42', 'CNAB Field42', 'CNAB Field42', 'CNAB Field42', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000071, 0, 0, 'Y', '2007-11-07 10:31:58.0', 100, '2007-11-07 10:31:58.0', 100, 'lbr_CNABField43', 'LBRA', 'CNAB Field43', 'CNAB Field43', 'CNAB Field43', 'CNAB Field43', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000073, 0, 0, 'Y', '2007-11-07 10:33:23.0', 100, '2007-11-07 10:33:23.0', 100, 'lbr_CNABField45', 'LBRA', 'CNAB Field45', 'CNAB Field45', 'CNAB Field45', 'CNAB Field45', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000074, 0, 0, 'Y', '2007-11-07 10:33:40.0', 100, '2007-11-07 10:33:40.0', 100, 'lbr_CNABField46', 'LBRA', 'CNAB Field46', 'CNAB Field46', 'CNAB Field46', 'CNAB Field46', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000075, 0, 0, 'Y', '2007-11-07 11:03:11.0', 100, '2007-11-07 11:03:11.0', 100, 'LBR_Bank_ID', 'LBRA', 'Bank', 'Bank', 'Primary Key table LBR_Bank', 'Primary Key table LBR_Bank', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000076, 0, 0, 'Y', '2007-11-07 11:18:56.0', 100, '2007-11-07 11:18:56.0', 100, 'lbr_jBoletoNo', 'LBRA', 'jBoleto Number', 'jBoleto Number', 'Identifies the bank number at jBoleto', 'Identifies the bank number at jBoleto', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000077, 0, 0, 'Y', '2007-11-08 15:26:57.0', 100, '2007-11-08 15:26:57.0', 100, 'lbr_PayScheduleNo', 'LBRA', 'PaySchedule Number', 'PaySchedule Number', 'Defines the PaySchedule Number', 'Defines the PaySchedule Number', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000078, 0, 0, 'Y', '2007-11-12 09:30:19.0', 100, '2007-11-12 09:30:50.0', 100, 'LBR_DocPrint_ID', 'LBRA', 'DocPrint', 'DocPrint', 'Primary key table LBR_DocPrint', 'Primary key table LBR_DocPrint', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000079, 0, 0, 'Y', '2007-11-12 11:26:21.0', 100, '2007-11-12 11:26:21.0', 100, 'lbr_CreateFields', 'LBRA', 'Create Fields', 'Create Fields', 'Processo to Create Document Fields', 'Processo to Create Document Fields', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000080, 0, 0, 'Y', '2007-11-12 11:27:29.0', 100, '2007-11-12 11:27:29.0', 100, 'lbr_TableName', 'LBRA', 'Table Name', 'Table Name', 'Identifies the Table or View Name', 'Identifies the Table or View Name', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000081, 0, 0, 'Y', '2007-11-12 11:29:21.0', 100, '2007-11-12 11:29:21.0', 100, 'lbr_HasSubDoc', 'LBRA', 'Has SubDoc', 'Has SubDoc', 'Identifies if the Document has SubDocuments', 'Identifies if the Document has SubDocuments', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000082, 0, 0, 'Y', '2007-11-12 11:30:46.0', 100, '2007-11-12 11:30:46.0', 100, 'lbr_SubDoc_ID', 'LBRA', 'SubDoc_ID', 'SubDoc_ID', 'Identifies the ID of the SubDocument', 'Identifies the ID of the SubDocument', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000083, 0, 0, 'Y', '2007-11-12 11:33:45.0', 100, '2007-11-12 11:33:45.0', 100, 'lbr_SubDocRow', 'LBRA', 'SubDoc Row', 'SubDoc Row', 'Identifies the Starter Row of the SubDocument', 'Identifies the Starter Row of the SubDocument', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000085, 0, 0, 'Y', '2007-11-12 11:35:44.0', 100, '2007-11-12 11:35:44.0', 100, 'lbr_NoCols', 'LBRA', 'Number of Columns', 'Number of Columns', 'Identifies the Number of Columns', 'Identifies the Number of Columns', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000086, 0, 0, 'Y', '2007-11-12 11:37:24.0', 100, '2007-11-12 11:37:24.0', 100, 'lbr_IsSubDoc', 'LBRA', 'IsSubDoc', 'IsSubDoc', 'Defines if this Documento is a SubDocument', 'Defines if this Documento is a SubDocument', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000087, 0, 0, 'Y', '2007-11-12 11:50:32.0', 100, '2007-11-12 11:50:32.0', 100, 'LBR_DocPrintField_ID', 'LBRA', 'DocPrint Field', 'DocPrint Field', 'Primary key table LBR_DocPrintField', 'Primary key table LBR_DocPrintField', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000088, 0, 0, 'Y', '2007-11-12 11:56:12.0', 100, '2007-11-12 11:56:12.0', 100, 'lbr_RowNo', 'LBRA', 'Row Number', 'Row Number', 'Defines the Y Position', 'Defines the Y Position', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000089, 0, 0, 'Y', '2007-11-12 11:57:06.0', 100, '2007-11-12 11:57:06.0', 100, 'lbr_ColumnNo', 'LBRA', 'Column Number', 'Column Number', 'Defines the X Position', 'Defines the X Position', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000091, 0, 0, 'Y', '2007-11-12 11:58:46.0', 100, '2007-11-12 11:58:46.0', 100, 'lbr_FieldAlignment', 'LBRA', 'Field Alignment', 'Field Alignment', 'Defines the Field Alignment', 'Defines the Field Alignment', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000092, 0, 0, 'Y', '2007-11-12 11:59:39.0', 100, '2007-11-12 11:59:39.0', 100, 'lbr_PrintFormat', 'LBRA', 'Print Format', 'Print Format', 'Defines the Print Format Type', 'Defines the Print Format Type', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000093, 0, 0, 'Y', '2007-11-12 12:01:23.0', 100, '2007-11-12 12:01:23.0', 100, 'lbr_IsHeader', 'LBRA', 'IsHeader', 'IsHeader', 'Identifies if this is a Header Information (all pages prints column)', 'Identifies if this is a Header Information (all pages prints column)', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000084, 0, 0, 'Y', '2007-11-12 11:35:18.0', 100, '2007-11-12 12:06:14.0', 100, 'lbr_NoRows', 'LBRA', 'Number of Rows', 'Number of Rows', 'Identifies the Number of Rows (If this is a SubDocument, enter 0 for unlimited)', 'Identifies the Number of Rows (If this is a SubDocument, enter 0 for unlimited)', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000094, 0, 0, 'Y', '2007-11-14 14:24:20.0', 100, '2007-11-14 14:24:20.0', 100, 'LBR_Tax_ID', 'LBRA', 'Brazilian Tax', 'Brazilian Tax', 'Primary key table LBR_Tax', 'Primary key table LBR_Tax', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000002, 0, 0, 'Y', '2007-10-30 10:21:15.0', 100, '2007-11-23 11:42:53.0', 100, 'lbr_ClientCode', 'LBRA', 'Client Code', 'Client Code', 'Client Code - needed for some Banks', 'Client Code used to generate the Bill', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000020, 0, 0, 'Y', '2007-11-07 09:40:38.0', 100, '2007-11-23 15:00:00.0', 100, 'lbr_ReceiverName', 'LBRA', 'Receiver Name', 'Receiver Name', 'Name of the Receiver', 'Name of the Receiver', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000090, 0, 0, 'Y', '2007-11-12 11:57:52.0', 100, '2007-11-23 16:23:33.0', 100, 'lbr_FieldLength', 'LBRA', 'Field Length', 'Field Length', 'Defines the Field Length', 'Defines the Field Length', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000126, 0, 0, 'Y', '2007-11-26 08:16:22.0', 100, '2007-11-26 08:16:22.0', 100, 'LBR_TaxLine_ID', 'LBRA', 'Tax Line', 'Tax Line', 'Primary key table LBR_TaxLine', 'Primary key table LBR_TaxLine', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000127, 0, 0, 'Y', '2007-11-26 08:24:10.0', 100, '2007-11-26 08:24:10.0', 100, 'lbr_TaxRate', 'LBRA', 'Tax Rate', 'Tax Rate', 'Indicates the Tax Rate', 'Indicates the Tax Rate', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000128, 0, 0, 'Y', '2007-11-26 08:25:59.0', 100, '2007-11-26 08:25:59.0', 100, 'lbr_TaxBase', 'LBRA', 'Tax Base', 'Tax Base', 'Indicates the Tax Base', 'Indicates the Tax Base', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000129, 0, 0, 'Y', '2007-11-26 08:27:18.0', 100, '2007-11-26 08:27:18.0', 100, 'lbr_PostTax', 'LBRA', 'Post Tax', 'Post Tax', 'Indicates if the Tax should be Posted', 'Indicates if the Tax should be Posted', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000130, 0, 0, 'Y', '2007-11-27 09:49:53.0', 100, '2007-11-27 09:49:53.0', 100, 'lbr_TaxAmt', 'LBRA', 'Tax Amount', 'Tax Amount', 'Defines the Tax Amount', 'Defines the Tax Amount', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000131, 0, 0, 'Y', '2007-12-03 11:17:59.0', 100, '2007-12-03 11:17:59.0', 100, 'LBR_BankInfo_ID', 'LBRA', 'Bank Info', 'Bank Info', 'Primary key table LBR_BankInfo', 'Primary key table LBR_BankInfo', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000132, 0, 0, 'Y', '2007-12-03 11:27:17.0', 100, '2007-12-03 11:27:17.0', 100, 'lbr_OccurType', 'LBRA', 'Occurrence Type', 'Occurrence Type', 'Defines the Occurrence Type', 'Defines the Occurrence Type', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000133, 0, 0, 'Y', '2007-12-03 11:31:22.0', 100, '2007-12-03 11:31:22.0', 100, 'lbr_OccurNo', 'LBRA', 'Occurrence Number', 'Occurrence Number', 'Defines the Occurrence Number', 'Defines the Occurrence Number', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000134, 0, 0, 'Y', '2007-12-04 14:21:03.0', 100, '2007-12-04 14:21:03.0', 100, 'LBR_NCM_ID', 'LBRA', 'NCM', 'NCM', 'Primary key table LBR_NCM', 'Primary key table LBR_NCM', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000137, 0, 0, 'Y', '2007-12-06 13:49:05.0', 100, '2007-12-06 13:49:30.0', 100, 'LBR_CFOP_ID', 'LBRA', 'CFOP', 'CFOP', 'Primary key table LBR_CFOP', 'Primary key table LBR_CFOP', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000144, 0, 0, 'Y', '2007-12-07 10:12:46.0', 100, '2007-12-07 10:12:46.0', 100, 'lbr_DestionationType', 'LBRA', 'Destination Type', 'Destination Type', 'Defines the Destination Type', 'Defines the Destination Type', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000145, 0, 0, 'Y', '2007-12-07 10:17:54.0', 100, '2007-12-07 10:23:38.0', 100, 'LBR_ProductCategory_ID', 'LBRA', 'Product Category', 'Product Category', 'Primary key table LBR_ProductCategory', 'Primary key table LBR_ProductCategory', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000147, 0, 0, 'Y', '2007-12-07 10:45:23.0', 100, '2007-12-07 10:46:22.0', 100, 'lbr_TransactionType', 'LBRA', 'Transaction Type', 'Transaction Type', 'Defines the Transaction Type', 'Defines the Transaction Type', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000148, 0, 0, 'Y', '2007-12-07 10:59:45.0', 100, '2007-12-07 11:01:01.0', 100, 'lbr_IsManufactured', 'LBRA', 'Is Manufactured', 'Is Manufactured', 'Defines if the Product is Manufactured', 'Defines if the Product is Manufactured', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000149, 0, 0, 'Y', '2007-12-07 11:05:45.0', 100, '2007-12-07 11:05:45.0', 100, 'LBR_BPartnerCategory_ID', 'LBRA', 'BPartner Category', 'BPartner Category', 'Primary key table LBR_BPartnerCategory', 'Primary key table LBR_BPartnerCategory', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000142, 0, 0, 'Y', '2007-12-07 09:54:14.0', 100, '2007-12-07 09:54:14.0', 100, 'LBR_CFOPLine_ID', 'LBRA', 'CFOP Line', 'CFOP Line', 'Primary key table LBR_CFOPLine', 'Primary key table LBR_CFOPLine', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000146, 0, 0, 'Y', '2007-12-07 10:42:44.0', 100, '2007-12-07 15:35:11.0', 100, 'lbr_IsSubTributaria', 'LBRA', 'Is Substituicao Tributaria', 'Is Substituicao Tributaria', 'Defines the Is Substituicao Tributaria Status', 'Defines the Is Substituicao Tributaria Status', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000151, 0, 0, 'Y', '2007-12-10 09:04:52.0', 100, '2007-12-10 09:04:52.0', 100, 'LBR_CustomerCategory_ID', 'LBRA', 'Customer Category', 'Customer Category', 'Defines the Customer Category', 'Defines the Customer Category', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000152, 0, 0, 'Y', '2007-12-10 09:05:50.0', 100, '2007-12-10 09:05:50.0', 100, 'LBR_VendorCategory_ID', 'LBRA', 'Vendor Category', 'Vendor Category', 'Defines the Vendor Category', 'Defines the Vendor Category', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000153, 0, 0, 'Y', '2007-12-10 15:03:13.0', 100, '2007-12-10 15:03:13.0', 100, 'LBR_ICMSMatrix_ID', 'LBRA', 'ICMS Matrix', 'ICMS Matrix', 'Primary key table LBR_ICMSMatrix', 'Primary key table LBR_ICMSMatrix', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000155, 0, 0, 'Y', '2007-12-10 15:44:54.0', 100, '2007-12-10 15:44:54.0', 100, 'LBR_TaxConfiguration_ID', 'LBRA', 'Tax Configuration', 'Tax Configuration', 'Primary key table LBR_TaxConfiguration', 'Primary key table LBR_TaxConfiguration', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000156, 0, 0, 'Y', '2007-12-11 09:30:52.0', 100, '2007-12-11 09:30:52.0', 100, 'LBR_FiscalGroup_Product_ID', 'LBRA', 'Fiscal Group - Product', 'Fiscal Group - Product', 'Primary key table LBR_FiscalGroup_Product', 'Primary key table LBR_FiscalGroup_Product', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000157, 0, 0, 'Y', '2007-12-11 10:02:52.0', 100, '2007-12-11 10:02:52.0', 100, 'LBR_FiscalGroup_BPartner_ID', 'LBRA', 'Fiscal Group - Business Partner', 'Fiscal Group - Business Partner', 'Primary key table LBR_FiscalGroup_BPartner', 'Primary key table LBR_FiscalGroup_BPartner', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000159, 0, 0, 'Y', '2007-12-11 10:18:19.0', 100, '2007-12-11 10:19:02.0', 100, 'LBR_FiscalGroup_Vendor_ID', 'LBRA', 'Fiscal Group - Vendor', 'Fiscal Group - Vendor', 'Defines the Fiscal Group - Vendor', 'Defines the Fiscal Group - Vendor', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000158, 0, 0, 'Y', '2007-12-11 10:17:38.0', 100, '2007-12-11 10:19:05.0', 100, 'LBR_FiscalGroup_Customer_ID', 'LBRA', 'Fiscal Group - Customer', 'Fiscal Group - Customer', 'Defines the Fiscal Group - Customer', 'Defines the Fiscal Group - Customer', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000160, 0, 0, 'Y', '2007-12-11 10:31:36.0', 100, '2007-12-11 10:31:36.0', 100, 'lbr_ExceptionType', 'LBRA', 'Exception Type', 'Exception Type', 'Defines the Exception Type', 'Defines the Exception Type', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000161, 0, 0, 'Y', '2007-12-11 11:12:55.0', 100, '2007-12-11 11:12:55.0', 100, 'LBR_TaxConfig_BPartner_ID', 'LBRA', 'Business Partner Exception', 'Business Partner Exception', 'Primary key table LBR_TaxConfig_BPartner', 'Primary key table LBR_TaxConfig_BPartner', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000162, 0, 0, 'Y', '2007-12-11 11:26:26.0', 100, '2007-12-11 11:26:26.0', 100, 'LBR_TaxConfig_BPGroup_ID', 'LBRA', 'Business Partner Group Exception', 'Business Partner Group Exception', 'Primary key table LBR_TaxConfig_BPGroup', 'Primary key table LBR_TaxConfig_BPGroup', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000163, 0, 0, 'Y', '2007-12-11 13:20:29.0', 100, '2007-12-11 13:20:29.0', 100, 'LBR_TaxConfig_Product_ID', 'LBRA', 'Product Exception', 'Product Exception', 'Primary key table LBR_TaxConfig_Product', 'Primary key table LBR_TaxConfig_Product', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000164, 0, 0, 'Y', '2007-12-11 13:37:46.0', 100, '2007-12-11 13:37:46.0', 100, 'LBR_TaxConfig_ProductGroup_ID', 'LBRA', 'Product Group Exception', 'Product Group Exception', 'Primary key table LBR_TaxConfig_ProductGroup', 'Primary key table LBR_TaxConfig_ProductGroup', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000165, 0, 0, 'Y', '2007-12-11 13:49:28.0', 100, '2007-12-11 13:49:28.0', 100, 'LBR_TaxConfig_Region_ID', 'LBRA', 'Region Exception', 'Region Exception', 'Primary key table LBR_TaxConfig_Region', 'Primary key table LBR_TaxConfig_Region', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000166, 0, 0, 'Y', '2007-12-12 08:53:46.0', 100, '2007-12-12 08:53:46.0', 100, 'lbr_Interest', 'LBRA', 'Interest', 'Interest', 'Defines the Interest', 'Defines the Interest', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000169, 0, 0, 'Y', '2007-12-15 10:23:55.0', 100, '2007-12-15 10:23:55.0', 100, 'LBR_TaxName_ID', 'LBRA', 'Tax Name', 'Tax Name', 'Primary key table LBR_TaxName', 'Primary key table LBR_TaxName', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000170, 0, 0, 'Y', '2007-12-15 10:40:12.0', 100, '2007-12-15 10:40:12.0', 100, 'lbr_TaxType', 'LBRA', 'Tax Type', 'Tax Type', 'Define the Tax Type', 'Define the Tax Type', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000171, 0, 0, 'Y', '2007-12-15 10:45:02.0', 100, '2007-12-15 10:45:02.0', 100, 'HasWithHold', 'LBRA', 'Has WithHold', 'Has WithHold', 'Defines if the Tax, has WithHold', 'Defines if the Tax, has WithHold', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000172, 0, 0, 'Y', '2007-12-15 10:55:11.0', 100, '2007-12-15 10:55:11.0', 100, 'WithHoldThreshold', 'LBRA', 'WithHold Threshold', 'WithHold Threshold', 'Defines the WithHold Threshold ', 'Defines the WithHold Threshold ', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000173, 0, 0, 'Y', '2007-12-15 11:08:06.0', 100, '2007-12-15 11:08:53.0', 100, 'LBR_TaxFormula_ID', 'LBRA', 'Tax Formula', 'Tax Formula', 'Primary key table LBR_TaxFormula', 'Primary key table LBR_TaxFormula', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000174, 0, 0, 'Y', '2007-12-15 11:18:04.0', 100, '2007-12-15 11:18:04.0', 100, 'lbr_Formula', 'LBRA', 'Formula', 'Formula', 'Defines the Tax Formula', 'Defines the Tax Formula', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000175, 0, 0, 'Y', '2008-01-02 10:57:27.0', 100, '2008-01-02 10:57:27.0', 100, 'lbr_TaxBaseAmt', 'LBRA', 'Tax Base Amount', 'Tax Base Amount', 'Defines the Tax Base Amount', 'Defines the Tax Base Amount', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000176, 0, 0, 'Y', '2008-01-04 08:51:00.0', 100, '2008-01-04 08:51:00.0', 100, 'lbr_FormulaNetWorth', 'LBRA', 'Formula NetWorth', 'Formula NetWorth', 'Defines the Tax Formula NetWorth', 'Defines the Tax Formula NetWorth', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000177, 0, 0, 'Y', '2008-01-04 13:22:36.0', 100, '2008-01-04 13:22:36.0', 100, 'LBR_NotaFiscal_ID', 'LBRA', 'Nota Fiscal', 'Nota Fiscal', 'Primary key table LBR_NotaFiscal', 'Primary key table LBR_NotaFiscal', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000178, 0, 0, 'Y', '2008-01-04 13:45:15.0', 100, '2008-01-04 14:37:43.0', 100, 'lbr_BPAddress1', 'LBRA', 'BP Address 1', 'BP Address 1', 'BP Address 1 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Address 1 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000179, 0, 0, 'Y', '2008-01-04 13:46:21.0', 100, '2008-01-04 14:37:51.0', 100, 'lbr_BPAddress2', 'LBRA', 'BP Address 2', 'BP Address 2', 'BP Address 2 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Address 2 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000180, 0, 0, 'Y', '2008-01-04 13:46:41.0', 100, '2008-01-04 14:37:56.0', 100, 'lbr_BPAddress3', 'LBRA', 'BP Address 3', 'BP Address 3', 'BP Address 3 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Address 3 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000181, 0, 0, 'Y', '2008-01-04 13:46:54.0', 100, '2008-01-04 14:38:03.0', 100, 'lbr_BPAddress4', 'LBRA', 'BP Address 4', 'BP Address 4', 'BP Address 4 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Address 4 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000187, 0, 0, 'Y', '2008-01-04 14:06:01.0', 100, '2008-01-04 14:38:10.0', 100, 'lbr_BPCNPJ', 'LBRA', 'BP CNPJ', 'BP CNPJ', 'BP CNPJ - Copied from the BP into Brazilan Legal and Tax Books', 'BP CNPJ - Copied from the BP into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000182, 0, 0, 'Y', '2008-01-04 13:50:07.0', 100, '2008-01-04 14:38:15.0', 100, 'lbr_BPCity', 'LBRA', 'BP City', 'BP City', 'BP City - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP City - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000183, 0, 0, 'Y', '2008-01-04 13:53:48.0', 100, '2008-01-04 14:38:21.0', 100, 'lbr_BPCountry', 'LBRA', 'BP Country', 'BP Country', 'BP Country - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Country - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000189, 0, 0, 'Y', '2008-01-04 14:25:51.0', 100, '2008-01-04 14:38:26.0', 100, 'lbr_BPDeliveryAddress1', 'LBRA', 'BP Delivery Address 1', 'BP Delivery Address 1', 'BP Delivery Address 1 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery Address 1 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000190, 0, 0, 'Y', '2008-01-04 14:26:41.0', 100, '2008-01-04 14:38:31.0', 100, 'lbr_BPDeliveryAddress2', 'LBRA', 'BP Delivery Address 2', 'BP Delivery Address 2', 'BP Delivery Address 2 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery Address 2 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000191, 0, 0, 'Y', '2008-01-04 14:27:21.0', 100, '2008-01-04 14:38:36.0', 100, 'lbr_BPDeliveryAddress3', 'LBRA', 'BP Delivery Address 3', 'BP Delivery Address 3', 'BP Delivery Address 3 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery Address 3 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000199, 0, 0, 'Y', '2008-01-04 14:34:04.0', 100, '2008-01-04 14:39:46.0', 100, 'lbr_BPShipperAddress3', 'LBRA', 'BP Shipper Address 3', 'BP Shipper Address 3', 'BP Shipper Address 3 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper Address 3 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000200, 0, 0, 'Y', '2008-01-04 14:35:41.0', 100, '2008-01-04 14:39:55.0', 100, 'lbr_BPShipperAddress4', 'LBRA', 'BP Shipper Address 4', 'BP Shipper Address 4', 'BP Shipper Address 4 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper Address 4 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000192, 0, 0, 'Y', '2008-01-04 14:28:09.0', 100, '2008-01-04 14:38:40.0', 100, 'lbr_BPDeliveryAddress4', 'LBRA', 'BP Delivery Address 4', 'BP Delivery Address 4', 'BP Delivery Address 4 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery Address 4 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000188, 0, 0, 'Y', '2008-01-04 14:07:01.0', 100, '2008-01-04 14:38:45.0', 100, 'lbr_BPIE', 'LBRA', 'BP IE', 'BP IE', 'BP IE - Copied from the BP into Brazilan Legal and Tax Books', 'BP IE - Copied from the BP into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000193, 0, 0, 'Y', '2008-01-04 14:29:29.0', 100, '2008-01-04 14:38:53.0', 100, 'lbr_BPInvoiceAddress1', 'LBRA', 'BP Invoice Address 1', 'BP Invoice Address 1', 'BP Invoice Address 1 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice Address 1 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000194, 0, 0, 'Y', '2008-01-04 14:30:03.0', 100, '2008-01-04 14:38:59.0', 100, 'lbr_BPInvoiceAddress2', 'LBRA', 'BP Invoice Address 2', 'BP Invoice Address 2', 'BP Invoice Address 2 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice Address 2 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000195, 0, 0, 'Y', '2008-01-04 14:30:41.0', 100, '2008-01-04 14:39:03.0', 100, 'lbr_BPInvoiceAddress3', 'LBRA', 'BP Invoice Address 3', 'BP Invoice Address 3', 'BP Invoice Address 3 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice Address 3 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000196, 0, 0, 'Y', '2008-01-04 14:31:14.0', 100, '2008-01-04 14:39:12.0', 100, 'lbr_BPInvoiceAddress4', 'LBRA', 'BP Invoice Address 4', 'BP Invoice Address 4', 'BP Invoice Address 4 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice Address 4 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000186, 0, 0, 'Y', '2008-01-04 13:59:05.0', 100, '2008-01-04 14:39:21.0', 100, 'lbr_BPPhone', 'LBRA', 'BP Phone', 'BP Phone', 'BP Phone - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Phone - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000184, 0, 0, 'Y', '2008-01-04 13:54:39.0', 100, '2008-01-04 14:39:27.0', 100, 'lbr_BPPostal', 'LBRA', 'BP Postal', 'BP Postal', 'BP Postal - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Postal - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000185, 0, 0, 'Y', '2008-01-04 13:56:23.0', 100, '2008-01-04 14:39:32.0', 100, 'lbr_BPRegion', 'LBRA', 'BP Region', 'BP Region', 'BP Region - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Region - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000197, 0, 0, 'Y', '2008-01-04 14:32:48.0', 100, '2008-01-04 14:39:37.0', 100, 'lbr_BPShipperAddress1', 'LBRA', 'BP Shipper Address 1', 'BP Shipper Address 1', 'BP Shipper Address 1 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper Address 1 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000198, 0, 0, 'Y', '2008-01-04 14:33:28.0', 100, '2008-01-04 14:39:42.0', 100, 'lbr_BPShipperAddress2', 'LBRA', 'BP Shipper Address 2', 'BP Shipper Address 2', 'BP Shipper Address 2 - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper Address 2 - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000201, 0, 0, 'Y', '2008-01-04 14:45:56.0', 100, '2008-01-04 14:45:56.0', 100, 'lbr_BPDeliveryCity', 'LBRA', 'BP Delivery City', 'BP Delivery City', 'BP Delivery City - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery City - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000202, 0, 0, 'Y', '2008-01-04 14:46:40.0', 100, '2008-01-04 14:46:40.0', 100, 'lbr_BPDeliveryCountry', 'LBRA', 'BP Delivery Country', 'BP Delivery Country', 'BP Delivery Country - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery Country - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000203, 0, 0, 'Y', '2008-01-04 14:47:35.0', 100, '2008-01-04 14:47:35.0', 100, 'lbr_BPDeliveryCNPJ', 'LBRA', 'BP Delivery CNPJ', 'BP Delivery CNPJ', 'BP Delivery CNPJ - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery CNPJ - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000204, 0, 0, 'Y', '2008-01-04 14:48:16.0', 100, '2008-01-04 14:48:16.0', 100, 'lbr_BPDeliveryIE', 'LBRA', 'BP Delivery IE', 'BP Delivery IE', 'BP Delivery IE - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery IE - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000205, 0, 0, 'Y', '2008-01-04 14:49:12.0', 100, '2008-01-04 14:49:12.0', 100, 'lbr_BPDeliveryPostal', 'LBRA', 'BP Delivery Postal', 'BP Delivery Postal', 'BP Delivery Postal - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Delivery Postal - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000206, 0, 0, 'Y', '2008-01-04 14:51:56.0', 100, '2008-01-04 14:51:56.0', 100, 'lbr_BPInvoiceCity', 'LBRA', 'BP Invoice City', 'BP Invoice City', 'BP Invoice City - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice City - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000207, 0, 0, 'Y', '2008-01-04 14:52:59.0', 100, '2008-01-04 14:52:59.0', 100, 'lbr_BPInvoiceCountry', 'LBRA', 'BP Invoice Country', 'BP Invoice Country', 'BP Invoice Country - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice Country - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000208, 0, 0, 'Y', '2008-01-04 14:54:02.0', 100, '2008-01-04 14:54:02.0', 100, 'lbr_BPInvoiceCNPJ', 'LBRA', 'BP Invoice CNPJ', 'BP Invoice CNPJ', 'BP Invoice CNPJ - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice CNPJ - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000209, 0, 0, 'Y', '2008-01-04 14:55:01.0', 100, '2008-01-04 14:55:01.0', 100, 'lbr_BPInvoiceIE', 'LBRA', 'BP Invoice IE', 'BP Invoice IE', 'BP Invoice IE - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice IE - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000211, 0, 0, 'Y', '2008-01-07 09:06:03.0', 100, '2008-01-07 09:06:03.0', 100, 'lbr_BPDeliveryRegion', 'LBRA', 'BP DeliveryRegion', 'BP DeliveryRegion', 'BP DeliveryRegion - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP DeliveryRegion - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000212, 0, 0, 'Y', '2008-01-07 09:17:35.0', 100, '2008-01-07 09:17:35.0', 100, 'lbr_BPInvoiceRegion', 'LBRA', 'BP InvoiceRegion', 'BP InvoiceRegion', 'BP InvoiceRegion - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP InvoiceRegion - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000213, 0, 0, 'Y', '2008-01-07 09:25:15.0', 100, '2008-01-07 09:25:15.0', 100, 'lbr_BPShipperCNPJ', 'LBRA', 'BP Shipper CNPJ', 'BP Shipper CNPJ', 'BP Shipper CNPJ - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper CNPJ - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000214, 0, 0, 'Y', '2008-01-07 09:25:59.0', 100, '2008-01-07 09:25:59.0', 100, 'lbr_BPShipperCity', 'LBRA', 'BP Shipper City', 'BP Shipper City', 'BP Shipper City - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper City - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000215, 0, 0, 'Y', '2008-01-07 09:29:18.0', 100, '2008-01-07 09:29:18.0', 100, 'lbr_BPShipperCountry', 'LBRA', 'BP Shipper Country', 'BP Shipper Country', 'BP Shipper Country - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper Country - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000216, 0, 0, 'Y', '2008-01-07 09:30:39.0', 100, '2008-01-07 09:30:39.0', 100, 'lbr_BPShipperIE', 'LBRA', 'BP Shipper IE', 'BP Shipper IE', 'BP Shipper IE - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper IE - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000217, 0, 0, 'Y', '2008-01-07 09:31:47.0', 100, '2008-01-07 09:31:47.0', 100, 'lbr_BPShipperPostal', 'LBRA', 'BP Shipper Postal', 'BP Shipper Postal', 'BP Shipper Postal - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Shipper Postal - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000218, 0, 0, 'Y', '2008-01-07 09:32:50.0', 100, '2008-01-07 09:32:50.0', 100, 'lbr_BPShipperRegion', 'LBRA', 'BP ShipperRegion', 'BP ShipperRegion', 'BP ShipperRegion - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP ShipperRegion - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000219, 0, 0, 'Y', '2008-01-07 16:09:14.0', 100, '2008-01-07 16:09:14.0', 100, 'LBR_NotaFiscalLine_ID', 'LBRA', 'Nota Fiscal Line', 'Nota Fiscal Line', 'Primary key table LBR_NotaFiscalLine', 'Primary key table LBR_NotaFiscalLine', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000220, 0, 0, 'Y', '2008-01-08 09:21:40.0', 100, '2008-01-08 09:21:40.0', 100, 'lbr_BPInvoicePostal', 'LBRA', 'BP Invoice Postal', 'BP Invoice Postal', 'BP Invoice Postal - Copied from the BP Location into Brazilan Legal and Tax Books', 'BP Invoice Postal - Copied from the BP Location into Brazilan Legal and Tax Books', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000221, 0, 0, 'Y', '2008-01-08 09:34:52.0', 100, '2008-01-08 09:34:52.0', 100, 'lbr_GrossWeight', 'LBRA', 'Gross Weight', 'Gross Weight', 'Defines the Gross Weight', 'Defines the Gross Weight', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000222, 0, 0, 'Y', '2008-01-08 09:35:40.0', 100, '2008-01-08 09:35:40.0', 100, 'lbr_NetWeight', 'LBRA', 'Net Weight', 'Net Weight', 'Defines the Net Weight', 'Defines the Net Weight', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000223, 0, 0, 'Y', '2008-01-08 09:44:22.0', 100, '2008-01-08 09:44:22.0', 100, 'lbr_InsuranceAmt', 'LBRA', 'Insurance Amt', 'Insurance Amt', 'Defines the Insurance Amt', 'Defines the Insurance Amt', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000224, 0, 0, 'Y', '2008-01-08 09:50:38.0', 100, '2008-01-08 09:50:38.0', 100, 'lbr_NCMReference', 'LBRA', 'NCM Reference', 'NCM Reference', 'Defines the NCM Reference', 'Defines the NCM Reference', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000225, 0, 0, 'Y', '2008-01-08 09:52:38.0', 100, '2008-01-08 09:52:38.0', 100, 'lbr_CFOPReference', 'LBRA', 'CFOP Reference', 'CFOP Reference', 'Defines the CFOP Reference', 'Defines the CFOP Reference', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000226, 0, 0, 'Y', '2008-01-08 10:07:03.0', 100, '2008-01-08 10:07:03.0', 100, 'lbr_UOMName', 'LBRA', 'UOM Name', 'UOM Name', 'Defines the UOM Name', 'Defines the UOM Name', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000227, 0, 0, 'Y', '2008-01-08 10:10:50.0', 100, '2008-01-08 10:10:50.0', 100, 'lbr_NCMName', 'LBRA', 'NCM Name', 'NCM Name', 'Defines the NCM Name', 'Defines the NCM Name', NULL, NULL, NULL, NULL);
INSERT INTO ADEMPIERE.AD_ELEMENT(ad_element_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, columnname, entitytype, name, printname, description, help, po_name, po_printname, po_description, po_help)
  VALUES(1000228, 0, 0, 'Y', '2008-01-08 10:11:27.0', 100, '2008-01-08 10:11:27.0', 100, 'lbr_CFOPName', 'LBRA', 'CFOP Name', 'CFOP Name', 'Defines the CFOP Name', 'Defines the CFOP Name', NULL, NULL, NULL, NULL);
