INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000026, 0, 0, 'Y', '2007-12-15 11:06:52.0', 100, '2007-12-15 11:06:52.0', 100, 'Tax Formula', NULL, NULL, 'LBR_TaxFormula', 'N', '3', 'LBRA', 1000014, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000025, 0, 0, 'Y', '2007-12-15 10:22:26.0', 100, '2007-12-15 11:22:02.0', 100, 'Tax Name', NULL, NULL, 'LBR_TaxName', 'N', '3', 'LBRA', 1000014, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000001, 0, 0, 'Y', '2007-11-01 11:26:41.0', 100, '2007-11-07 09:59:41.0', 100, 'Boleto', 'Table LBR_Boleto', NULL, 'LBR_Boleto', 'N', '3', 'LBRA', NULL, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000002, 0, 0, 'Y', '2007-11-07 10:00:06.0', 100, '2007-11-07 10:00:06.0', 100, 'CNAB', 'Table LBR_CNAB', NULL, 'LBR_CNAB', 'N', '3', 'LBRA', NULL, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000005, 0, 0, 'Y', '2007-11-12 11:49:26.0', 100, '2007-11-12 12:22:59.0', 100, 'DocPrint Field', NULL, NULL, 'LBR_DocPrintField', 'N', '4', 'LBRA', 1000001, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000004, 0, 0, 'Y', '2007-11-12 09:28:28.0', 100, '2007-11-14 11:50:59.0', 100, 'DocPrint', 'Primary key table LBR_DocPrint', NULL, 'LBR_DocPrint', 'N', '4', 'LBRA', 1000001, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000006, 0, 0, 'Y', '2007-11-14 14:23:40.0', 100, '2007-11-27 09:52:13.0', 100, 'Brazilian Tax', NULL, NULL, 'LBR_Tax', 'N', '3', 'LBRA', NULL, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000003, 0, 0, 'Y', '2007-11-07 11:02:36.0', 100, '2007-12-03 15:05:58.0', 100, 'Bank', 'Primary Key table LBR_Bank', NULL, 'LBR_Bank', 'N', '7', 'LBRA', 1000000, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000007, 0, 0, 'Y', '2007-11-26 08:15:05.0', 100, '2007-11-27 09:52:17.0', 100, 'Tax Line', 'Primary key table LBR_TaxLine', NULL, 'LBR_TaxLine', 'N', '3', 'LBRA', NULL, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000008, 0, 0, 'Y', '2007-12-03 11:17:26.0', 100, '2007-12-03 15:09:17.0', 100, 'Bank Info', 'Primary key table LBR_BankInfo', NULL, 'LBR_BankInfo', 'N', '7', 'LBRA', 1000000, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000010, 0, 0, 'Y', '2007-12-06 13:48:01.0', 100, '2007-12-06 14:42:49.0', 100, 'CFOP', NULL, NULL, 'LBR_CFOP', 'N', '3', 'LBRA', 1000003, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000012, 0, 0, 'Y', '2007-12-07 09:53:24.0', 100, '2007-12-07 10:26:26.0', 100, 'CFOP Line', NULL, NULL, 'LBR_CFOPLine', 'N', '3', 'LBRA', 1000003, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000015, 0, 0, 'Y', '2007-12-10 15:01:39.0', 100, '2007-12-15 14:25:28.0', 100, 'ICMS Matrix', NULL, NULL, 'LBR_ICMSMatrix', 'N', '7', 'LBRA', 1000010, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000009, 0, 0, 'Y', '2007-12-04 14:20:15.0', 100, '2007-12-10 14:42:41.0', 100, 'NCM', NULL, NULL, 'LBR_NCM', 'N', '3', 'LBRA', 1000002, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000013, 0, 0, 'Y', '2007-12-07 10:26:22.0', 100, '2007-12-11 09:01:54.0', 100, 'Product Category', 'Primary key table LBR_ProductCategory', NULL, 'LBR_ProductCategory', 'N', '3', 'LBRA', 1000008, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000017, 0, 0, 'Y', '2007-12-11 09:30:05.0', 100, '2007-12-11 09:56:48.0', 100, 'Fiscal Group - Product', NULL, NULL, 'LBR_FiscalGroup_Product', 'N', '3', 'LBRA', 1000011, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000018, 0, 0, 'Y', '2007-12-11 10:00:30.0', 100, '2007-12-11 10:10:03.0', 100, 'Fiscal Group - Business Partner', NULL, NULL, 'LBR_FiscalGroup_BPartner', 'N', '3', 'LBRA', 1000012, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000014, 0, 0, 'Y', '2007-12-07 11:04:38.0', 100, '2007-12-11 09:23:40.0', 100, 'BPartner Category', 'Primary key table LBR_BPartnerCategory', NULL, 'LBR_BPartnerCategory', 'N', '3', 'LBRA', 1000009, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000016, 0, 0, 'Y', '2007-12-10 15:43:57.0', 100, '2007-12-11 11:10:59.0', 100, 'Tax Configuration', NULL, NULL, 'LBR_TaxConfiguration', 'N', '3', 'LBRA', 1000013, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000019, 0, 0, 'Y', '2007-12-11 11:11:40.0', 100, '2007-12-11 11:11:45.0', 100, 'Business Partner Exception', NULL, NULL, 'LBR_TaxConfig_BPartner', 'N', '3', 'LBRA', 1000013, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000020, 0, 0, 'Y', '2007-12-11 11:24:37.0', 100, '2007-12-11 11:24:37.0', 100, 'Business Partner Group Exception', NULL, NULL, 'LBR_TaxConfig_BPGroup', 'N', '3', 'LBRA', 1000013, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000021, 0, 0, 'Y', '2007-12-11 13:19:12.0', 100, '2007-12-11 13:19:12.0', 100, 'Product Exception', NULL, NULL, 'LBR_TaxConfig_Product', 'N', '3', 'LBRA', 1000013, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000023, 0, 0, 'Y', '2007-12-11 13:48:23.0', 100, '2007-12-11 13:48:23.0', 100, 'Region Exception', NULL, NULL, 'LBR_TaxConfig_Region', 'N', '3', 'LBRA', 1000013, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000022, 0, 0, 'Y', '2007-12-11 13:36:12.0', 100, '2007-12-11 13:36:12.0', 100, 'Product Group Exception', 'Primary key table LBR_TaxConfig_ProductGroup', NULL, 'LBR_TaxConfig_ProductGroup', 'N', '3', 'LBRA', 1000013, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000027, 0, 0, 'Y', '2008-01-04 13:21:57.0', 100, '2008-01-04 13:28:30.0', 100, 'Nota Fiscal', NULL, NULL, 'LBR_NotaFiscal', 'N', '1', 'LBRA', 1000015, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
INSERT INTO ADEMPIERE.AD_TABLE(ad_table_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, tablename, isview, accesslevel, entitytype, ad_window_id, ad_val_rule_id, loadseq, issecurityenabled, isdeleteable, ishighvolume, importtable, ischangelog, replicationtype, po_window_id, copycolumnsfromtable)
  VALUES(1000028, 0, 0, 'Y', '2008-01-07 16:08:13.0', 100, '2008-01-07 16:08:13.0', 100, 'Nota Fiscal Line', NULL, NULL, 'LBR_NotaFiscalLine', 'N', '1', 'LBRA', 1000015, NULL, 0, 'N', 'Y', 'N', 'N', 'N', 'L', NULL, 'N');
