INSERT INTO ADEMPIERE.AD_PROCESS_PARA(ad_process_para_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_process_id, seqno, ad_reference_id, ad_reference_value_id, ad_val_rule_id, columnname, iscentrallymaintained, fieldlength, ismandatory, isrange, defaultvalue, defaultvalue2, vformat, valuemin, valuemax, ad_element_id, entitytype)
  VALUES(1000004, 0, 0, 'Y', '2007-11-20 15:23:37.0', 100, '2007-11-20 15:24:30.0', 100, 'File_Directory', NULL, NULL, 1000001, 30, 38, NULL, NULL, 'File_Directory', 'Y', 22, 'Y', 'N', NULL, NULL, NULL, NULL, NULL, 50022, 'LBRA');
INSERT INTO ADEMPIERE.AD_PROCESS_PARA(ad_process_para_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_process_id, seqno, ad_reference_id, ad_reference_value_id, ad_val_rule_id, columnname, iscentrallymaintained, fieldlength, ismandatory, isrange, defaultvalue, defaultvalue2, vformat, valuemin, valuemax, ad_element_id, entitytype)
  VALUES(1000001, 0, 0, 'Y', '2007-11-12 15:58:55.0', 100, '2007-11-20 15:26:51.453', 100, 'Table Name', 'Identifies the Table or View Name', 'Identifies the Table or View Name', 1000000, 20, 10, NULL, NULL, 'lbr_TableName', 'Y', 0, 'Y', 'N', '@lbr_TableName@', NULL, NULL, NULL, NULL, 1000080, 'LBRA');
INSERT INTO ADEMPIERE.AD_PROCESS_PARA(ad_process_para_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_process_id, seqno, ad_reference_id, ad_reference_value_id, ad_val_rule_id, columnname, iscentrallymaintained, fieldlength, ismandatory, isrange, defaultvalue, defaultvalue2, vformat, valuemin, valuemax, ad_element_id, entitytype)
  VALUES(1000000, 0, 0, 'Y', '2007-11-12 15:58:18.0', 100, '2007-11-20 15:26:51.453', 100, 'DocPrint', 'Primary key table LBR_DocPrint', 'Primary key table LBR_DocPrint', 1000000, 10, 18, NULL, NULL, 'LBR_DocPrint_ID', 'Y', 22, 'Y', 'N', '@LBR_DocPrint_ID@', NULL, NULL, NULL, NULL, 1000078, 'LBRA');
INSERT INTO ADEMPIERE.AD_PROCESS_PARA(ad_process_para_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_process_id, seqno, ad_reference_id, ad_reference_value_id, ad_val_rule_id, columnname, iscentrallymaintained, fieldlength, ismandatory, isrange, defaultvalue, defaultvalue2, vformat, valuemin, valuemax, ad_element_id, entitytype)
  VALUES(1000002, 0, 0, 'Y', '2007-11-20 15:22:06.0', 100, '2007-11-20 15:26:51.453', 100, 'Bank Account', 'Account at the Bank', 'The Bank Account identifies an account at this Bank.', 1000001, 10, 30, NULL, NULL, 'C_BankAccount_ID', 'Y', 22, 'Y', 'N', NULL, NULL, NULL, NULL, NULL, 836, 'LBRA');
INSERT INTO ADEMPIERE.AD_PROCESS_PARA(ad_process_para_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_process_id, seqno, ad_reference_id, ad_reference_value_id, ad_val_rule_id, columnname, iscentrallymaintained, fieldlength, ismandatory, isrange, defaultvalue, defaultvalue2, vformat, valuemin, valuemax, ad_element_id, entitytype)
  VALUES(1000003, 0, 0, 'Y', '2007-11-20 15:22:49.0', 100, '2007-11-20 15:26:51.453', 100, 'Document Date', 'Identifies the Document Date', 'Identifies the Document Date', 1000001, 20, 15, NULL, NULL, 'lbr_DocDate', 'Y', 22, 'Y', 'Y', '@#Date@', '@#Date@', NULL, NULL, NULL, 1000018, 'LBRA');
INSERT INTO ADEMPIERE.AD_PROCESS_PARA(ad_process_para_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_process_id, seqno, ad_reference_id, ad_reference_value_id, ad_val_rule_id, columnname, iscentrallymaintained, fieldlength, ismandatory, isrange, defaultvalue, defaultvalue2, vformat, valuemin, valuemax, ad_element_id, entitytype)
  VALUES(1000005, 0, 0, 'Y', '2007-12-03 15:18:09.0', 100, '2007-12-03 15:20:17.25', 100, 'File Name', 'Name of the local file or URL', 'Name of a file in the local directory space - or URL (file://.., http://.., ftp://..)', 1000002, 10, 39, NULL, NULL, 'FileName', 'Y', 22, 'Y', 'N', NULL, NULL, NULL, NULL, NULL, 2295, 'LBRA');
INSERT INTO ADEMPIERE.AD_PROCESS_PARA(ad_process_para_id, ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby, name, description, help, ad_process_id, seqno, ad_reference_id, ad_reference_value_id, ad_val_rule_id, columnname, iscentrallymaintained, fieldlength, ismandatory, isrange, defaultvalue, defaultvalue2, vformat, valuemin, valuemax, ad_element_id, entitytype)
  VALUES(1000006, 0, 0, 'Y', '2007-12-03 15:18:49.0', 100, '2007-12-03 15:24:05.0', 100, 'File_Directory', NULL, NULL, 1000002, 20, 38, NULL, NULL, 'File_Directory', 'N', 22, 'Y', 'N', NULL, NULL, NULL, NULL, NULL, 50022, 'LBRA');
